# Generated by Django 4.2.25 on 2025-10-12 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField()),
                ('external_app', models.CharField(max_length=64)),
                ('external_user_id', models.CharField(max_length=256)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='BridgeThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_app', models.CharField(max_length=64)),
                ('external_thread_id', models.CharField(max_length=256)),
                ('linked_thread_id', models.UUIDField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['external_app', 'external_thread_id'], name='bridge_brid_externa_660504_idx')],
            },
        ),
        migrations.CreateModel(
            name='BridgeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'INBOUND'), ('OUTBOUND', 'OUTBOUND')], max_length=8)),
                ('message_type', models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('FILE', 'FILE'), ('LINK', 'LINK'), ('REACTION', 'REACTION')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('external_message_id', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(default='RECEIVED', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=128, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('bridge_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bridge.bridgethread')),
            ],
        ),
        migrations.CreateModel(
            name='BridgeAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rule_name', models.CharField(max_length=128)),
                ('trigger_type', models.CharField(choices=[('KEYWORD', 'KEYWORD'), ('TIME', 'TIME'), ('EVENT', 'EVENT')], max_length=16)),
                ('action_type', models.CharField(choices=[('REPLY', 'REPLY'), ('FORWARD', 'FORWARD'), ('ALERT', 'ALERT'), ('ANALYTICS', 'ANALYTICS')], max_length=16)),
                ('action_payload', models.JSONField(default=dict)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('bridge_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='bridge.bridgethread')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BridgeAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_messages', models.IntegerField(default=0)),
                ('inbound_count', models.IntegerField(default=0)),
                ('outbound_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('top_external_apps', models.JSONField(default=dict)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('bridge_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='bridge.bridgeaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='bridgeaccount',
            index=models.Index(fields=['user_id', 'external_app'], name='bridge_brid_user_id_59ee2a_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgemessage',
            index=models.Index(fields=['bridge_thread', 'external_message_id', 'status'], name='bridge_brid_bridge__b2a95c_idx'),
        ),
    ]
