# Generated by Django 4.2.25 on 2026-10-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
