# Generated by Django 5.2.8 on 2026-01-05 13:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.TextField(blank=True)),
                ("styled_text", models.JSONField(blank=True, default=dict)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("poll", models.JSONField(blank=True, default=dict)),
                ("event", models.JSONField(blank=True, default=dict)),
                ("link", models.URLField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="partner_posts", to=settings.AUTH_USER_MODEL)),
                ("partner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="partners.partner")),
            ],
            options={
                "db_table": "partner_post",
            },
        ),
        migrations.AddIndex(
            model_name="partnerpost",
            index=models.Index(fields=["partner", "created_at"], name="partner_po_partner_8e9d24_idx"),
        ),
    ]
