# Generated by Django 4.2.25 on 2026-01-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerpost'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerpost',
            new_name='partner_pos_partner_f8b11b_idx',
            old_name='partner_po_partner_8e9d24_idx',
        ),
    ]
