# Generated by Django 4.2.25 on 2026-01-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_post_comments_reactions_broadcast'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerpostcomment',
            new_name='partner_pos_post_id_f5e8f9_idx',
            old_name='partner_post_comment_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerpostreaction',
            new_name='partner_pos_post_id_3554e0_idx',
            old_name='partner_post_reaction_post_created_idx',
        ),
    ]
