# Generated by Codex on 2026-01-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_conversation_last_message_seq"),
        ("partners", "0005_rename_partner_post_comment_post_created_idx_partner_pos_post_id_f5e8f9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpost",
            name="comment_conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_post_comments",
                to="chat.conversation",
            ),
        ),
    ]
