# Generated by Django 4.2.25 on 2026-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partnerfeatureflag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerfeatureflag',
            new_name='partner_fea_partner_e5ede0_idx',
            old_name='partner_fe_partner_8a9a25_idx',
        ),
        migrations.AlterField(
            model_name='partnerfeatureflag',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
