# Generated by Codex on 2026-01-09
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0009_merge_0008_partner_join_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerJobPost",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("auto_assign", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("partner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="job_posts", to="partners.partner")),
            ],
            options={
                "db_table": "partner_job_post",
            },
        ),
        migrations.AddIndex(
            model_name="partnerjobpost",
            index=models.Index(fields=["partner", "is_active"], name="partner_jo_partner_0a9a8f_idx"),
        ),
        migrations.AddField(
            model_name="partnerapplication",
            name="job_post",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="applications", to="partners.partnerjobpost"),
        ),
        migrations.AddField(
            model_name="partnerapplication",
            name="stage_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerapplication",
            name="stage_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
