# Generated by Django 4.2.25 on 2026-01-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_merge_0008_partner_join_flow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerapplication',
            new_name='partner_app_partner_3fd062_idx',
            old_name='partner_ap_partner_4fd7c2_idx',
        ),
        migrations.RenameIndex(
            model_name='partnermembership',
            new_name='partner_mem_partner_e3d0ce_idx',
            old_name='partner_me_partner_90b7ef_idx',
        ),
    ]
