# Generated by Codex on 2026-01-09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0010_partner_job_posts"),
        ("partners", "0010_rename_partner_ap_partner_4fd7c2_idx_partner_app_partner_3fd062_idx_and_more"),
    ]

    operations = []
