# Generated by Django 4.2.25 on 2026-01-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_merge_0010_partner_job_posts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerjobpost',
            new_name='partner_job_partner_3a3139_idx',
            old_name='partner_jo_partner_0a9a8f_idx',
        ),
    ]
