# Generated by Django 4.2.25 on 2026-01-09 13:11

import apps.partners.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0012_rename_partner_jo_partner_0a9a8f_idx_partner_job_partner_3a3139_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='partners.partnerrole')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_role',
            },
        ),
        migrations.CreateModel(
            name='PartnerPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('settings', models.JSONField(blank=True, default=apps.partners.models._default_partner_policy)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_policy',
            },
        ),
        migrations.CreateModel(
            name='PartnerAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_audit_events', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_audit_event',
            },
        ),
        migrations.CreateModel(
            name='PartnerRoleAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('community', 'Community'), ('group', 'Group'), ('channel', 'Channel')], default='global', max_length=32)),
                ('scope_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='partners.partner')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='partners.partnerrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_role_assignment',
                'indexes': [models.Index(fields=['partner', 'user'], name='partner_rol_partner_a71d00_idx'), models.Index(fields=['partner', 'scope_type', 'scope_id'], name='partner_rol_partner_417035_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='partnerrole',
            index=models.Index(fields=['partner', 'name'], name='partner_rol_partner_6a3999_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerrole',
            unique_together={('partner', 'name')},
        ),
        migrations.AddIndex(
            model_name='partnerauditevent',
            index=models.Index(fields=['partner', 'created_at'], name='partner_aud_partner_e70f09_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerauditevent',
            index=models.Index(fields=['partner', 'action'], name='partner_aud_partner_985615_idx'),
        ),
    ]
