# Generated by Django 4.2.25 on 2026-01-09 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_partnerrole_partnerpolicy_partnerauditevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerWebhook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(blank=True, default=list)),
                ('secret', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_webhook',
                'indexes': [models.Index(fields=['partner', 'is_active'], name='partner_web_partner_4d8d73_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerIntegration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sso', 'SSO'), ('scim', 'SCIM'), ('webhook', 'Webhook')], max_length=32)),
                ('provider', models.CharField(blank=True, max_length=128)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_integration',
                'indexes': [models.Index(fields=['partner', 'kind'], name='partner_int_partner_d12663_idx')],
            },
        ),
    ]
