# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partners", "0014_partnerwebhook_partnerintegration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAutomationRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("trigger", models.CharField(db_index=True, max_length=64)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_status", models.CharField(blank=True, max_length=32)),
                ("last_run_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_automation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partner_automation_rule",
                "indexes": [
                    models.Index(fields=["partner", "trigger"], name="partner_aut_partner_9ec01a_idx"),
                    models.Index(fields=["partner", "is_active"], name="partner_aut_partner_4b7c2a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerReportSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_report_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_snapshots",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partner_report_snapshot",
                "indexes": [
                    models.Index(fields=["partner", "kind"], name="partner_rep_partner_5d0b86_idx"),
                    models.Index(fields=["partner", "created_at"], name="partner_rep_partner_4f8a1f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerExportJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("export_format", models.CharField(default="csv", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partner_export_job",
                "indexes": [
                    models.Index(fields=["partner", "status"], name="partner_exp_partner_fce1ad_idx"),
                    models.Index(fields=["partner", "kind"], name="partner_exp_partner_7791e6_idx"),
                ],
            },
        ),
    ]
