# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partners", "0015_partner_automation_reports_exports"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAccessRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("scope_type", models.CharField(default="global", max_length=32)),
                ("scope_id", models.CharField(blank=True, max_length=128)),
                ("justification", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_access_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="partners.partner",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests",
                        to="partners.partnerrole",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_access_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "partner_access_request",
                "indexes": [
                    models.Index(fields=["partner", "status"], name="partner_acc_partner_45d167_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerAccessReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("scope_type", models.CharField(default="global", max_length=32)),
                ("scope_id", models.CharField(blank=True, max_length=128)),
                ("findings", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_access_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_reviews",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partner_access_review",
                "indexes": [
                    models.Index(fields=["partner", "status"], name="partner_acc_partner_9e1e0b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerExportSchedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("export_format", models.CharField(default="csv", max_length=16)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_export_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_schedules",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partner_export_schedule",
                "indexes": [
                    models.Index(fields=["partner", "is_active"], name="partner_exp_partner_7b31e3_idx"),
                    models.Index(fields=["partner", "kind"], name="partner_exp_partner_3fefc5_idx"),
                ],
            },
        ),
    ]
