# Generated by Django 4.2.25 on 2026-01-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_partner_access_and_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partneraccessrequest',
            new_name='partner_acc_partner_f672b5_idx',
            old_name='partner_acc_partner_45d167_idx',
        ),
        migrations.RenameIndex(
            model_name='partneraccessreview',
            new_name='partner_acc_partner_308e63_idx',
            old_name='partner_acc_partner_9e1e0b_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerautomationrule',
            new_name='partner_aut_partner_99dcbe_idx',
            old_name='partner_aut_partner_9ec01a_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerautomationrule',
            new_name='partner_aut_partner_57f18c_idx',
            old_name='partner_aut_partner_4b7c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerexportjob',
            new_name='partner_exp_partner_39a567_idx',
            old_name='partner_exp_partner_fce1ad_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerexportjob',
            new_name='partner_exp_partner_419b82_idx',
            old_name='partner_exp_partner_7791e6_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerexportschedule',
            new_name='partner_exp_partner_154fda_idx',
            old_name='partner_exp_partner_7b31e3_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerexportschedule',
            new_name='partner_exp_partner_1fe9b7_idx',
            old_name='partner_exp_partner_3fefc5_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerreportsnapshot',
            new_name='partner_rep_partner_72ecbc_idx',
            old_name='partner_rep_partner_5d0b86_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerreportsnapshot',
            new_name='partner_rep_partner_575c94_idx',
            old_name='partner_rep_partner_4f8a1f_idx',
        ),
    ]
