# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.db import migrations, models
import django.utils.timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0016_partner_access_and_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerwebhook",
            name="retry_backoff_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="partnerwebhook",
            name="retry_limit",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name="PartnerWebhookDelivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event", models.CharField(max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("delivered", "Delivered"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="partners.partnerwebhook",
                    ),
                ),
            ],
            options={
                "db_table": "partner_webhook_delivery",
                "indexes": [
                    models.Index(fields=["status", "next_retry_at"], name="partner_web_status_7b7cb3_idx"),
                    models.Index(fields=["webhook", "created_at"], name="partner_web_webhook_2ec7f4_idx"),
                ],
            },
        ),
    ]
