# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0017_rename_partner_acc_partner_45d167_idx_partner_acc_partner_f672b5_idx_and_more"),
        ("partners", "0017_webhook_delivery_and_retry"),
    ]

    operations = []
