# Generated by Django 4.2.25 on 2026-01-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_merge_0017_webhook_and_rename'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerwebhookdelivery',
            new_name='partner_web_status_8cfcc7_idx',
            old_name='partner_web_status_7b7cb3_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerwebhookdelivery',
            new_name='partner_web_webhook_d7fcfd_idx',
            old_name='partner_web_webhook_2ec7f4_idx',
        ),
    ]
