# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0019_partner_setting"),
        ("partners", "0019_rename_partner_web_status_7b7cb3_idx_partner_web_status_8cfcc7_idx_and_more"),
    ]

    operations = []
