# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partners", "0020_merge_0019_partner_setting_and_webhook_rename"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerOrganizationProfile",
            fields=[
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_profile",
                        primary_key=True,
                        serialize=False,
                        to="partners.partner",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("industry", models.CharField(blank=True, max_length=128)),
                ("size", models.CharField(blank=True, max_length=64)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=255)),
                ("logo_url", models.URLField(blank=True)),
                ("brand_colors", models.JSONField(blank=True, default=list)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_org_profile_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "partner_organization_profile",
            },
        ),
    ]
