# Generated by Django 4.2.25 on 2026-01-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_merge_0019_partner_setting_and_webhook_rename'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnersetting',
            new_name='partner_set_partner_87251f_idx',
            old_name='partner_set_partner_0b9a64_idx',
        ),
    ]
