# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0021_partner_organization_profile"),
        ("partners", "0021_rename_partner_set_partner_0b9a64_idx_partner_set_partner_87251f_idx"),
    ]

    operations = []
