# Generated by Django 4.2.25 on 2026-01-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_partner_deactivation'),
        ('partners', '0024_lesson_access'),
    ]

    operations = [
    ]
