# Generated by Django 4.2.25 on 2026-01-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_partnerpost_rich_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpost',
            name='text',
            field=models.JSONField(blank=True, default=dict, help_text='ProseMirror-style document that captures the formatted text.'),
        ),
        migrations.AlterField(
            model_name='partnerpost',
            name='text_plain',
            field=models.TextField(blank=True, help_text='Plain text extracted from the rich document.'),
        ),
        migrations.AlterField(
            model_name='partnerpost',
            name='text_preview',
            field=models.CharField(blank=True, help_text='Preview text for lists/previews.', max_length=512),
        ),
    ]
