# Generated by Django 4.2.25 on 2026-01-26 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from apps.partners.models import _default_partner_profile_link_analytics


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_alter_partnerpost_text_alter_partnerpost_text_plain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_key', models.CharField(choices=[('broadcast_feed', 'Broadcast'), ('health', 'Health'), ('market', 'Market'), ('education', 'Education')], max_length=32)),
                ('linked', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=16)),
                ('analytics', models.JSONField(blank=True, default=_default_partner_profile_link_analytics)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_profile_link',
                'unique_together': {('partner', 'profile_key')},
            },
        ),
    ]
