# Generated by Django 4.2.25 on 2026-02-04 00:00

import uuid

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0028_partner_profile_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerOrganizationApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        max_length=32,
                        choices=[
                            ("kis", "KIS App"),
                            ("bible", "Bible App"),
                            ("external", "External App"),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=128)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_apps",
                        to="partners.partner",
                    ),
                ),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "partner_organization_app",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["partner", "type"], name="partner_org_app_partner_type_idx"),
                    models.Index(fields=["partner", "order"], name="partner_org_app_partner_order_idx"),
                ],
            },
        ),
    ]
