# Generated by Django 4.2.25 on 2026-02-05 00:00

from django.db import migrations, models


def _default_app_visibility():
    return ["owner", "admin", "manager"]


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0029_partner_organization_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerorganizationapp",
            name="visible_to",
            field=models.JSONField(default=_default_app_visibility, blank=True),
        ),
    ]
