# Generated by Django 4.2.25 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0030_partner_organization_app_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerorganizationapp",
            name="group",
            field=models.CharField(blank=True, max_length=128, default=""),
        ),
        migrations.AddField(
            model_name="partnerorganizationapp",
            name="badge_label",
            field=models.CharField(blank=True, max_length=128, default=""),
        ),
    ]
