# Generated by Django 4.2.25 on 2026-02-05 05:50

import apps.partners.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0031_partner_organization_app_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerorganizationapp',
            new_name='partner_org_partner_cacc3f_idx',
            old_name='partner_org_app_partner_type_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerorganizationapp',
            new_name='partner_org_partner_c035c8_idx',
            old_name='partner_org_app_partner_order_idx',
        ),
        migrations.AlterField(
            model_name='partnerorganizationapp',
            name='badge_label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='partnerorganizationapp',
            name='group',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='partnerorganizationapp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partnerorganizationapp',
            name='visible_to',
            field=models.JSONField(blank=True, default=apps.partners.models.default_app_visibility),
        ),
    ]
