# Generated by Django 4.2.25 on 2026-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0032_rename_partner_org_app_partner_type_idx_partner_org_partner_cacc3f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerorganizationapp",
            name="module",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="partnerorganizationapp",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
