# Generated by Django 4.2.25 on 2026-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0033_partner_organization_app_module_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerOrganizationAppAccessLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="access_logs",
                        to="partners.partnerorganizationapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="organization_app_access_logs",
                        to="accounts.user",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("data_scope", models.JSONField(blank=True, default=list)),
                ("consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "partner_organization_app_access_log",
                "indexes": [
                    models.Index(fields=["app", "created_at"], name="partner_org_app_access_app_created_idx"),
                    models.Index(fields=["user", "created_at"], name="partner_org_app_access_user_created_idx"),
                ],
                "verbose_name": "Partner organization app access log",
            },
        ),
    ]
