# Generated by Django 4.2.25 on 2026-02-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0034_partner_organization_app_access_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerorganizationapp',
            new_name='partner_org_app_pt_idx',
            old_name='partner_org_partner_cacc3f_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerorganizationapp',
            new_name='partner_org_app_po_idx',
            old_name='partner_org_partner_c035c8_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerorganizationappaccesslog',
            new_name='partner_org_app_id_a0db6f_idx',
            old_name='partner_org_app_access_app_created_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerorganizationappaccesslog',
            new_name='partner_org_user_id_bd4062_idx',
            old_name='partner_org_app_access_user_created_idx',
        ),
        migrations.AlterField(
            model_name='partnerorganizationapp',
            name='module',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
