# Generated by Django 4.2.25 on 2026-04-20 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_rename_partner_org_partner_cacc3f_idx_partner_org_app_pt_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerServerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_categories', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_server_category',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['partner', 'order'], name='partner_ser_partner_66fb47_idx')],
                'unique_together': {('partner', 'slug')},
            },
        ),
    ]
