# Generated by Django 4.2.25 on 2026-04-20 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_channel_options_alter_channel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0036_partnerservercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerChannelPermissionOverwrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('role', 'Role'), ('member', 'Member')], max_length=16)),
                ('allow_permissions', models.JSONField(blank=True, default=list)),
                ('deny_permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overwrites', to='channels.channel')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_permission_overwrites', to='partners.partner')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_permission_overwrites', to='partners.partnerrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_channel_permission_overwrites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_channel_permission_overwrite',
                'indexes': [models.Index(fields=['partner', 'channel', 'subject_type'], name='partner_cha_partner_4b8d02_idx'), models.Index(fields=['channel', 'role'], name='partner_cha_channel_f6b764_idx'), models.Index(fields=['channel', 'user'], name='partner_cha_channel_b2640b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='partnerchannelpermissionoverwrite',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False), ('subject_type', 'role')), fields=('channel', 'role'), name='partner_channel_overwrite_unique_role'),
        ),
        migrations.AddConstraint(
            model_name='partnerchannelpermissionoverwrite',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_type', 'member'), ('user__isnull', False)), fields=('channel', 'user'), name='partner_channel_overwrite_unique_user'),
        ),
    ]
