# Generated by Django 4.2.25 on 2026-04-20 11:55

import apps.partners.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0037_partnerchannelpermissionoverwrite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.partners.models.generate_partner_invite_code, max_length=32, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('membership_role', models.CharField(default='member', max_length=16)),
                ('auto_assign', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner_invite',
            },
        ),
        migrations.CreateModel(
            name='PartnerModerationAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('mute', 'Mute'), ('unmute', 'Unmute'), ('timeout', 'Timeout'), ('kick', 'Kick'), ('ban', 'Ban'), ('unban', 'Unban')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'partner_moderation_action',
            },
        ),
        migrations.CreateModel(
            name='PartnerOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rules_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('selected_role_ids', models.JSONField(blank=True, default=list)),
                ('selected_channel_ids', models.JSONField(blank=True, default=list)),
                ('onboarding_snapshot', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner_onboarding_progress',
            },
        ),
        migrations.AddField(
            model_name='partnermembership',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnermembership',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnermembership',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnermembership',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnermembership',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnermembership',
            name='timed_out_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='partnermembership',
            index=models.Index(fields=['partner', 'is_banned'], name='partner_mem_partner_d60c77_idx'),
        ),
        migrations.AddField(
            model_name='partneronboardingprogress',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_progress', to='partners.partnerinvite'),
        ),
        migrations.AddField(
            model_name='partneronboardingprogress',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='partneronboardingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_onboarding_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnermoderationaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_moderation_actions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnermoderationaction',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='partners.partnermembership'),
        ),
        migrations.AddField(
            model_name='partnermoderationaction',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='partnermoderationaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerinvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_invites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerinvite',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='partners.partner'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingprogress',
            index=models.Index(fields=['partner', 'user'], name='partner_onb_partner_43478f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partneronboardingprogress',
            unique_together={('partner', 'user')},
        ),
        migrations.AddIndex(
            model_name='partnermoderationaction',
            index=models.Index(fields=['partner', 'user', 'action_type'], name='partner_mod_partner_a6f5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='partnermoderationaction',
            index=models.Index(fields=['partner', 'created_at'], name='partner_mod_partner_a1d265_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinvite',
            index=models.Index(fields=['partner', 'is_active'], name='partner_inv_partner_055326_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinvite',
            index=models.Index(fields=['partner', 'code'], name='partner_inv_partner_b19fa3_idx'),
        ),
    ]
