# Generated by Django 4.2.25 on 2026-04-28 08:11

import apps.partners.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0038_partnerinvite_partnermoderationaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganizationAppContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('rich_text', 'Rich text'), ('video', 'Video'), ('image', 'Image'), ('link', 'Link'), ('file', 'File'), ('embed', 'Embed')], default='text', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner_organization_app_content_block',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOrganizationAppTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('visible_to', models.JSONField(blank=True, default=apps.partners.models.default_app_visibility)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner_organization_app_tab',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='partnerorganizationapp',
            name='is_promoted_global',
            field=models.BooleanField(db_index=True, default=False, help_text='Only KCAN/platform-controlled apps should be promoted into the main app navigation.'),
        ),
        migrations.AddField(
            model_name='partnerorganizationapp',
            name='promoted_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerorganizationapp',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganizationapp',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddIndex(
            model_name='partnerorganizationapp',
            index=models.Index(fields=['is_promoted_global', 'status'], name='partner_org_app_global_idx'),
        ),
        migrations.AddField(
            model_name='partnerorganizationapptab',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='partners.partnerorganizationapp'),
        ),
        migrations.AddField(
            model_name='partnerorganizationappcontentblock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_app_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerorganizationappcontentblock',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='partners.partnerorganizationapptab'),
        ),
        migrations.AddIndex(
            model_name='partnerorganizationapptab',
            index=models.Index(fields=['app', 'order'], name='partner_org_tab_app_order_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorganizationapptab',
            index=models.Index(fields=['app', 'is_active'], name='partner_org_tab_app_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerorganizationapptab',
            unique_together={('app', 'slug')},
        ),
        migrations.AddIndex(
            model_name='partnerorganizationappcontentblock',
            index=models.Index(fields=['tab', 'order'], name='partner_block_tab_order_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorganizationappcontentblock',
            index=models.Index(fields=['tab', 'status'], name='partner_block_tab_status_idx'),
        ),
    ]
