# Generated by Django 4.2.25 on 2026-05-25 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0039_partnerorganizationappcontentblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppShortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('shortcut_name', models.CharField(max_length=128)),
                ('icon', models.URLField(blank=True)),
                ('deep_link', models.CharField(max_length=512)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='partners.partnerorganizationapp')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='partners.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_shortcuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_app_shortcut',
                'indexes': [models.Index(fields=['user', 'partner'], name='user_app_sh_user_id_cbf7ae_idx'), models.Index(fields=['user', 'device_id'], name='user_app_sh_user_id_013605_idx')],
            },
        ),
    ]
