# Generated by Django 4.2.25 on 2026-08-19 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0041_job_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganizationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('shop', 'Shop'), ('health_institution', 'Health Institution'), ('education_institution', 'Education Institution'), ('broadcast_channel', 'Broadcast Channel')], max_length=32)),
                ('owner_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_organization_link',
                'indexes': [models.Index(fields=['partner'], name='partner_org_partner_2175d7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='partnerorganizationlink',
            constraint=models.UniqueConstraint(fields=('owner_type', 'owner_id'), name='partner_org_link_unique_owner'),
        ),
    ]
