# Generated by Django 4.2.25 on 2026-08-31 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0044_backfill_partner_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_department',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_location',
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['partner'], name='partner_loc_partner_800094_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerDepartmentMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='partners.partnerdepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_department_membership',
                'unique_together': {('department', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='partnerdepartment',
            index=models.Index(fields=['partner'], name='partner_dep_partner_ec4c4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerdepartment',
            unique_together={('partner', 'name')},
        ),
    ]
