# Generated by Django 4.2.25 on 2026-08-31 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0045_partnerdepartment_partnerlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDepartmentNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('general', 'General'), ('succession', 'Succession planning'), ('goals', 'Leadership goals'), ('onboarding', 'Onboarding path')], default='general', max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='partners.partnerdepartment')),
            ],
            options={
                'db_table': 'partner_department_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'category'], name='partner_dep_departm_4815ed_idx')],
            },
        ),
    ]
