# Generated by Django 4.2.25 on 2026-08-31 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_canonical_media_asset_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0046_partnerdepartmentnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('file', 'File'), ('article', 'Article')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_resources', to='media.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_resource',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'kind'], name='partner_res_partner_df76d2_idx'), models.Index(fields=['partner', 'category'], name='partner_res_partner_66bc09_idx')],
            },
        ),
    ]
