# Generated by Django 4.2.25 on 2026-08-31 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0047_partnerresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCalendarEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('virtual_url', models.URLField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('all_members', 'All members'), ('admins_only', 'Admins only')], default='all_members', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='partners.partnerdepartment')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_calendar_event',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCalendarRsvp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('declined', 'Declined')], default='going', max_length=16)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='partners.partnercalendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_calendar_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_calendar_rsvp',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='partnercalendarevent',
            index=models.Index(fields=['partner', 'start_at'], name='partner_cal_partner_5671c0_idx'),
        ),
    ]
