# Generated by Django 4.2.25 on 2026-09-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0048_partnercalendarevent_partnercalendarrsvp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpost',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerpost',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('scheduled', 'Scheduled')], default='published', max_length=16),
        ),
        migrations.AddIndex(
            model_name='partnerpost',
            index=models.Index(fields=['status', 'scheduled_for'], name='partner_pos_status_acf870_idx'),
        ),
    ]
