# Generated by Django 4.2.25 on 2026-09-01 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0049_partnerpost_scheduled_for_partnerpost_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='partners.partnerdepartment')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='partners.partner')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_support_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketReply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_internal_note', models.BooleanField(default=False, help_text='Visible to admins/assignees only, hidden from the requester.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_replies', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='partners.supportticket')),
            ],
            options={
                'db_table': 'partner_support_ticket_reply',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='partner_sup_ticket__a30ee2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['partner', 'status'], name='partner_sup_partner_9afeab_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['partner', 'assignee'], name='partner_sup_partner_4eaf42_idx'),
        ),
    ]
