# Generated by Django 4.2.25 on 2026-09-01 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0050_supportticket_supportticketreply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPostTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_post_template',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['partner'], name='partner_pos_partner_f099be_idx')],
            },
        ),
    ]
