# Generated by Django 4.2.25 on 2026-09-01 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0051_partnerposttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSurvey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSurveyResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='partners.partnersurvey')),
            ],
            options={
                'db_table': 'partner_survey_response',
                'unique_together': {('survey', 'respondent')},
            },
        ),
        migrations.CreateModel(
            name='PartnerSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('rating', 'Rating (1-5)'), ('text', 'Open text')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text="For single_choice/multiple_choice: [{'id': 'opt1', 'label': 'Yes'}, ...].")),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='partners.partnersurvey')),
            ],
            options={
                'db_table': 'partner_survey_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSurveyAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.JSONField(help_text="Shape depends on question_type: {'choice_id': 'opt1'} | {'choice_ids': ['opt1','opt2']} | {'value': 4} | {'text': '...'}.")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='partners.partnersurveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='partners.partnersurveyresponse')),
            ],
            options={
                'db_table': 'partner_survey_answer',
            },
        ),
        migrations.AddIndex(
            model_name='partnersurveyquestion',
            index=models.Index(fields=['survey', 'order'], name='partner_sur_survey__67d1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='partnersurveyanswer',
            index=models.Index(fields=['question'], name='partner_sur_questio_45b0ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnersurveyanswer',
            unique_together={('response', 'question')},
        ),
        migrations.AddIndex(
            model_name='partnersurvey',
            index=models.Index(fields=['partner', 'status'], name='partner_sur_partner_a9d649_idx'),
        ),
    ]
