# Generated by Django 4.2.25 on 2026-09-01 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0052_partnersurvey_partnersurveyresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBudget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='partners.partnerdepartment')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_budget',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBudgetExpense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='partners.partnerbudget')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_budget_expense',
                'ordering': ['-spent_at'],
                'indexes': [models.Index(fields=['budget', 'spent_at'], name='partner_bud_budget__87c73f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='partnerbudget',
            index=models.Index(fields=['partner', 'department'], name='partner_bud_partner_084766_idx'),
        ),
    ]
