# Generated by Django 4.2.25 on 2026-09-01 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0053_partnerbudget_partnerbudgetexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerVolunteerShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('slots_total', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_shifts', to='partners.partner')),
            ],
            options={
                'db_table': 'partner_volunteer_shift',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerVolunteerSignup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('signed_up', 'Signed up'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='signed_up', max_length=16)),
                ('signed_up_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='partners.partnervolunteershift')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_volunteer_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_volunteer_signup',
                'unique_together': {('shift', 'volunteer')},
            },
        ),
        migrations.AddIndex(
            model_name='partnervolunteershift',
            index=models.Index(fields=['partner', 'starts_at'], name='partner_vol_partner_f8ac7c_idx'),
        ),
    ]
