# Generated by Django 4.2.25 on 2026-09-01 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0054_partnervolunteershift_partnervolunteersignup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDonation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('mobile_money', 'Mobile money'), ('other', 'Other')], default='other', max_length=16)),
                ('fund', models.CharField(blank=True, help_text="e.g. 'General Fund', 'Missions', 'Building'.", max_length=120)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('receipt_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_donations_made', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='partners.partner')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_donation',
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['partner', 'received_at'], name='partner_don_partner_43a983_idx'), models.Index(fields=['partner', 'fund'], name='partner_don_partner_215245_idx')],
            },
        ),
    ]
