# Generated by Codex for Bible course system
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0002_seed_data"),
        ("partners", "0023_partner_org_profile_public_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.URLField(blank=True)),
                ("level", models.CharField(default="beginner", max_length=50)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("is_bible_course", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=True)),
                ("price_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("price_currency", models.CharField(default="USD", max_length=10)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="bible_courses", to="partners.partner"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BibleCourseModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="modules", to="bible.biblecourse"),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="BibleLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("duration_minutes", models.PositiveIntegerField(default=5)),
                ("video_url", models.URLField(blank=True)),
                ("audio_url", models.URLField(blank=True)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="bible.biblecourse"),
                ),
                (
                    "module",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lessons", to="bible.biblecoursemodule"),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="BibleCourseEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("active", "Active"), ("completed", "Completed"), ("paused", "Paused")], default="active", max_length=20)),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="bible.biblecourse"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bible_course_enrollments", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="BibleLessonProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed", models.BooleanField(default=False)),
                ("last_position_ms", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress", to="bible.biblelesson"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bible_lesson_progress", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
