# Generated by Django 4.2.25 on 2026-04-27 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0038_partnerinvite_partnermoderationaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bible', '0014_bible_preferences_public_prayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblePrayerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('language', models.CharField(default='en', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prayer_months', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_prayer_months', to='partners.partner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prayer_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('partner', 'year', 'month', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BibleMeditationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('message', 'Message'), ('video', 'Video')], default='message', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('scripture_refs', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meditation_posts', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_meditation_posts', to='partners.partner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meditation_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BibleReadingPlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_ref', models.CharField(max_length=160)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('reminder_offsets', models.JSONField(blank=True, default=list)),
                ('reminder_channels', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('source', models.CharField(default='reader', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapters', models.ManyToManyField(blank=True, related_name='planned_reading_events', to='bible.biblechapter')),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bible.bibletranslation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_reading_events', to=settings.AUTH_USER_MODEL)),
                ('verses', models.ManyToManyField(blank=True, related_name='planned_reading_events', to='bible.bibleverse')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['user', 'start_at'], name='bible_bible_user_id_68c6a4_idx'), models.Index(fields=['user', 'status'], name='bible_bible_user_id_5b547a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BiblePrayerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('prayer_points', models.JSONField(blank=True, default=list)),
                ('exhortation', models.TextField(blank=True)),
                ('scripture_refs', models.JSONField(blank=True, default=list)),
                ('prayer_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='bible.bibleprayermonth')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('prayer_month', 'day')},
            },
        ),
        migrations.CreateModel(
            name='BibleDailyPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('language', models.CharField(default='en', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('passage_ref', models.CharField(max_length=120)),
                ('scripture_refs', models.JSONField(blank=True, default=list)),
                ('exhortation', models.TextField(blank=True)),
                ('prayer_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_passages', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bible_passages', to='partners.partner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_daily_passages', to=settings.AUTH_USER_MODEL)),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_passages', to='bible.bibletranslation')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('partner', 'date', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BibleContentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_content_audit_logs', to='partners.partner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'created_at'], name='bible_bible_partner_a029bb_idx'), models.Index(fields=['target_type', 'target_id'], name='bible_bible_target__864c8b_idx')],
            },
        ),
    ]
