# Generated by Django 4.2.25 on 2026-04-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0015_bibleprayermonth_biblemeditationpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleTranslationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(max_length=20)),
                ('display_language', models.CharField(blank=True, max_length=80)),
                ('abbreviation', models.CharField(blank=True, max_length=40)),
                ('full_name', models.CharField(max_length=200)),
                ('source_path', models.CharField(max_length=500)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('copyright_status', models.CharField(choices=[('public_domain', 'Public domain'), ('licensed', 'Licensed'), ('restricted', 'Restricted'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('license_notes', models.TextField(blank=True)),
                ('rights_holder', models.CharField(blank=True, max_length=200)),
                ('is_licensed', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('import_enabled', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('book_count', models.PositiveIntegerField(default=0)),
                ('chapter_count', models.PositiveIntegerField(default=0)),
                ('verse_count', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata', to='bible.bibletranslation')),
            ],
            options={
                'ordering': ['language', 'full_name'],
                'indexes': [models.Index(fields=['language', 'is_public'], name='bible_bible_languag_5bc090_idx'), models.Index(fields=['copyright_status', 'is_licensed'], name='bible_bible_copyrig_aee04a_idx'), models.Index(fields=['validation_status'], name='bible_bible_validat_be0b81_idx')],
            },
        ),
    ]
