# Generated by Django 4.2.25 on 2026-04-28 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def mark_public_domain_reviews_not_required(apps, schema_editor):
    BibleTranslationMetadata = apps.get_model("bible", "BibleTranslationMetadata")
    BibleTranslationMetadata.objects.filter(copyright_status="public_domain").update(
        license_review_status="not_required"
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bible', '0016_bibletranslationmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibletranslationmetadata',
            name='license_review_status',
            field=models.CharField(choices=[('pending', 'Pending human review'), ('not_required', 'Not required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='bibletranslationmetadata',
            name='license_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibletranslationmetadata',
            name='license_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bible_translation_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(mark_public_domain_reviews_not_required, migrations.RunPython.noop),
    ]
