# Generated by Django 4.2.25 on 2026-08-31 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0047_partnerresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bible', '0018_kcanbook_kcanmessagetopic_kcanminister_kcanmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleCourseTrackProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='bible.biblecoursetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_track_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('track', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BibleCourseTrackAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_track_assignments', to='partners.partnerdepartment')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bible.biblecoursetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_track_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('track', 'user')},
            },
        ),
    ]
