# Generated by Django 4.2.25 on 2026-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0019_biblecoursetrackprogress_biblecoursetrackassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblecourseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
