# Generated by Django 4.2.25 on 2026-08-13 01:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_device_one_active_parent_constraint'),
        ('rewards', '0002_backfill_loyalty_points'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='qualifying_net_amount_cents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='qualifying_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.subscription'),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rewards.rewardledgerentry'),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_rate_percent_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('rewarded', 'Rewarded'), ('reversed', 'Reversed'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferralRateConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('tier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rate_config', to='accounts.accounttier')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
