# Generated by Django 4.2.25 on 2026-08-13 08:02

from django.db import migrations, models


def backfill_qualified_at(apps, schema_editor):
    """
    One-time best-effort backfill for QUALIFIED/REWARDED Referral rows that
    predate the qualified_at field (Phase 11 of the billing/rewards
    project). qualified_at was never tracked before, so updated_at (bumped
    by the same qualify_referral() save that set status=QUALIFIED) is the
    closest available proxy — accurate unless something else touched the
    row between qualification and now, which is the same caveat every
    other backfill in this project accepts. Referrals that never reached
    QUALIFIED (still PENDING/BLOCKED, or REVERSED before ever qualifying)
    correctly stay NULL.
    """
    Referral = apps.get_model("referrals", "Referral")
    updated = Referral.objects.filter(
        status__in=["qualified", "rewarded"], qualified_at__isnull=True,
    ).update(qualified_at=models.F("updated_at"))
    print(f"[0004_referral_qualified_at] backfilled qualified_at for {updated} referral row(s)")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_seed_referral_rate_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='qualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'qualified_at'], name='referrals_r_status_3f3a9f_idx'),
        ),
        migrations.RunPython(backfill_qualified_at, noop_reverse),
    ]
