from django.urls import path

from .views_internal import ProcessBroadcastVideoUploadView
from .views import (
    BroadcastFeedView,
    ChannelContentChaptersView,
    ChannelContentChapterDetailView,
    ChannelCommentReportView,
    ChannelClipShareView,
    BroadcastChannelListCreateView,
    BroadcastChannelDetailView,
    BroadcastChannelBroadcastView,
    BroadcastChannelAnalyticsView,
    BroadcastChannelModerationQueueView,
    BroadcastChannelReportView,
    BroadcastChannelSubscribeView,
    BroadcastChannelSubscriptionView,
    BroadcastChannelContentListCreateView,
    ChannelContentDetailView,
    ChannelContentPublishView,
    ChannelContentUnpublishView,
    ChannelContentBroadcastView,
    ChannelContentScheduleView,
    ChannelContentAssetUploadView,
    ChannelLiveStreamListCreateView,
    ChannelLiveStreamDetailView,
    ChannelLiveStreamStreamKeyView,
    ChannelLiveStreamStartView,
    ChannelLiveStreamEndView,
    ChannelLiveStreamWebhookView,
    ChannelContentEmbedPublicView,
    ChannelContentOEmbedView,
    ChannelContentEmbedTokenView,
    PublicChannelContentLandingView,
    PublicChannelLandingView,
    PublicRobotsPolicyView,
    PublicSitemapPlanView,
    ChannelContentReactView,
    ChannelContentSaveView,
    ChannelContentShareView,
    ChannelContentViewEventView,
    ChannelContentCommentsView,
    ChannelContentCommentModerationView,
    ChannelCommentReactView,
    ChannelCommentPinView,
    WatchHistoryView,
    WatchHistorySettingsView,
    ChannelContentClipView,
    ChannelContentClipDetailView,
    ChannelPublicClipsView,
    ChannelContentReportView,
    ChannelModerationActionView,
    BroadcastPlaylistItemView,
    BroadcastPlaylistItemDetailView,
    BroadcastPlaylistListCreateView,
    ChannelContentCommentEditView,
    ChannelContentCommentDeleteView,
    CommentCreatorHeartView,
    ChannelContentSubtitleListView,
    ChannelContentSubtitleDetailView,
    ChannelContentEndScreenView,
    ChannelContentCardsView,
    ChannelContentCardDetailView,
    ChannelActivityFeedView,
    ChannelSubscriberListView,
    ChannelContentRelatedView,
    ChannelLivePollListCreateView,
    ChannelLivePollVoteView,
    ChannelLivePollEndView,
    ChannelLiveQAView,
    ChannelLiveQAQuestionView,
    ChannelLiveQAQuestionActionView,
    ChannelLiveQAQuestionUpvoteView,
    BroadcastChannelMessageView,
    BroadcastReactView,
    BroadcastCommentRoomView,
    BroadcastShareView,
    BroadcastViewEventView,
    BroadcastSaveView,
    BroadcastHideView,
    BroadcastReportView,
    BroadcastFeatureListView,
    ChannelFeatureView,
    BroadcastVideoListView,
    BroadcastVideoUploadView,
    BroadcastVideoStreamView,
    BroadcastLessonListView,
    CreatorStudentListView,
    LessonEnrollmentActionView,
    LessonEnrollmentListView,
    ProfileCreationView,
    BroadcastFeedEntriesView,
    BroadcastFeedEntryDetailView,
    BroadcastFeedEntryBroadcastView,
    BroadcastFeedEntryAttachmentDeleteView,
    ProfileAttachmentUploadView,
    ProfileManagementView,
    BroadcastSubscribeView,
    EducationCourseBroadcastView,
    EducationHubView,
    EducationUploadInitiateView,
    EducationInstitutionListView,
    EducationInstitutionDetailView,
    ChannelPayoutAccountConnectView,
    ChannelStripeConnectAccountView,
    EducationInstitutionPartnerConnectView,
    EducationInstitutionPayoutAccountConnectView,
    EducationInstitutionStripeConnectAccountView,
    EducationInstitutionVerificationReviewView,
    EducationInstitutionVerificationStartView,
    EducationInstitutionVerificationStatusView,
    EducationInstitutionDashboardView,
    EducationInstitutionMembershipListView,
    EducationInstitutionMembershipActionView,
    EducationInstitutionStudentMembershipDetailView,
    EducationInstitutionStaffMembershipDetailView,
    EducationInstitutionStaffAssignmentListView,
    EducationInstitutionStaffAssignmentDetailView,
    EducationInstitutionEnrollmentListView,
    EducationInstitutionEnrollmentDetailView,
    EducationInstitutionEnrollmentActionView,
    EducationInstitutionBookingListView,
    EducationInstitutionBookingDetailView,
    EducationInstitutionBookingActionView,
    EducationInstitutionBookingSatisfactionView,
    EducationInstitutionProgramListView,
    EducationInstitutionProgramDetailView,
    EducationInstitutionCourseListView,
    EducationInstitutionCourseDetailView,
    EducationInstitutionCourseModuleListView,
    EducationInstitutionCourseModuleDetailView,
    EducationInstitutionCourseModuleItemListView,
    EducationInstitutionCourseModuleItemDetailView,
    EducationInstitutionLessonListView,
    EducationInstitutionLessonDetailView,
    EducationInstitutionClassSessionListView,
    EducationInstitutionClassSessionDetailView,
    EducationInstitutionMaterialListView,
    EducationInstitutionMaterialDetailView,
    EducationInstitutionEventListView,
    EducationInstitutionEventDetailView,
    EducationInstitutionBroadcastListView,
    EducationInstitutionBroadcastDetailView,
    EducationInstitutionBroadcastMembershipActionView,
    EducationInstitutionBroadcastEnrollmentListView,
    EducationInstitutionBroadcastBookingListView,
    EducationInstitutionBroadcastBookingPaymentView,
    EducationBroadcastCatalogView,
    EducationDiscoveryView,
    EducationContentDetailView,
    EducationContentQuestionsView,
    EducationContentReviewsView,
    EducationContentCertificateView,
    EducationContentCertificateShareView,
    EducationContentItemActionView,
    EducationProgressView,
    EducationContentEnrollmentView,
    EducationContentAccessRequestView,
    EducationCourseAccessRequestListView,
    EducationCourseAccessRequestActionView,
    EducationInstitutionCourseAccessRequestListView,
    EducationInstitutionAssessmentListView,
    EducationInstitutionAssessmentDetailView,
    EducationInstitutionAssessmentQuestionListView,
    EducationInstitutionAssessmentQuestionDetailView,
    EducationInstitutionAssessmentOptionListView,
    EducationInstitutionAssessmentOptionDetailView,
    EducationInstitutionAssessmentSubmissionListView,
    EducationInstitutionAssessmentSubmissionDetailView,
    EducationInstitutionAssessmentSubmissionActionView,
    EducationProfileListView,
    EducationProfileDetailView,
    EducationProfileBroadcastView,
    EducationProfilePermissionsView,
    HealthInstitutionCardsView,
    HealthMediumListView,
    HealthMediumDetailView,
    HealthServiceListView,
    HealthServiceDetailView,
    UserContentPlaylistListView,
    UserContentPlaylistDetailView,
    UserContentPlaylistItemListView,
    UserContentPlaylistItemDetailView,
    LiveStreamCameraListView,
    LiveStreamCameraDetailView,
    LiveStreamSwitchCameraView,
    LiveStreamViewerPingView,
    ChannelContentMyReactionsView,
    ChannelLiveStreamWhipView,
    ChannelLiveStreamChatHistoryView,
    BroadcastTrendingView,
    ChannelLiveStreamArchiveView,
    ChannelContentDownloadView,
    ChannelMembershipTierListView,
    ChannelMembershipView,
    TipCreatorView,
    ChannelContentTipView,
    ChannelLiveStreamTipView,
    ChannelLiveStreamTipListView,
    ChannelContentWatchEventView,
    ChannelContentWatchSegmentView,
    ChannelContentAudioTracksView,
    ChannelContentGeoRestrictionView,
    ChannelContentPremiereView,
    ChannelContentTranscriptView,
    ChannelContentTranscriptWebhookView,
    ChannelMonetizationSettingsView,
    ChannelPayoutRequestView,
    ChannelLiveStreamGuestsView,
    ChannelLiveStreamGuestActionView,
    ChannelContentRecommendationsView,
    ChannelRevenueAnalyticsView,
    ChannelContentAutoChaptersView,
    ChannelContentProductsView,
    ChannelContentProductDetailView,
    ChannelLiveStreamTargetsView,
    ChannelLiveStreamTargetDetailView,
    ChannelMembershipGiftView,
    ChannelMembershipGiftRedeemView,
    ChannelContentCopyrightClaimsView,
    ChannelContentCopyrightDisputeView,
    ChannelAudienceDemographicsView,
    ChannelAdCampaignView,
    ChannelAdSlotView,
    ChannelAdImpressionView,
    ChannelContentQueueView,
    ChannelContentQueueReorderView,
    BroadcastChannelVerifyView,
    BroadcastSearchView,
    ChannelCommentPinByContentView,
    ChannelTrailerFeaturedView,
    ChannelAnalyticsImpressionsCTRView,
    ChannelAnalyticsTrafficSourcesView,
    ChannelKeywordFiltersView,
    ChannelKeywordFilterDetailView,
    ChannelHomepageShelvesView,
    ChannelHomepageShelfDetailView,
    ChannelHomepageShelfItemsView,
    ChannelCategoryListView,
    ChannelCategoryBrowseView,
    ChannelContentFingerprintView,
    ChannelLiveStreamSettingsView,
)

app_name = "broadcasts"

urlpatterns = [
    path("broadcasts/", BroadcastFeedView.as_view(), name="broadcast-feed"),
    path("broadcasts/channels/", BroadcastChannelListCreateView.as_view(), name="broadcast-channel-list"),
    path("broadcasts/channels/<str:handle_or_id>/", BroadcastChannelDetailView.as_view(), name="broadcast-channel-detail"),
    path("broadcasts/channels/<uuid:channel_id>/subscribe/", BroadcastChannelSubscribeView.as_view(), name="broadcast-channel-subscribe"),
    path("broadcasts/channels/<uuid:channel_id>/subscription/", BroadcastChannelSubscriptionView.as_view(), name="broadcast-channel-subscription"),
    path("broadcasts/channels/<uuid:channel_id>/report/", BroadcastChannelReportView.as_view(), name="broadcast-channel-report"),
    path("broadcasts/channels/<uuid:channel_id>/moderation/", BroadcastChannelModerationQueueView.as_view(), name="broadcast-channel-moderation"),
    path("broadcasts/channels/<uuid:channel_id>/analytics/", BroadcastChannelAnalyticsView.as_view(), name="broadcast-channel-analytics"),
    path("broadcasts/channels/<uuid:channel_id>/broadcast/", BroadcastChannelBroadcastView.as_view(), name="broadcast-channel-broadcast"),
    path("broadcasts/channels/<uuid:channel_id>/contents/", BroadcastChannelContentListCreateView.as_view(), name="broadcast-channel-contents"),
    path("broadcasts/channels/<uuid:channel_id>/playlists/", BroadcastPlaylistListCreateView.as_view(), name="broadcast-channel-playlists"),
    path("broadcasts/channels/<uuid:channel_id>/live-streams/", ChannelLiveStreamListCreateView.as_view(), name="broadcast-channel-live-streams"),
    path("broadcasts/channels/<uuid:channel_id>/payout-account/connect/", ChannelPayoutAccountConnectView.as_view(), name="broadcast-channel-payout-account-connect"),
    path("broadcasts/channels/<uuid:channel_id>/stripe-account/connect/", ChannelStripeConnectAccountView.as_view(), name="broadcast-channel-stripe-account-connect"),
    path("broadcasts/channel-contents/my-reactions/", ChannelContentMyReactionsView.as_view(), name="broadcast-channel-content-my-reactions"),
    path("broadcasts/channel-contents/<uuid:content_id>/", ChannelContentDetailView.as_view(), name="broadcast-channel-content-detail"),
    path("broadcasts/channel-contents/<uuid:content_id>/publish/", ChannelContentPublishView.as_view(), name="broadcast-channel-content-publish"),
    path("broadcasts/channel-contents/<uuid:content_id>/unpublish/", ChannelContentUnpublishView.as_view(), name="broadcast-channel-content-unpublish"),
    path("broadcasts/channel-contents/<uuid:content_id>/broadcast/", ChannelContentBroadcastView.as_view(), name="broadcast-channel-content-broadcast"),
    path("broadcasts/channel-contents/<uuid:content_id>/schedule/", ChannelContentScheduleView.as_view(), name="broadcast-channel-content-schedule"),
    path("broadcasts/channel-contents/<uuid:content_id>/assets/", ChannelContentAssetUploadView.as_view(), name="broadcast-channel-content-assets"),
    path("broadcasts/channel-contents/<uuid:content_id>/embed-token/", ChannelContentEmbedTokenView.as_view(), name="broadcast-channel-content-embed-token"),
    path("broadcasts/channel-contents/<uuid:content_id>/react/", ChannelContentReactView.as_view(), name="broadcast-channel-content-react"),
    path("broadcasts/channel-contents/<uuid:content_id>/save/", ChannelContentSaveView.as_view(), name="broadcast-channel-content-save"),
    path("broadcasts/channel-contents/<uuid:content_id>/share/", ChannelContentShareView.as_view(), name="broadcast-channel-content-share"),
    path("broadcasts/channel-contents/<uuid:content_id>/view/", ChannelContentViewEventView.as_view(), name="broadcast-channel-content-view"),
    path("broadcasts/channel-contents/<uuid:content_id>/report/", ChannelContentReportView.as_view(), name="broadcast-channel-content-report"),
    path("broadcasts/channel-contents/<uuid:content_id>/comments/", ChannelContentCommentsView.as_view(), name="broadcast-channel-content-comments"),
    path("broadcasts/channel-comments/<uuid:comment_id>/moderate/", ChannelContentCommentModerationView.as_view(), name="broadcast-channel-comment-moderate"),
    path("broadcasts/channel-comments/<uuid:comment_id>/react/", ChannelCommentReactView.as_view(), name="broadcast-channel-comment-react"),
    path("broadcasts/channel-comments/<uuid:comment_id>/pin/", ChannelCommentPinView.as_view(), name="broadcast-channel-comment-pin"),
    path("broadcasts/channel-contents/<uuid:content_id>/clip/", ChannelContentClipView.as_view(), name="broadcast-channel-content-clip"),
    path("broadcasts/watch-history/", WatchHistoryView.as_view(), name="broadcast-watch-history"),
    path("broadcasts/channel-moderation/<uuid:record_id>/action/", ChannelModerationActionView.as_view(), name="broadcast-channel-moderation-action"),
    path("broadcasts/playlists/<uuid:playlist_id>/items/", BroadcastPlaylistItemView.as_view(), name="broadcast-channel-playlist-items"),
    path("broadcasts/playlists/<uuid:playlist_id>/items/<uuid:content_id>/", BroadcastPlaylistItemDetailView.as_view(), name="broadcast-channel-playlist-item-detail"),
    path("broadcasts/live-streams/<uuid:stream_id>/", ChannelLiveStreamDetailView.as_view(), name="broadcast-live-stream-detail"),
    path("broadcasts/live-streams/<uuid:stream_id>/stream-key/", ChannelLiveStreamStreamKeyView.as_view(), name="broadcast-live-stream-key"),
    path("broadcasts/live-streams/<uuid:stream_id>/start/", ChannelLiveStreamStartView.as_view(), name="broadcast-live-stream-start"),
    path("broadcasts/live-streams/<uuid:stream_id>/end/", ChannelLiveStreamEndView.as_view(), name="broadcast-live-stream-end"),
    path("broadcasts/live-streams/webhook/<str:provider>/", ChannelLiveStreamWebhookView.as_view(), name="broadcast-live-stream-webhook"),
    path("broadcasts/embed/contents/<uuid:content_id>/", ChannelContentEmbedPublicView.as_view(), name="broadcast-channel-content-embed-public"),
    path("broadcasts/embed/contents/<uuid:content_id>/oembed/", ChannelContentOEmbedView.as_view(), name="broadcast-channel-content-oembed"),
    path("broadcasts/public/channels/<str:handle>/", PublicChannelLandingView.as_view(), name="broadcast-public-channel-landing"),
    path("broadcasts/public/contents/<uuid:content_id>/", PublicChannelContentLandingView.as_view(), name="broadcast-public-content-landing"),
    path("broadcasts/public/robots.txt", PublicRobotsPolicyView.as_view(), name="broadcast-public-robots"),
    path("broadcasts/public/sitemap-plan/", PublicSitemapPlanView.as_view(), name="broadcast-public-sitemap-plan"),
    path("broadcasts/channel-messages/", BroadcastChannelMessageView.as_view(), name="broadcast-channel-messages"),
    path("broadcasts/<uuid:pk>/react/", BroadcastReactView.as_view(), name="broadcast-react"),
    path("broadcasts/<uuid:pk>/comment-room/", BroadcastCommentRoomView.as_view(), name="broadcast-comment-room"),
    path("broadcasts/<uuid:pk>/share/", BroadcastShareView.as_view(), name="broadcast-share"),
    path("broadcasts/<uuid:pk>/view/", BroadcastViewEventView.as_view(), name="broadcast-view"),
    path("broadcasts/<uuid:pk>/save/", BroadcastSaveView.as_view(), name="broadcast-save"),
    path("broadcasts/<uuid:pk>/hide/", BroadcastHideView.as_view(), name="broadcast-hide"),
    path("broadcasts/<uuid:pk>/report/", BroadcastReportView.as_view(), name="broadcast-report"),
    path("broadcasts/features/", BroadcastFeatureListView.as_view(), name="broadcast-features"),
    path(
        "broadcasts/channels/<uuid:channel_id>/features/",
        ChannelFeatureView.as_view(),
        name="channel-features",
    ),
    path("broadcasts/videos/", BroadcastVideoListView.as_view(), name="broadcast-videos"),
    path("broadcasts/videos/upload/", BroadcastVideoUploadView.as_view(), name="broadcast-video-upload"),
    path("broadcasts/upload/", BroadcastVideoUploadView.as_view(), name="broadcast-upload-legacy"),
    # Trusted-internal only (apps.chat.internal_auth) — Nest calls this after
    # confirming a direct-to-S3 video upload landed. See views_internal.py.
    path(
        "broadcasts/internal/process-video-upload/",
        ProcessBroadcastVideoUploadView.as_view(),
        name="broadcast-internal-process-video-upload",
    ),
    path("broadcasts/videos/<uuid:video_id>/stream/", BroadcastVideoStreamView.as_view(), name="video-stream"),
    path("broadcasts/lessons/", BroadcastLessonListView.as_view(), name="broadcast-lessons"),
    path(
        "broadcasts/lessons/enrollments/",
        LessonEnrollmentListView.as_view(),
        name="lesson-enrollments",
    ),
    path(
        "broadcasts/creator/students/",
        CreatorStudentListView.as_view(),
        name="creator-students",
    ),
    path(
        "broadcasts/lessons/<uuid:lesson_id>/enroll/",
        LessonEnrollmentActionView.as_view(),
        name="lesson-enroll",
    ),
    path(
        "broadcasts/profiles/create/",
        ProfileCreationView.as_view(),
        name="profile-create",
    ),
    path(
        "broadcasts/profiles/feeds/",
        BroadcastFeedEntriesView.as_view(),
        name="profile-feed-entries",
    ),
    path(
        "broadcasts/profiles/feeds/<uuid:entry_id>/",
        BroadcastFeedEntryDetailView.as_view(),
        name="profile-feed-entry",
    ),
    path(
        "broadcasts/profiles/feeds/<uuid:entry_id>/broadcast/",
        BroadcastFeedEntryBroadcastView.as_view(),
        name="profile-feed-entry-broadcast",
    ),
    path(
        "broadcasts/profiles/feeds/<uuid:entry_id>/unbroadcast/",
        BroadcastFeedEntryBroadcastView.as_view(),
        name="profile-feed-entry-unbroadcast",
    ),
    path(
        "broadcasts/profiles/feeds/<uuid:entry_id>/attachments/",
        BroadcastFeedEntryAttachmentDeleteView.as_view(),
        name="profile-feed-entry-attachment",
    ),
    path(
        "broadcasts/profiles/attachment/",
        ProfileAttachmentUploadView.as_view(),
        name="profile-attachment",
    ),
    path(
        "broadcasts/profiles/manage/",
        ProfileManagementView.as_view(),
        name="profile-manage",
    ),
    path(
        "broadcasts/subscribe/",
        BroadcastSubscribeView.as_view(),
        name="broadcast-subscribe",
    ),
    path(
        "broadcasts/education/courses/broadcast/",
        EducationCourseBroadcastView.as_view(),
        name="education-course-broadcast",
    ),
    path(
        "broadcasts/education/uploads/initiate/",
        EducationUploadInitiateView.as_view(),
        name="education-upload-initiate",
    ),
    path(
        "broadcasts/education/institutions/",
        EducationInstitutionListView.as_view(),
        name="education-institution-list",
    ),
    path(
        "broadcasts/education/hub/",
        EducationHubView.as_view(),
        name="education-hub",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/",
        EducationInstitutionDetailView.as_view(),
        name="education-institution-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/payout-account/connect/",
        EducationInstitutionPayoutAccountConnectView.as_view(),
        name="education-institution-payout-account-connect",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/stripe-account/connect/",
        EducationInstitutionStripeConnectAccountView.as_view(),
        name="education-institution-stripe-account-connect",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/partner/",
        EducationInstitutionPartnerConnectView.as_view(),
        name="education-institution-partner-connect",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/verification-status/",
        EducationInstitutionVerificationStatusView.as_view(),
        name="education-institution-verification-status",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/verification/start/",
        EducationInstitutionVerificationStartView.as_view(),
        name="education-institution-verification-start",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/verification/cases/<uuid:case_id>/review/",
        EducationInstitutionVerificationReviewView.as_view(),
        name="education-institution-verification-review",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/dashboard/",
        EducationInstitutionDashboardView.as_view(),
        name="education-institution-dashboard",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/memberships/",
        EducationInstitutionMembershipListView.as_view(),
        name="education-institution-memberships",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/enrollments/",
        EducationInstitutionEnrollmentListView.as_view(),
        name="education-institution-enrollments",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/course-access-requests/",
        EducationInstitutionCourseAccessRequestListView.as_view(),
        name="education-institution-course-access-requests",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/enrollments/<uuid:enrollment_id>/",
        EducationInstitutionEnrollmentDetailView.as_view(),
        name="education-institution-enrollment-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/enrollments/<uuid:enrollment_id>/action/",
        EducationInstitutionEnrollmentActionView.as_view(),
        name="education-institution-enrollment-action",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/bookings/",
        EducationInstitutionBookingListView.as_view(),
        name="education-institution-bookings",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/bookings/<uuid:booking_id>/",
        EducationInstitutionBookingDetailView.as_view(),
        name="education-institution-booking-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/bookings/<uuid:booking_id>/action/",
        EducationInstitutionBookingActionView.as_view(),
        name="education-institution-booking-action",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/bookings/<uuid:booking_id>/satisfy/",
        EducationInstitutionBookingSatisfactionView.as_view(),
        name="education-institution-booking-satisfaction",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/memberships/<uuid:membership_id>/action/",
        EducationInstitutionMembershipActionView.as_view(),
        name="education-institution-membership-action",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/memberships/<uuid:membership_id>/student-detail/",
        EducationInstitutionStudentMembershipDetailView.as_view(),
        name="education-institution-student-membership-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/memberships/<uuid:membership_id>/staff-detail/",
        EducationInstitutionStaffMembershipDetailView.as_view(),
        name="education-institution-staff-membership-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/staff-assignments/",
        EducationInstitutionStaffAssignmentListView.as_view(),
        name="education-institution-staff-assignment-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/staff-assignments/<uuid:assignment_id>/",
        EducationInstitutionStaffAssignmentDetailView.as_view(),
        name="education-institution-staff-assignment-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/programs/",
        EducationInstitutionProgramListView.as_view(),
        name="education-institution-program-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/programs/<uuid:program_id>/",
        EducationInstitutionProgramDetailView.as_view(),
        name="education-institution-program-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/courses/",
        EducationInstitutionCourseListView.as_view(),
        name="education-institution-course-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/courses/<uuid:course_id>/",
        EducationInstitutionCourseDetailView.as_view(),
        name="education-institution-course-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/courses/<uuid:course_id>/modules/",
        EducationInstitutionCourseModuleListView.as_view(),
        name="education-institution-course-module-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/courses/<uuid:course_id>/modules/<uuid:module_id>/",
        EducationInstitutionCourseModuleDetailView.as_view(),
        name="education-institution-course-module-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/courses/<uuid:course_id>/modules/<uuid:module_id>/items/",
        EducationInstitutionCourseModuleItemListView.as_view(),
        name="education-institution-course-module-item-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/courses/<uuid:course_id>/modules/<uuid:module_id>/items/<uuid:item_id>/",
        EducationInstitutionCourseModuleItemDetailView.as_view(),
        name="education-institution-course-module-item-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/lessons/",
        EducationInstitutionLessonListView.as_view(),
        name="education-institution-lesson-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/lessons/<uuid:lesson_id>/",
        EducationInstitutionLessonDetailView.as_view(),
        name="education-institution-lesson-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/class-sessions/",
        EducationInstitutionClassSessionListView.as_view(),
        name="education-institution-class-session-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/class-sessions/<uuid:session_id>/",
        EducationInstitutionClassSessionDetailView.as_view(),
        name="education-institution-class-session-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/materials/",
        EducationInstitutionMaterialListView.as_view(),
        name="education-institution-material-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/materials/<uuid:material_id>/",
        EducationInstitutionMaterialDetailView.as_view(),
        name="education-institution-material-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/events/",
        EducationInstitutionEventListView.as_view(),
        name="education-institution-event-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/events/<uuid:event_id>/",
        EducationInstitutionEventDetailView.as_view(),
        name="education-institution-event-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/broadcasts/",
        EducationInstitutionBroadcastListView.as_view(),
        name="education-institution-broadcast-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/broadcasts/<uuid:broadcast_id>/",
        EducationInstitutionBroadcastDetailView.as_view(),
        name="education-institution-broadcast-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/broadcasts/<uuid:broadcast_id>/membership/",
        EducationInstitutionBroadcastMembershipActionView.as_view(),
        name="education-institution-broadcast-membership-action",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/broadcasts/<uuid:broadcast_id>/enrollments/",
        EducationInstitutionBroadcastEnrollmentListView.as_view(),
        name="education-institution-broadcast-enrollment-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/broadcasts/<uuid:broadcast_id>/bookings/",
        EducationInstitutionBroadcastBookingListView.as_view(),
        name="education-institution-broadcast-booking-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/broadcasts/<uuid:broadcast_id>/bookings/<uuid:booking_id>/pay/",
        EducationInstitutionBroadcastBookingPaymentView.as_view(),
        name="education-institution-broadcast-booking-payment",
    ),
    path(
        "broadcasts/education/catalog/",
        EducationBroadcastCatalogView.as_view(),
        name="education-broadcast-catalog",
    ),
    path(
        "education/discovery/",
        EducationDiscoveryView.as_view(),
        name="education-discovery",
    ),
    path(
        "education/contents/<uuid:content_id>/",
        EducationContentDetailView.as_view(),
        name="education-content-detail",
    ),
    path(
        "education/contents/<uuid:content_id>/reviews/",
        EducationContentReviewsView.as_view(),
        name="education-content-reviews",
    ),
    path(
        "education/contents/<uuid:content_id>/questions/",
        EducationContentQuestionsView.as_view(),
        name="education-content-questions",
    ),
    path(
        "education/contents/<uuid:content_id>/certificate/",
        EducationContentCertificateView.as_view(),
        name="education-content-certificate",
    ),
    path(
        "education/certificates/share/<str:token>/",
        EducationContentCertificateShareView.as_view(),
        name="education-content-certificate-share",
    ),
    path(
        "education/progress/",
        EducationProgressView.as_view(),
        name="education-progress",
    ),
    path(
        "education/contents/<uuid:content_id>/items/<str:item_id>/action/",
        EducationContentItemActionView.as_view(),
        name="education-content-item-action",
    ),
    path(
        "education/contents/<uuid:content_id>/enroll/",
        EducationContentEnrollmentView.as_view(),
        name="education-content-enroll",
    ),
    path(
        "education/contents/<uuid:content_id>/access-request/",
        EducationContentAccessRequestView.as_view(),
        name="education-content-access-request",
    ),
    path(
        "broadcasts/education/courses/<uuid:course_id>/access-requests/",
        EducationCourseAccessRequestListView.as_view(),
        name="education-course-access-requests",
    ),
    path(
        "broadcasts/education/courses/<uuid:course_id>/access-requests/<uuid:request_id>/action/",
        EducationCourseAccessRequestActionView.as_view(),
        name="education-course-access-request-action",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/",
        EducationInstitutionAssessmentListView.as_view(),
        name="education-institution-assessment-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/",
        EducationInstitutionAssessmentDetailView.as_view(),
        name="education-institution-assessment-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/questions/",
        EducationInstitutionAssessmentQuestionListView.as_view(),
        name="education-institution-assessment-question-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/questions/<uuid:question_id>/",
        EducationInstitutionAssessmentQuestionDetailView.as_view(),
        name="education-institution-assessment-question-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/questions/<uuid:question_id>/options/",
        EducationInstitutionAssessmentOptionListView.as_view(),
        name="education-institution-assessment-option-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/questions/<uuid:question_id>/options/<uuid:option_id>/",
        EducationInstitutionAssessmentOptionDetailView.as_view(),
        name="education-institution-assessment-option-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/submissions/",
        EducationInstitutionAssessmentSubmissionListView.as_view(),
        name="education-institution-assessment-submission-list",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/submissions/<uuid:submission_id>/",
        EducationInstitutionAssessmentSubmissionDetailView.as_view(),
        name="education-institution-assessment-submission-detail",
    ),
    path(
        "broadcasts/education/institutions/<uuid:institution_id>/assessments/<uuid:assessment_id>/submissions/<uuid:submission_id>/action/",
        EducationInstitutionAssessmentSubmissionActionView.as_view(),
        name="education-institution-assessment-submission-action",
    ),
    path(
        "broadcasts/education/profiles/",
        EducationProfileListView.as_view(),
        name="education-profile-list",
    ),
    path(
        "broadcasts/education/profiles/<uuid:profile_id>/",
        EducationProfileDetailView.as_view(),
        name="education-profile-detail",
    ),
    path(
        "broadcasts/education/profiles/<uuid:profile_id>/broadcast/",
        EducationProfileBroadcastView.as_view(),
        name="education-profile-broadcast",
    ),
    path(
        "broadcasts/education/profiles/permissions/",
        EducationProfilePermissionsView.as_view(),
        name="education-profile-permissions",
    ),
    path(
        "broadcasts/health/cards/<str:institution_id>/",
        HealthInstitutionCardsView.as_view(),
        name="health-institution-cards",
    ),
    path(
        "broadcasts/health/mediums/",
        HealthMediumListView.as_view(),
        name="health-medium-list",
    ),
    path(
        "broadcasts/health/mediums/<uuid:medium_id>/",
        HealthMediumDetailView.as_view(),
        name="health-medium-detail",
    ),
    path(
        "broadcasts/health/services/",
        HealthServiceListView.as_view(),
        name="health-service-list",
    ),
    path(
        "broadcasts/health/services/<uuid:service_id>/",
        HealthServiceDetailView.as_view(),
        name="health-service-detail",
    ),
    path("broadcasts/channel-contents/<uuid:content_id>/chapters/", ChannelContentChaptersView.as_view(), name="broadcast-channel-content-chapters"),
    path("broadcasts/channel-contents/<uuid:content_id>/chapters/<uuid:chapter_id>/", ChannelContentChapterDetailView.as_view(), name="broadcast-channel-content-chapter-detail"),
    path("broadcasts/channel-comments/<uuid:comment_id>/report/", ChannelCommentReportView.as_view(), name="broadcast-channel-comment-report"),
    path("broadcasts/clips/<uuid:clip_id>/share/", ChannelClipShareView.as_view(), name="broadcast-clip-share"),
    # YouTube parity
    path("broadcasts/channel-comments/<uuid:comment_id>/edit/", ChannelContentCommentEditView.as_view(), name="broadcast-channel-comment-edit"),
    path("broadcasts/channel-comments/<uuid:comment_id>/delete/", ChannelContentCommentDeleteView.as_view(), name="broadcast-channel-comment-delete"),
    path("broadcasts/channel-comments/<uuid:comment_id>/heart/", CommentCreatorHeartView.as_view(), name="broadcast-channel-comment-heart"),
    path("broadcasts/channel-contents/<uuid:content_id>/subtitles/", ChannelContentSubtitleListView.as_view(), name="broadcast-channel-content-subtitles"),
    path("broadcasts/channel-contents/<uuid:content_id>/subtitles/<uuid:subtitle_id>/", ChannelContentSubtitleDetailView.as_view(), name="broadcast-channel-content-subtitle-detail"),
    path("broadcasts/channel-contents/<uuid:content_id>/end-screen/", ChannelContentEndScreenView.as_view(), name="broadcast-channel-content-end-screen"),
    path("broadcasts/channel-contents/<uuid:content_id>/cards/", ChannelContentCardsView.as_view(), name="broadcast-channel-content-cards"),
    path("broadcasts/channel-contents/<uuid:content_id>/cards/<uuid:card_id>/", ChannelContentCardDetailView.as_view(), name="broadcast-channel-content-card-detail"),
    path("broadcasts/channel-contents/<uuid:content_id>/related/", ChannelContentRelatedView.as_view(), name="broadcast-channel-content-related"),
    path("broadcasts/channel-contents/<uuid:content_id>/clips/public/", ChannelPublicClipsView.as_view(), name="broadcast-channel-content-clips-public"),
    path("broadcasts/channel-contents/<uuid:content_id>/clips/<uuid:clip_id>/", ChannelContentClipDetailView.as_view(), name="broadcast-channel-content-clip-detail"),
    path("broadcasts/channels/<uuid:channel_id>/activity/", ChannelActivityFeedView.as_view(), name="broadcast-channel-activity"),
    path("broadcasts/channels/<uuid:channel_id>/subscribers/", ChannelSubscriberListView.as_view(), name="broadcast-channel-subscribers"),
    path("broadcasts/live-streams/<uuid:stream_id>/polls/", ChannelLivePollListCreateView.as_view(), name="broadcast-live-stream-polls"),
    path("broadcasts/polls/<uuid:poll_id>/vote/", ChannelLivePollVoteView.as_view(), name="broadcast-poll-vote"),
    path("broadcasts/polls/<uuid:poll_id>/end/", ChannelLivePollEndView.as_view(), name="broadcast-poll-end"),
    path("broadcasts/live-streams/<uuid:stream_id>/qa/", ChannelLiveQAView.as_view(), name="broadcast-live-stream-qa"),
    path("broadcasts/qa/<uuid:session_id>/questions/", ChannelLiveQAQuestionView.as_view(), name="broadcast-qa-questions"),
    path("broadcasts/qa-questions/<uuid:question_id>/", ChannelLiveQAQuestionActionView.as_view(), name="broadcast-qa-question-action"),
    path("broadcasts/qa-questions/<uuid:question_id>/upvote/", ChannelLiveQAQuestionUpvoteView.as_view(), name="broadcast-qa-question-upvote"),
    path("broadcasts/watch-history/settings/", WatchHistorySettingsView.as_view(), name="broadcast-watch-history-settings"),
    # User content playlists (cross-device, server-persisted)
    path("broadcasts/user-playlists/", UserContentPlaylistListView.as_view(), name="broadcast-user-playlists"),
    path("broadcasts/user-playlists/<uuid:playlist_id>/", UserContentPlaylistDetailView.as_view(), name="broadcast-user-playlist-detail"),
    path("broadcasts/user-playlists/<uuid:playlist_id>/items/", UserContentPlaylistItemListView.as_view(), name="broadcast-user-playlist-items"),
    path("broadcasts/user-playlists/<uuid:playlist_id>/items/<int:item_id>/", UserContentPlaylistItemDetailView.as_view(), name="broadcast-user-playlist-item-detail"),
    # Live stream cameras
    path("broadcasts/live-streams/<uuid:stream_id>/cameras/", LiveStreamCameraListView.as_view(), name="broadcast-live-stream-cameras"),
    path("broadcasts/live-streams/<uuid:stream_id>/cameras/<uuid:camera_id>/", LiveStreamCameraDetailView.as_view(), name="broadcast-live-stream-camera-detail"),
    path("broadcasts/live-streams/<uuid:stream_id>/switch-camera/", LiveStreamSwitchCameraView.as_view(), name="broadcast-live-stream-switch-camera"),
    # Live stream viewer count (REST fallback + ping)
    path("broadcasts/live-streams/<uuid:stream_id>/viewer-ping/", LiveStreamViewerPingView.as_view(), name="broadcast-live-stream-viewer-ping"),
    # Task 1b: notification preference alias
    path(
        "broadcasts/channels/<uuid:channel_id>/notification-preference/",
        BroadcastChannelSubscriptionView.as_view(),
        name="broadcast-channel-notification-preference",
    ),
    # Task 1c: WHIP proxy
    path("broadcasts/live-streams/<uuid:stream_id>/whip/", ChannelLiveStreamWhipView.as_view(), name="broadcast-live-stream-whip"),
    # Task 1d: live chat history
    path("broadcasts/live-streams/<uuid:stream_id>/chat/", ChannelLiveStreamChatHistoryView.as_view(), name="broadcast-live-stream-chat"),
    # Task 2b: trending
    path("broadcasts/trending/", BroadcastTrendingView.as_view(), name="broadcast-trending"),
    # Task 3b: DVR archive webhook
    path("broadcasts/live-streams/<uuid:stream_id>/archive/", ChannelLiveStreamArchiveView.as_view(), name="broadcast-live-stream-archive"),
    # Task 4: content download
    path("broadcasts/channel-contents/<uuid:content_id>/download/", ChannelContentDownloadView.as_view(), name="broadcast-channel-content-download"),
    # Task 5: channel membership tiers and membership
    path("broadcasts/channels/<uuid:channel_id>/membership-tiers/", ChannelMembershipTierListView.as_view(), name="broadcast-channel-membership-tiers"),
    path("broadcasts/channels/<uuid:channel_id>/membership/", ChannelMembershipView.as_view(), name="broadcast-channel-membership"),
    path("broadcast-items/<str:content_id>/tip/", TipCreatorView.as_view(), name="tip-creator"),
    # Super Thanks / Super Chat tips
    path("broadcasts/channel-contents/<uuid:content_id>/tips/", ChannelContentTipView.as_view(), name="broadcast-channel-content-tips"),
    path("broadcasts/live-streams/<uuid:stream_id>/tips/", ChannelLiveStreamTipListView.as_view(), name="broadcast-live-stream-tips"),
    path("broadcasts/live-streams/<uuid:stream_id>/tip/", ChannelLiveStreamTipView.as_view(), name="broadcast-live-stream-tip"),
    # Watch heatmap + recommendation signals
    path("broadcasts/channel-contents/<uuid:content_id>/watch-segments/", ChannelContentWatchSegmentView.as_view(), name="broadcast-channel-content-watch-segments"),
    path("broadcasts/channel-contents/<uuid:content_id>/watch-event/", ChannelContentWatchEventView.as_view(), name="broadcast-channel-content-watch-event"),
    # Audio tracks
    path("broadcasts/channel-contents/<uuid:content_id>/audio-tracks/", ChannelContentAudioTracksView.as_view(), name="broadcast-channel-content-audio-tracks"),
    # Geo-restriction
    path("broadcasts/channel-contents/<uuid:content_id>/geo-restriction/", ChannelContentGeoRestrictionView.as_view(), name="broadcast-channel-content-geo-restriction"),
    # Premiere
    path("broadcasts/channel-contents/<uuid:content_id>/premiere/", ChannelContentPremiereView.as_view(), name="broadcast-channel-content-premiere"),
    # Transcript / auto-captions
    path("broadcasts/channel-contents/<uuid:content_id>/transcript/", ChannelContentTranscriptView.as_view(), name="broadcast-channel-content-transcript"),
    path("broadcasts/transcripts/webhook/", ChannelContentTranscriptWebhookView.as_view(), name="broadcast-transcript-webhook"),
    # Monetization + payouts
    path("broadcasts/channels/<uuid:channel_id>/monetization/", ChannelMonetizationSettingsView.as_view(), name="broadcast-channel-monetization"),
    path("broadcasts/channels/<uuid:channel_id>/payout-requests/", ChannelPayoutRequestView.as_view(), name="broadcast-channel-payout-requests"),
    # Co-streaming guests
    path("broadcasts/live-streams/<uuid:stream_id>/guests/", ChannelLiveStreamGuestsView.as_view(), name="broadcast-live-stream-guests"),
    path("broadcasts/live-streams/<uuid:stream_id>/guests/<uuid:guest_id>/", ChannelLiveStreamGuestActionView.as_view(), name="broadcast-live-stream-guest-action"),
    # Recommendations
    path("broadcasts/recommendations/", ChannelContentRecommendationsView.as_view(), name="broadcast-recommendations"),
    # Revenue analytics
    path("broadcasts/channels/<uuid:channel_id>/revenue/", ChannelRevenueAnalyticsView.as_view(), name="broadcast-channel-revenue"),
    # Auto-chapters
    path("broadcasts/channel-contents/<uuid:content_id>/auto-chapters/", ChannelContentAutoChaptersView.as_view(), name="broadcast-channel-content-auto-chapters"),
    # Product tagging
    path("broadcasts/channel-contents/<uuid:content_id>/products/", ChannelContentProductsView.as_view(), name="broadcast-channel-content-products"),
    path("broadcasts/channel-contents/<uuid:content_id>/products/<uuid:tag_id>/", ChannelContentProductDetailView.as_view(), name="broadcast-channel-content-product-detail"),
    # SimulCast
    path("broadcasts/live-streams/<uuid:stream_id>/simulcast/", ChannelLiveStreamTargetsView.as_view(), name="broadcast-live-stream-simulcast"),
    path("broadcasts/live-streams/<uuid:stream_id>/simulcast/<uuid:target_id>/", ChannelLiveStreamTargetDetailView.as_view(), name="broadcast-live-stream-simulcast-detail"),
    # Gift memberships
    path("broadcasts/memberships/gift/", ChannelMembershipGiftView.as_view(), name="broadcast-membership-gift"),
    path("broadcasts/memberships/gift/<str:token>/redeem/", ChannelMembershipGiftRedeemView.as_view(), name="broadcast-membership-gift-redeem"),
    # Copyright claims
    path("broadcasts/channels/<uuid:channel_id>/copyright-claims/", ChannelContentCopyrightClaimsView.as_view(), name="broadcast-channel-copyright-claims"),
    path("broadcasts/copyright-claims/<uuid:claim_id>/dispute/", ChannelContentCopyrightDisputeView.as_view(), name="broadcast-copyright-claim-dispute"),
    # Audience demographics
    path("broadcasts/channels/<uuid:channel_id>/demographics/", ChannelAudienceDemographicsView.as_view(), name="broadcast-channel-demographics"),
    # Ad campaigns + slots + impressions
    path("broadcasts/channels/<uuid:channel_id>/ad-campaigns/", ChannelAdCampaignView.as_view(), name="broadcast-channel-ad-campaigns"),
    path("broadcasts/channel-contents/<uuid:content_id>/ad-slots/", ChannelAdSlotView.as_view(), name="broadcast-channel-content-ad-slots"),
    path("broadcasts/ad-slots/<uuid:slot_id>/impression/", ChannelAdImpressionView.as_view(), name="broadcast-ad-slot-impression"),
    # Watch queue
    path("broadcasts/queue/", ChannelContentQueueView.as_view(), name="broadcast-queue"),
    path("broadcasts/queue/reorder/", ChannelContentQueueReorderView.as_view(), name="broadcast-queue-reorder"),
    # Verified channel (admin)
    path("broadcasts/channels/<uuid:channel_id>/verify/", BroadcastChannelVerifyView.as_view(), name="broadcast-channel-verify"),
    # Search
    path("broadcasts/search/", BroadcastSearchView.as_view(), name="broadcast-search"),
    # Comment pin (content-scoped)
    path("broadcasts/channel-contents/<uuid:content_id>/comments/<uuid:comment_id>/pin/", ChannelCommentPinByContentView.as_view(), name="broadcast-comment-pin"),
    # Channel trailer / featured
    path("broadcasts/channels/<uuid:channel_id>/trailer-featured/", ChannelTrailerFeaturedView.as_view(), name="broadcast-channel-trailer-featured"),
    # Analytics: impressions + CTR
    path("broadcasts/channels/<uuid:channel_id>/analytics/impressions/", ChannelAnalyticsImpressionsCTRView.as_view(), name="broadcast-channel-analytics-impressions"),
    # Analytics: traffic sources
    path("broadcasts/channels/<uuid:channel_id>/analytics/traffic-sources/", ChannelAnalyticsTrafficSourcesView.as_view(), name="broadcast-channel-analytics-traffic-sources"),
    # Keyword filters
    path("broadcasts/channels/<uuid:channel_id>/keyword-filters/", ChannelKeywordFiltersView.as_view(), name="broadcast-channel-keyword-filters"),
    path("broadcasts/keyword-filters/<uuid:filter_id>/", ChannelKeywordFilterDetailView.as_view(), name="broadcast-keyword-filter-detail"),
    # Homepage shelves
    path("broadcasts/channels/<uuid:channel_id>/shelves/", ChannelHomepageShelvesView.as_view(), name="broadcast-channel-shelves"),
    path("broadcasts/shelves/<uuid:shelf_id>/", ChannelHomepageShelfDetailView.as_view(), name="broadcast-shelf-detail"),
    path("broadcasts/shelves/<uuid:shelf_id>/items/", ChannelHomepageShelfItemsView.as_view(), name="broadcast-shelf-items"),
    # Categories
    path("broadcasts/categories/", ChannelCategoryListView.as_view(), name="broadcast-categories"),
    path("broadcasts/categories/<slug:slug>/browse/", ChannelCategoryBrowseView.as_view(), name="broadcast-category-browse"),
    # Content fingerprint
    path("broadcasts/channel-contents/<uuid:content_id>/fingerprint/", ChannelContentFingerprintView.as_view(), name="broadcast-content-fingerprint"),
    # Live stream settings (latency/DVR)
    path("broadcasts/live-streams/<uuid:stream_id>/settings/", ChannelLiveStreamSettingsView.as_view(), name="broadcast-live-stream-settings"),
]
