# Generated by Django 4.2.25 on 2025-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_alter_user_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_usernam_c0ea66_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='accounts_us_name_f6626a_idx'),
        ),
    ]
