# Generated by Django 4.2.25 on 2026-01-03 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_e2ee_keys'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='device',
            new_name='accounts_de_user_id_180a57_idx',
            old_name='accounts_de_user_id_1c2e42_idx',
        ),
        migrations.RenameIndex(
            model_name='e2edevicekey',
            new_name='accounts_e2_user_id_159f32_idx',
            old_name='accounts_e2_user_id_39c74a_idx',
        ),
        migrations.RenameIndex(
            model_name='e2edevicekey',
            new_name='accounts_e2_user_id_d2b5bd_idx',
            old_name='accounts_e2_user_id_6b4b7b_idx',
        ),
        migrations.RenameIndex(
            model_name='e2eprekey',
            new_name='accounts_e2_user_id_c70ec6_idx',
            old_name='accounts_e2_user_id_2d3b11_idx',
        ),
        migrations.RenameIndex(
            model_name='e2eprekey',
            new_name='accounts_e2_user_id_de77f7_idx',
            old_name='accounts_e2_user_id_0f6d54_idx',
        ),
        migrations.RemoveField(
            model_name='e2edevicekey',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='e2eprekey',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='e2edevicekey',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='e2edevicekey',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='e2eprekey',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='e2eprekey',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
