# Generated by Django 4.2.25 on 2026-01-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_privacy_articles_tiers'),
        ('accounts', '0011_rename_accounts_de_user_id_1c2e42_idx_accounts_de_user_id_180a57_idx_and_more'),
    ]

    operations = [
    ]
