# Generated by Django 4.2.25 on 2026-01-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_media_fields'),
        ('accounts', '0012_merge_20260106_0957'),
    ]

    operations = [
    ]
