# Generated by Django 4.2.25 on 2026-01-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_showcase_preferences'),
        ('accounts', '0013_merge_20260106_1056'),
    ]

    operations = [
    ]
