# Generated by Django 4.2.25 on 2026-01-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20260106_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilearticle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profilefieldvisibility',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profilepreferences',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profileshowcase',
            options={},
        ),
        migrations.RenameIndex(
            model_name='profilearticle',
            new_name='accounts_pr_user_id_f422f5_idx',
            old_name='accounts_pr_user_id_3bba6c_idx',
        ),
        migrations.RenameIndex(
            model_name='profilearticle',
            new_name='accounts_pr_visibil_1829c0_idx',
            old_name='accounts_pr_visibility_72d9ea_idx',
        ),
        migrations.RenameIndex(
            model_name='profilefieldvisibility',
            new_name='accounts_pr_user_id_0407d7_idx',
            old_name='accounts_pr_user_id_8af7b3_idx',
        ),
        migrations.RenameIndex(
            model_name='profilepreferences',
            new_name='accounts_pr_user_id_36ef02_idx',
            old_name='accounts_pr_user_id_68a8de_idx',
        ),
        migrations.RenameIndex(
            model_name='profileshowcase',
            new_name='accounts_pr_user_id_d09308_idx',
            old_name='accounts_pr_user_id_7e1f7a_idx',
        ),
        migrations.RenameIndex(
            model_name='profileshowcase',
            new_name='accounts_pr_type_56bfd0_idx',
            old_name='accounts_pr_type_68f6f1_idx',
        ),
    ]
