# Generated by Django 4.2.25 on 2026-01-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subscription_lifecycle_fields'),
        ('accounts', '0015_alter_profilearticle_options_and_more'),
    ]

    operations = [
    ]
