# Generated by Codex on 2026-03-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_tier_system_rollout"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("contact_phone", models.CharField(db_index=True, max_length=50)),
                ("contact_phone_number", models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ("contact_country_code", models.CharField(blank=True, max_length=12, null=True)),
                ("contact_display_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "contact_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts_incoming",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts_outgoing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "contact_phone")},
            },
        ),
        migrations.CreateModel(
            name="ProfileFieldVisibilityAllowTarget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("target_phone", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("target_phone_number", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allow_targets",
                        to="accounts.profilefieldvisibility",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_visibility_allow_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ProfileArticleAllowTarget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("target_phone", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("target_phone_number", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allow_targets",
                        to="accounts.profilearticle",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_article_allow_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="profilefieldvisibility",
            name="allow_user_ids",
        ),
        migrations.RemoveField(
            model_name="profilearticle",
            name="allow_user_ids",
        ),
        migrations.AddIndex(
            model_name="usercontact",
            index=models.Index(fields=["user", "contact_user"], name="accounts_us_user_id_5f5cc9_idx"),
        ),
        migrations.AddIndex(
            model_name="usercontact",
            index=models.Index(fields=["user", "contact_phone"], name="accounts_us_user_id_4a4507_idx"),
        ),
        migrations.AddIndex(
            model_name="usercontact",
            index=models.Index(fields=["user", "contact_phone_number"], name="accounts_us_user_id_27f450_idx"),
        ),
        migrations.AddIndex(
            model_name="profilefieldvisibilityallowtarget",
            index=models.Index(fields=["rule", "target_user"], name="accounts_pr_rule_id_3b89f4_idx"),
        ),
        migrations.AddIndex(
            model_name="profilefieldvisibilityallowtarget",
            index=models.Index(fields=["rule", "target_phone"], name="accounts_pr_rule_id_42a474_idx"),
        ),
        migrations.AddIndex(
            model_name="profilefieldvisibilityallowtarget",
            index=models.Index(fields=["rule", "target_phone_number"], name="accounts_pr_rule_id_818027_idx"),
        ),
        migrations.AddIndex(
            model_name="profilearticleallowtarget",
            index=models.Index(fields=["article", "target_user"], name="accounts_pr_article__3c0d43_idx"),
        ),
        migrations.AddIndex(
            model_name="profilearticleallowtarget",
            index=models.Index(fields=["article", "target_phone"], name="accounts_pr_article__f40d8f_idx"),
        ),
        migrations.AddIndex(
            model_name="profilearticleallowtarget",
            index=models.Index(fields=["article", "target_phone_number"], name="accounts_pr_article__241f72_idx"),
        ),
    ]
