# Generated by Django 4.2.25 on 2026-03-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_relational_privacy_and_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilearticleallowtarget',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profilefieldvisibilityallowtarget',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usercontact',
            options={},
        ),
        migrations.RenameIndex(
            model_name='profilearticleallowtarget',
            new_name='accounts_pr_article_80dd94_idx',
            old_name='accounts_pr_article__3c0d43_idx',
        ),
        migrations.RenameIndex(
            model_name='profilearticleallowtarget',
            new_name='accounts_pr_article_d47327_idx',
            old_name='accounts_pr_article__f40d8f_idx',
        ),
        migrations.RenameIndex(
            model_name='profilearticleallowtarget',
            new_name='accounts_pr_article_81c255_idx',
            old_name='accounts_pr_article__241f72_idx',
        ),
        migrations.RenameIndex(
            model_name='profilefieldvisibilityallowtarget',
            new_name='accounts_pr_rule_id_e5fc50_idx',
            old_name='accounts_pr_rule_id_3b89f4_idx',
        ),
        migrations.RenameIndex(
            model_name='profilefieldvisibilityallowtarget',
            new_name='accounts_pr_rule_id_cc435f_idx',
            old_name='accounts_pr_rule_id_42a474_idx',
        ),
        migrations.RenameIndex(
            model_name='profilefieldvisibilityallowtarget',
            new_name='accounts_pr_rule_id_d1ca45_idx',
            old_name='accounts_pr_rule_id_818027_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontact',
            new_name='accounts_us_user_id_b1fa1e_idx',
            old_name='accounts_us_user_id_5f5cc9_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontact',
            new_name='accounts_us_user_id_5076b4_idx',
            old_name='accounts_us_user_id_4a4507_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontact',
            new_name='accounts_us_user_id_e2e2dd_idx',
            old_name='accounts_us_user_id_27f450_idx',
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='contact_country_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
