# Generated by Django 4.2.25 on 2026-04-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_profilearticleallowtarget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='revoke_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='revoked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'revoked_at'], name='accounts_de_user_id_34db7f_idx'),
        ),
    ]
