# Generated by Django 4.2.25 on 2026-05-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_device_revoke_reason_device_revoked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(db_index=True, default='Free', max_length=50),
        ),
        # Backfill any rows that still carry the old 'Basic' label.
        # Migration 0024 handles the AccountTier rename; this covers the
        # denormalised user.tier field for users created before that ran.
        migrations.RunSQL(
            sql="UPDATE accounts_user SET tier = 'Free' WHERE LOWER(tier) = 'basic';",
            reverse_sql="UPDATE accounts_user SET tier = 'Basic' WHERE LOWER(tier) = 'free';",
        ),
    ]
