# Generated by Django 4.2.25 on 2026-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_e2ee_key_uniqueness'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userconnection',
            new_name='accounts_us_to_user_74a598_idx',
            old_name='accounts_uc_to_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userconnection',
            new_name='accounts_us_from_us_e52492_idx',
            old_name='accounts_uc_from_user_status_idx',
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
