# Generated by Django 4.2.25 on 2026-06-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_accounts_uc_to_user_status_idx_accounts_us_to_user_74a598_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepreferences',
            name='consent_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profilepreferences',
            name='language_preference',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profilepreferences',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
