# Generated by Django 4.2.25 on 2026-08-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_profilepreferences_quicklock_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttier',
            name='billing_period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='accounttier',
            name='rank',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
