# Generated by Django 4.2.25 on 2026-08-07 05:32
#
# Hand-edited after generation to insert a data-cleanup RunPython step
# between the schema changes and the new uniqueness constraint — see
# _consolidate_status_values below. Without it, the AddConstraint at the
# end could fail outright against a production database that (since
# `status` previously had no choices= constraint at all) might contain
# duplicate active rows or the old "ended" spelling.

from django.db import migrations, models


def _consolidate_status_values(apps, schema_editor):
    Subscription = apps.get_model("accounts", "Subscription")

    # "ended" (written by the old _finalize_pending_downgrade) is the same
    # concept as the new canonical "expired" — rename in place, no rows lost.
    Subscription.objects.filter(status="ended").update(status="expired")

    # Defensive dedupe for the uniqueness constraint about to be added:
    # every code path already supersedes the prior active row before
    # creating a new one, so this is expected to be a no-op in practice —
    # but a previously-unconstrained `status` column means we can't prove
    # that for data this migration didn't create. Keep the most recently
    # started active subscription per user; supersede the rest.
    from django.db.models import Count

    duplicate_user_ids = (
        Subscription.objects.filter(status="active")
        .values("user_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .values_list("user_id", flat=True)
    )
    for user_id in duplicate_user_ids:
        active_subs = list(
            Subscription.objects.filter(user_id=user_id, status="active").order_by("-started_at")
        )
        for stale in active_subs[1:]:
            stale.status = "superseded"
            stale.save(update_fields=["status"])


def _noop_reverse(apps, schema_editor):
    # Reversing the rename would require guessing which "expired" rows were
    # originally "ended" vs. already "expired" — not reconstructible,
    # intentionally a no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_backfill_tier_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='next_retry_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='retry_count',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('refunded', 'Refunded')], default='active', max_length=50),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'ends_at'], name='accounts_su_status_22487b_idx'),
        ),
        migrations.RunPython(_consolidate_status_values, _noop_reverse),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_subscription_per_user'),
        ),
    ]
