# Generated by Django 4.2.25 on 2026-08-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_subscription_status_state_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepreferences',
            name='lock_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
