# Generated by Django 4.2.25 on 2026-08-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_cleanup_device_duplicates_and_multi_parent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='accounts_device_user_device_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('is_parent', True), ('revoked_at__isnull', True)), fields=('user',), name='accounts_device_one_active_parent_per_user'),
        ),
    ]
