# Generated by Django 4.2.25 on 2026-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_device_one_active_parent_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceqrtoken',
            name='purpose',
            field=models.CharField(choices=[('phone_link', 'Phone link'), ('web_login', 'Web login')], default='phone_link', max_length=20),
        ),
    ]
