# Generated by Django 4.2.25 on 2026-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_feedengagementstate_dailyfeedusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
