# Generated by Django 4.2.25 on 2026-02-12 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_control', '0003_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_control_%(class)s_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminroleassignment',
            name='granted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adminuseractivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_control_%(class)s_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
