# Generated by Django 4.2.25 on 2026-01-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditaccount',
            new_name='billing_cre_user_id_70b1bb_idx',
            old_name='billing_ca_user_9ee7d2_idx',
        ),
        migrations.RenameIndex(
            model_name='promocode',
            new_name='billing_pro_code_a66cba_idx',
            old_name='billing_pc_code_7b1d1b_idx',
        ),
        migrations.RenameIndex(
            model_name='walletaccount',
            new_name='billing_wal_user_id_160ff2_idx',
            old_name='billing_wa_user_s_ae1d0d_idx',
        ),
        migrations.RenameIndex(
            model_name='walletledgerentry',
            new_name='billing_wal_user_id_a9ec7b_idx',
            old_name='billing_wl_user_k_2733b2_idx',
        ),
        migrations.RenameIndex(
            model_name='walletledgerentry',
            new_name='billing_wal_created_85a652_idx',
            old_name='billing_wl_created_0b9b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='billing_wal_user_id_d55bb3_idx',
            old_name='billing_wt_user_s_ea5f65_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='billing_wal_tx_ref_448a36_idx',
            old_name='billing_wt_tx_ref_1d1b04_idx',
        ),
    ]
