# Generated by Django 4.2.25 on 2026-02-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_financial_workflows'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingreconciliation',
            new_name='billing_bil_status_fa3c2f_idx',
            old_name='billing_br_status_idx',
        ),
        migrations.RenameIndex(
            model_name='billingreconciliation',
            new_name='billing_bil_organiz_9d28b0_idx',
            old_name='billing_br_org_idx',
        ),
        migrations.RenameIndex(
            model_name='insuranceclaim',
            new_name='billing_ins_status_13533b_idx',
            old_name='billing_ic_status_idx',
        ),
        migrations.RenameIndex(
            model_name='insuranceclaim',
            new_name='billing_ins_insuran_32d4b5_idx',
            old_name='billing_ic_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentdispute',
            new_name='billing_pay_status_330101_idx',
            old_name='billing_pd_status_idx',
        ),
    ]
