# Generated by Django 4.2.25 on 2026-05-07 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_alter_walletledgerentry_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('provider', models.CharField(default='flutterwave', max_length=64)),
                ('target_type', models.CharField(choices=[('marketplace_order', 'Marketplace order'), ('service_booking_payment', 'Service booking payment'), ('education_booking', 'Education booking'), ('health_billing_session', 'Health billing session')], max_length=64)),
                ('target_id', models.UUIDField(db_index=True)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('tx_ref', models.CharField(max_length=255, unique=True)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('payment_url', models.URLField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectPaymentAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event', models.CharField(max_length=80)),
                ('provider', models.CharField(default='flutterwave', max_length=64)),
                ('tx_ref', models.CharField(blank=True, db_index=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_payment_audit_events', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='billing.directpaymentintent')),
            ],
        ),
        migrations.AddIndex(
            model_name='directpaymentintent',
            index=models.Index(fields=['user', 'status'], name='billing_dir_user_id_88b144_idx'),
        ),
        migrations.AddIndex(
            model_name='directpaymentintent',
            index=models.Index(fields=['target_type', 'target_id'], name='billing_dir_target__7065dc_idx'),
        ),
        migrations.AddIndex(
            model_name='directpaymentintent',
            index=models.Index(fields=['tx_ref'], name='billing_dir_tx_ref_f52cf5_idx'),
        ),
        migrations.AddConstraint(
            model_name='directpaymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('target_type', 'target_id', 'status'), name='uniq_pending_direct_payment_target'),
        ),
        migrations.AddIndex(
            model_name='directpaymentauditevent',
            index=models.Index(fields=['event', 'created_at'], name='billing_dir_event_820e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='directpaymentauditevent',
            index=models.Index(fields=['tx_ref'], name='billing_dir_tx_ref_29b3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='directpaymentauditevent',
            index=models.Index(fields=['target_type', 'target_id'], name='billing_dir_target__cca035_idx'),
        ),
    ]
