# Generated by Django 4.2.25 on 2026-05-16 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_mediasafetyscan'),
        ('billing', '0007_directpaymentintent_directpaymentauditevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueLaunchEvidenceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('area', models.CharField(choices=[('legal_review', 'Legal review'), ('pastoral_child_safety_review', 'Pastoral and child-safety review'), ('tax_accounting_review', 'Tax and accounting review'), ('flutterwave_sandbox_proof', 'Flutterwave sandbox proof'), ('invoice_receipt_proof', 'Invoice and receipt proof'), ('refund_support_proof', 'Refund and support proof'), ('entitlement_grace_policy', 'Entitlement grace policy'), ('promotion_sponsored_label_policy', 'Promotion sponsored-label policy'), ('verification_fee_policy', 'Verification fee policy'), ('enterprise_contract_policy', 'Enterprise contract policy'), ('privacy_analytics_policy', 'Privacy analytics policy'), ('rollback_proof', 'Rollback proof')], db_index=True, max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_changes', 'Needs changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=32)),
                ('owner_role', models.CharField(blank=True, max_length=80)),
                ('redacted_summary', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_evidence_records_created', to=settings.AUTH_USER_MODEL)),
                ('private_media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_launch_evidence_records', to='media.mediaasset')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_evidence_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueLaunchEvidenceAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_type', models.CharField(choices=[('evidence_record_created', 'Evidence record created'), ('evidence_record_updated', 'Evidence record updated'), ('evidence_record_submitted', 'Evidence record submitted'), ('evidence_record_reviewed', 'Evidence record reviewed'), ('evidence_record_approved', 'Evidence record approved'), ('evidence_record_rejected', 'Evidence record rejected'), ('evidence_record_revoked', 'Evidence record revoked'), ('evidence_record_expired', 'Evidence record expired'), ('private_media_reference_added', 'Private media reference added'), ('private_media_reference_removed', 'Private media reference removed')], db_index=True, max_length=80)),
                ('redacted_detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_evidence_audit_events', to=settings.AUTH_USER_MODEL)),
                ('evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='billing.revenuelaunchevidencerecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='revenuelaunchevidencerecord',
            index=models.Index(fields=['area', 'status'], name='billing_rev_area_5ac4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuelaunchevidencerecord',
            index=models.Index(fields=['status', 'expires_at'], name='billing_rev_status_c80e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuelaunchevidencerecord',
            index=models.Index(fields=['created_by', 'created_at'], name='billing_rev_created_09fc55_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuelaunchevidenceauditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='billing_rev_event_t_2a588d_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuelaunchevidenceauditevent',
            index=models.Index(fields=['evidence_record', 'created_at'], name='billing_rev_evidenc_6423c2_idx'),
        ),
    ]
