# Generated by Django 4.2.25 on 2026-06-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_revenuelaunchevidencerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpaymentintent',
            name='payment_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
