# Generated by Django 4.2.25 on 2026-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_directpaymentintent_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletledgerentry',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('conversion_cash_to_credits', 'Convert cash to credits'), ('conversion_credits_to_cash', 'Convert credits to cash'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('tier_upgrade', 'Tier upgrade'), ('promo', 'Promo'), ('admin_adjust', 'Admin adjustment'), ('purchase', 'Purchase'), ('service_payout', 'Service payout'), ('refund', 'Refund'), ('downgrade_credit', 'Downgrade proration credit'), ('subscription_reversal', 'Subscription payment reversal (refund/chargeback)')], max_length=64),
        ),
    ]
