# Generated by Django 4.2.25 on 2026-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_downgrade_and_reversal_ledger_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpaymentintent',
            name='target_type',
            field=models.CharField(choices=[('marketplace_order', 'Marketplace order'), ('service_booking_payment', 'Service booking payment'), ('education_booking', 'Education booking'), ('health_billing_session', 'Health billing session'), ('channel_membership', 'Channel membership')], max_length=64),
        ),
    ]
