# Generated by Django 4.2.25 on 2026-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_directpaymentintent_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpaymentintent',
            name='target_type',
            field=models.CharField(choices=[('marketplace_order', 'Marketplace order'), ('service_booking_payment', 'Service booking payment'), ('education_booking', 'Education booking'), ('health_billing_session', 'Health billing session'), ('channel_membership', 'Channel membership'), ('channel_tip', 'Channel tip')], max_length=64),
        ),
    ]
