import uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ─── GIVING ───────────────────────────────────────────────────────────
        migrations.CreateModel(
            name="OfferingCampaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("target_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("raised_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("type", models.CharField(choices=[("building", "Building"), ("missions", "Missions"), ("benevolence", "Benevolence"), ("special", "Special"), ("general", "General")], max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("banner_url", models.URLField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="offering_campaigns", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ChurchGiving",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("type", models.CharField(choices=[("tithe", "Tithe"), ("offering", "Offering"), ("pledge", "Pledge"), ("special", "Special"), ("firstfruits", "First Fruits"), ("matching", "Matching")], max_length=20)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("payment_ref", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="church_givings", to=settings.AUTH_USER_MODEL)),
                ("campaign", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="givings", to="church.offeringcampaign")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TithePledge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("period", models.CharField(choices=[("monthly", "Monthly"), ("annual", "Annual")], max_length=10)),
                ("fulfilled_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tithe_pledges", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        # ─── MEMBERSHIP ───────────────────────────────────────────────────────
        migrations.CreateModel(
            name="ChurchMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("church_id", models.UUIDField()),
                ("tier", models.CharField(choices=[("visitor", "Visitor"), ("member", "Member"), ("deacon", "Deacon"), ("elder", "Elder"), ("staff", "Staff")], max_length=20)),
                ("join_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("transferred", "Transferred"), ("deceased", "Deceased")], default="active", max_length=20)),
                ("baptism_date", models.DateField(blank=True, null=True)),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                ("transfer_from", models.CharField(blank=True, max_length=255)),
                ("transfer_to", models.CharField(blank=True, max_length=255)),
                ("pastoral_notes", models.TextField(blank=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="church_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("church_id", models.UUIDField()),
                ("date", models.DateField()),
                ("type", models.CharField(choices=[("physical", "Physical"), ("digital", "Digital")], max_length=10)),
                ("check_in_method", models.CharField(choices=[("qr", "QR Code"), ("manual", "Manual"), ("app", "App")], max_length=10)),
                ("service_type", models.CharField(blank=True, max_length=100)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="ChurchLifeEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("church_id", models.UUIDField()),
                ("type", models.CharField(choices=[("baptism", "Baptism"), ("confirmation", "Confirmation"), ("wedding", "Wedding"), ("funeral", "Funeral"), ("dedication", "Dedication"), ("salvation", "Salvation")], max_length=20)),
                ("event_date", models.DateField()),
                ("officiant", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("witnesses", models.JSONField(default=list)),
                ("certificate_url", models.URLField(blank=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="church_life_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-event_date"]},
        ),
        migrations.CreateModel(
            name="MemberBirthdayAnniversary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(choices=[("birthday", "Birthday"), ("anniversary", "Anniversary"), ("wedding_anniversary", "Wedding Anniversary")], max_length=20)),
                ("date", models.DateField()),
                ("notify_church", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="birthday_anniversaries", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["date"]},
        ),
        # ─── SMALL GROUPS ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name="SmallGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("church_id", models.UUIDField()),
                ("type", models.CharField(choices=[("cell", "Cell"), ("youth", "Youth"), ("women", "Women"), ("men", "Men"), ("couples", "Couples"), ("seniors", "Seniors"), ("mixed", "Mixed")], max_length=10)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("zone", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("meeting_schedule", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                ("max_members", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("leader", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="led_groups", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SmallGroupMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(choices=[("leader", "Leader"), ("co_leader", "Co-Leader"), ("member", "Member")], max_length=15)),
                ("join_date", models.DateField(auto_now_add=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="church.smallgroup")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="small_group_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("group", "user")}},
        ),
        migrations.CreateModel(
            name="SmallGroupAttendance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("present_members", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="church.smallgroup")),
            ],
            options={"ordering": ["-date"]},
        ),
        # ─── DISCIPLESHIP ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name="DiscipleshipJourney",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.CharField(choices=[("seeker", "Seeker"), ("salvation", "Salvation"), ("baptism", "Baptism"), ("basic", "Basic"), ("intermediate", "Intermediate"), ("leadership", "Leadership"), ("mentor", "Mentor")], max_length=20)),
                ("salvation_date", models.DateField(blank=True, null=True)),
                ("baptism_date", models.DateField(blank=True, null=True)),
                ("milestones", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="discipleship_journeys", to=settings.AUTH_USER_MODEL)),
                ("mentor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mentor_disciples", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SpiritualGiftsAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(auto_now=True)),
                ("results", models.JSONField(default=dict)),
                ("dominant_gifts", models.JSONField(default=list)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="spiritual_gifts_assessments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-completed_at"]},
        ),
        migrations.CreateModel(
            name="AccountabilityPartner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("focus_area", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("user1", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accountability_initiated", to=settings.AUTH_USER_MODEL)),
                ("user2", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accountability_received", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-started_at"]},
        ),
        # ─── PRAYER ───────────────────────────────────────────────────────────
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("privacy", models.CharField(choices=[("public", "Public"), ("anonymous", "Anonymous"), ("leaders_only", "Leaders Only")], default="public", max_length=15)),
                ("is_answered", models.BooleanField(default=False)),
                ("testimony", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(default=list)),
                ("prayer_count", models.IntegerField(default=0)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prayer_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PrayerWallEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("is_public", models.BooleanField(default=True)),
                ("prayer_count", models.IntegerField(default=0)),
                ("church_id", models.UUIDField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prayer_wall_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="FastingRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(choices=[("partial", "Partial"), ("full", "Full"), ("liquid", "Liquid"), ("sunrise_to_sunset", "Sunrise to Sunset")], max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("goal", models.TextField(blank=True)),
                ("is_community", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fasting_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-start_date"]},
        ),
        migrations.CreateModel(
            name="PrayerChainSlot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("church_id", models.UUIDField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("focus", models.CharField(blank=True, max_length=255)),
                ("is_filled", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prayer_chain_slots", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["start_time"]},
        ),
        # ─── WORSHIP ──────────────────────────────────────────────────────────
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(blank=True, max_length=255)),
                ("key", models.CharField(blank=True, max_length=10)),
                ("tempo_bpm", models.IntegerField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("ccli_number", models.CharField(blank=True, max_length=50)),
                ("lyrics", models.TextField(blank=True)),
                ("chord_chart_url", models.URLField(blank=True)),
                ("church_id", models.UUIDField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_songs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["title"]},
        ),
        migrations.CreateModel(
            name="SetList",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("church_id", models.UUIDField()),
                ("service_date", models.DateField()),
                ("songs", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_setlists", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-service_date"]},
        ),
        # ─── MINISTRY & OUTREACH ──────────────────────────────────────────────
        migrations.CreateModel(
            name="MinistryDepartment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("church_id", models.UUIDField()),
                ("type", models.CharField(choices=[("children", "Children"), ("youth", "Youth"), ("women", "Women"), ("men", "Men"), ("media", "Media"), ("worship", "Worship"), ("outreach", "Outreach"), ("prayer", "Prayer"), ("admin", "Admin")], max_length=15)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("leader", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="led_departments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="VolunteerSignup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("church_id", models.UUIDField()),
                ("role", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("completed", "Completed"), ("no_show", "No Show")], default="pending", max_length=15)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="volunteer_signups", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="volunteers", to="church.ministrydepartment")),
            ],
            options={"ordering": ["-event_date"]},
        ),
        migrations.CreateModel(
            name="OutreachCampaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("church_id", models.UUIDField()),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("target_count", models.IntegerField(blank=True, null=True)),
                ("current_count", models.IntegerField(default=0)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outreach_campaigns", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-start_date"]},
        ),
        migrations.CreateModel(
            name="EvangelismRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("shares", models.IntegerField(default=0)),
                ("follow_ups", models.IntegerField(default=0)),
                ("salvations", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("church_id", models.UUIDField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evangelism_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-date"]},
        ),
    ]
