# Generated by Django 4.2.25 on 2026-06-19 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_prayer_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
