# Generated by Django 4.2.25 on 2026-10-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_alter_prayerrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerwallentry',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerwallentry',
            name='source_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_entry', to='church.prayerrequest'),
        ),
    ]
