# Generated by Django 4.2.25 on 2026-08-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_department_organization_staffprofile_patientmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='triggered_by',
            field=models.CharField(default='USER', max_length=64),
        ),
    ]
