# Generated by Django 4.2.25 on 2026-05-03 13:48

import apps.verification.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('id', models.UUIDField(default=apps.verification.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('provider_pending', 'Provider Pending'), ('needs_more_info', 'Needs More Info'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=32)),
                ('provider_applicant_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_case_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('evidence_metadata', models.JSONField(blank=True, default=dict)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('public_summary', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_cases_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_cases_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_case',
            },
        ),
        migrations.CreateModel(
            name='VerificationSubject',
            fields=[
                ('id', models.UUIDField(default=apps.verification.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('health_institution', 'Health Institution'), ('education_institution', 'Education Institution'), ('partner', 'Partner')], db_index=True, max_length=40)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_level', models.CharField(blank=True, db_index=True, max_length=64)),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('provider_pending', 'Provider Pending'), ('needs_more_info', 'Needs More Info'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_subject',
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.UUIDField(default=apps.verification.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_type', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('skipped', 'Skipped'), ('expired', 'Expired')], db_index=True, default='pending', max_length=32)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=32)),
                ('provider_check_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=128)),
                ('result_summary', models.CharField(blank=True, max_length=255)),
                ('evidence_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_result_metadata', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='verification.verificationcase')),
            ],
            options={
                'db_table': 'verification_check',
            },
        ),
        migrations.AddField(
            model_name='verificationcase',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='verification.verificationsubject'),
        ),
        migrations.CreateModel(
            name='VerificationBadge',
            fields=[
                ('id', models.UUIDField(default=apps.verification.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('level', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='verification.verificationcase')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_badges_issued', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='verification.verificationsubject')),
            ],
            options={
                'db_table': 'verification_badge',
            },
        ),
        migrations.CreateModel(
            name='VerificationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=apps.verification.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_audit_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='verification.verificationcase')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='verification.verificationsubject')),
            ],
            options={
                'db_table': 'verification_audit_event',
            },
        ),
        migrations.AddIndex(
            model_name='verificationsubject',
            index=models.Index(fields=['subject_type', 'subject_id'], name='verificatio_subject_89f8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsubject',
            index=models.Index(fields=['owner', 'subject_type'], name='verificatio_owner_i_0c49bc_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsubject',
            index=models.Index(fields=['current_status', 'current_level'], name='verificatio_current_fe19f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationsubject',
            constraint=models.UniqueConstraint(fields=('subject_type', 'subject_id'), name='verification_unique_subject'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['case', 'check_type'], name='verificatio_case_id_cfb4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['status', 'check_type'], name='verificatio_status_df2f16_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['provider', 'provider_check_id'], name='verificatio_provide_05975a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['subject', 'status'], name='verificatio_subject_2780bf_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['status', 'created_at'], name='verificatio_status_1a6cad_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['provider', 'provider_case_id'], name='verificatio_provide_ac4061_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['level', 'status'], name='verificatio_level_0f6a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationbadge',
            index=models.Index(fields=['subject', 'status', 'public'], name='verificatio_subject_eb0fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationbadge',
            index=models.Index(fields=['code', 'status'], name='verificatio_code_0c26b3_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationbadge',
            index=models.Index(fields=['expires_at'], name='verificatio_expires_c73277_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationbadge',
            constraint=models.UniqueConstraint(fields=('subject', 'code'), name='verification_unique_subject_badge'),
        ),
        migrations.AddIndex(
            model_name='verificationauditevent',
            index=models.Index(fields=['subject', 'created_at'], name='verificatio_subject_461496_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationauditevent',
            index=models.Index(fields=['case', 'created_at'], name='verificatio_case_id_6ec56e_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationauditevent',
            index=models.Index(fields=['action', 'created_at'], name='verificatio_action_54c3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationauditevent',
            index=models.Index(fields=['provider', 'created_at'], name='verificatio_provide_234e39_idx'),
        ),
    ]
