# Generated by Django 4.2.25 on 2026-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationsubject',
            name='subject_type',
            field=models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('health_institution', 'Health Institution'), ('health_practitioner', 'Health Practitioner'), ('education_institution', 'Education Institution'), ('partner', 'Partner')], db_index=True, max_length=40),
        ),
    ]
