# Generated by Django 4.2.25 on 2026-06-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testimonyreach',
            new_name='testimony_t_to_user_e81b19_idx',
            old_name='testimony_tr_to_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userseason',
            new_name='testimony_u_categor_721677_idx',
            old_name='testimony_us_category_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='userseason',
            new_name='testimony_u_user_id_2707f6_idx',
            old_name='testimony_us_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='usertestimony',
            new_name='testimony_u_categor_2ea92b_idx',
            old_name='testimony_ut_category_is_available_idx',
        ),
    ]
