# Generated by Django 4.2.25 on 2026-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0002_rename_testimony_tr_to_user_status_idx_testimony_t_to_user_e81b19_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestimony',
            name='media_kind',
            field=models.CharField(choices=[('none', 'None'), ('video', 'Video'), ('file', 'File')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='usertestimony',
            name='resource_mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usertestimony',
            name='resource_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usertestimony',
            name='resource_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
