# Generated by Django 4.2.25 on 2026-09-01 05:27

import apps.testimony.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0003_usertestimony_media_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestimony',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertestimony',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=apps.testimony.models._default_testimony_expiry),
        ),
    ]
