# Generated by Django 4.2.25 on 2025-10-10 19:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_channel',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('owner_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('HIDDEN', 'Hidden')], default='PUBLIC', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archived', models.BooleanField(default=False, help_text='If archived, new activity is restricted.')),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'core_community',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='If false, group is invite-only or request-only depending on membership settings.')),
                ('archived', models.BooleanField(default=False)),
                ('member_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.community')),
            ],
            options={
                'db_table': 'core_group',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_permission',
                'ordering': ('codename',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('COMMUNITY', 'Community'), ('GROUP', 'Group'), ('CHANNEL', 'Channel')], default='GLOBAL', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-assigned role for new members in a scope')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='core.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission')),
            ],
            options={
                'db_table': 'core_role',
                'unique_together': {('name', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='MembershipInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_by_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.community')),
                ('created_by_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.group')),
            ],
            options={
                'db_table': 'core_membership_invite',
            },
        ),
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('allowed_mimetypes', models.JSONField(blank=True, default=list, help_text='If non-empty, only these mimetypes are allowed.')),
                ('message_rate_limit_seconds', models.PositiveIntegerField(default=0, help_text='Minimum seconds between messages (0 = no slow mode)')),
                ('max_message_length', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)])),
                ('join_policy', models.CharField(choices=[('OPEN', 'Open: anyone can join'), ('INVITE', 'Invite-only'), ('REQUEST', 'Request to join (pending approval)')], default='OPEN', max_length=16)),
                ('discoverability', models.CharField(choices=[('VISIBLE', 'Visible in search'), ('HIDDEN', 'Hidden from search')], default='VISIBLE', max_length=16)),
                ('profanity_filter', models.BooleanField(default=False)),
                ('max_attachments_per_message', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.group')),
            ],
            options={
                'db_table': 'core_group_settings',
            },
        ),
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read_only', models.BooleanField(default=False)),
                ('allow_threads', models.BooleanField(default=True)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('allowed_mimetypes', models.JSONField(blank=True, default=list)),
                ('slow_mode_seconds', models.PositiveIntegerField(default=0)),
                ('max_message_length', models.PositiveIntegerField(default=5000)),
                ('moderation_queue_enabled', models.BooleanField(default=False, help_text='If true, new messages may require moderator approval.')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.channel')),
            ],
            options={
                'db_table': 'core_channel_settings',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='channels', to='core.community'),
        ),
        migrations.AddField(
            model_name='channel',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='channels', to='core.group'),
        ),
        migrations.CreateModel(
            name='AccessControlEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', models.JSONField(default=list)),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], default='ALLOW', max_length=8)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('principal_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'core_ace',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_object_id', models.CharField(max_length=255)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('principal_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.role')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'core_role_assignment',
                'indexes': [models.Index(fields=['principal_content_type', 'principal_object_id'], name='core_role_a_princip_6b2cee_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='core_role_a_target__0969ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_object_id', models.CharField(max_length=255)),
                ('subject_object_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('BAN', 'Ban'), ('UNBAN', 'Unban'), ('MUTE', 'Mute'), ('UNMUTE', 'Unmute'), ('WARN', 'Warn'), ('REMOVE', 'Remove content')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('performed_by_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'core_moderation_action',
                'indexes': [models.Index(fields=['action'], name='core_modera_action_a7459c_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='core_modera_target__1c1d66_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_object_id', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('reviewed_by_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='core.group')),
                ('reviewed_by_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('user_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'core_membership_request',
                'indexes': [models.Index(fields=['group', 'status'], name='core_member_group_i_933c37_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_object_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INVITED', 'Invited'), ('BANNED', 'Banned'), ('LEFT', 'Left')], default='PENDING', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_moderator', models.BooleanField(default=False)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.group')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.role')),
                ('user_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'core_membership',
                'indexes': [models.Index(fields=['group', 'status'], name='core_member_group_i_3915fa_idx'), models.Index(fields=['user_content_type', 'user_object_id'], name='core_member_user_co_e4dec4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'user_content_type', 'user_object_id'), name='unique_group_user_membership'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['community', 'slug'], name='core_group_communi_600922_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['archived'], name='core_group_archive_79cb23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('community', 'slug')},
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug'], name='core_commun_slug_4749d8_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['archived'], name='core_commun_archive_675209_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['slug'], name='core_channe_slug_663543_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['archived'], name='core_channe_archive_0287e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('slug',)},
        ),
        migrations.AddIndex(
            model_name='accesscontrolentry',
            index=models.Index(fields=['principal_content_type', 'principal_object_id'], name='core_ace_princip_61f907_idx'),
        ),
        migrations.AddIndex(
            model_name='accesscontrolentry',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='core_ace_target__ec2a83_idx'),
        ),
    ]
