# Generated by Django on (manual)

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthcareOrganization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("org_type", models.CharField(choices=[("hospital", "Hospital"), ("clinic", "Clinic"), ("laboratory", "Laboratory"), ("pharmacy", "Pharmacy"), ("diagnostic", "Diagnostic"), ("wellness", "Wellness Center")], default="hospital", max_length=24)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("suspended", "Suspended")], default="active", max_length=32)),
                ("region", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="medical_organizations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "core_healthcare_organization",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["tenant_id"], name="core_health_tenant__5fadb1_idx"),
                    models.Index(fields=["org_type", "status"], name="core_health_org_typ_687de8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicalProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_type", models.CharField(choices=[("health", "Health Profile"), ("market", "Market Profile"), ("education", "Education Profile")], default="health", max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("archived", "Archived")], default="active", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("location", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_medical_profiles", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profiles", to="core.healthcareorganization")),
            ],
            options={
                "db_table": "core_medical_profile",
                "ordering": ["-created_at"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("is_ward", models.BooleanField(default=False)),
                ("services", models.JSONField(blank=True, default=list)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="departments", to="core.medicalprofile")),
            ],
            options={
                "db_table": "core_medical_department",
                "ordering": ["name"],
                "unique_together": {("profile", "name")},
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=64)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("licenses", models.JSONField(blank=True, default=list)),
                ("shifts", models.JSONField(blank=True, default=list)),
                ("is_on_call", models.BooleanField(default=False)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staff_profiles", to="core.medicalprofile")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="medical_staff_profiles", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "core_medical_staff",
                "indexes": [
                    models.Index(fields=["profile", "role"], name="core_medica_profile_7dd6dc_idx"),
                    models.Index(fields=["is_on_call"], name="core_medica_is_on_c_095f52_idx"),
                ],
            },
        ),
    ]
