# Generated by Django manually for patient master data models.

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_healthcareorganization_medicalprofile_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMasterRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                ("mrn", models.CharField(max_length=32, unique=True)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(choices=[("unknown", "Unknown"), ("male", "Male"), ("female", "Female"), ("other", "Other")], default="unknown", max_length=16)),
                ("primary_contact", models.JSONField(blank=True, default=dict)),
                ("emergency_contact", models.JSONField(blank=True, default=dict)),
                ("family", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("deceased", "Deceased")], default="active", max_length=16)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="patients", to="core.healthcareorganization")),
            ],
            options={
                "db_table": "core_patient_master",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id"], name="core_patien_tenant__2d59fd_idx"),
                    models.Index(fields=["mrn"], name="core_patien_mrn_0023e0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientFamilyProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relationship", models.CharField(max_length=64)),
                ("members", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="family_profiles", to="core.patientmasterrecord")),
            ],
            options={
                "db_table": "core_patient_family",
                "ordering": ["relationship"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purpose", models.CharField(max_length=128)),
                ("consent_text", models.TextField()),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consents", to="core.patientmasterrecord")),
                ("granted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="granted_consents", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "core_consent_record",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="EncounterNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encounter_type", models.CharField(max_length=64, default="clinical")),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("ai_insights", models.JSONField(blank=True, default=dict)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="encounters", to="core.patientmasterrecord")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.healthcareorganization")),
                ("profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.medicalprofile")),
                ("clinician", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="encounters", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "core_encounter_note",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("scheduled", "Scheduled"), ("cancelled", "Cancelled"), ("completed", "Completed")], default="scheduled", max_length=16)),
                ("queue_position", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="core.patientmasterrecord")),
                ("profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.medicalprofile")),
            ],
            options={
                "db_table": "core_appointment",
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
