# Generated by Django 4.2.25 on 2026-01-24 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_department_organization_staffprofile_patientmaster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_staff_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemedicineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tele_sessions', to='core.appointment')),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tele_clinician_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tele_sessions', to='core.patientmasterrecord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tele_sessions', to='core.medicalprofile')),
            ],
            options={
                'db_table': 'core_telemedicine_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffauditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VoiceDictation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_metadata', models.JSONField(blank=True, default=dict)),
                ('transcript', models.TextField(blank=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictations', to=settings.AUTH_USER_MODEL)),
                ('groq_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_integration.aijob')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictations', to='core.telemedicinesession')),
            ],
            options={
                'db_table': 'core_voice_dictation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vital_type', models.CharField(choices=[('pulse', 'Pulse'), ('blood_pressure', 'Blood pressure'), ('respiration', 'Respiration rate'), ('temperature', 'Temperature'), ('oxygen_saturation', 'Oxygen saturation')], max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('units', models.CharField(blank=True, max_length=24)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.patientmasterrecord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile')),
            ],
            options={
                'db_table': 'core_vital_sign',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'vital_type'], name='core_vital__patient_9b4d1f_idx'), models.Index(fields=['recorded_at'], name='core_vital__recorde_d5f776_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemedicineDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=128)),
                ('device_type', models.CharField(default='camera', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.telemedicinesession')),
            ],
            options={
                'db_table': 'core_telemedicine_device',
                'unique_together': {('session', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name', models.CharField(max_length=160)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('route', models.CharField(blank=True, max_length=64)),
                ('frequency', models.CharField(blank=True, max_length=64)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('fhir_resource', models.JSONField(blank=True, default=dict)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='core.encounternote')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.patientmasterrecord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile')),
            ],
            options={
                'db_table': 'core_medication_order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='core_medica_patient_4357f4_idx'), models.Index(fields=['drug_name'], name='core_medica_drug_na_ef0dfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AllergyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.CharField(max_length=140)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=16)),
                ('reaction', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='core.patientmasterrecord')),
            ],
            options={
                'db_table': 'core_patient_allergy',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='core_patien_patient_477f69_idx')],
            },
        ),
    ]
