# Generated by Django 4.2.25 on 2026-02-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_medical_resources_phase2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaleventlog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='clinicaltask',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='emergencyescalation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='referralroute',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='triagerecord',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='clinicaleventlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clinicaleventlog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_clinical_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicaltask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicaltask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicaltask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile'),
        ),
        migrations.AlterField(
            model_name='diagnosticorder',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencyescalation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emergencyescalation',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicationadherencereminder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicationadherencereminder',
            name='medication_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicationorder'),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplyforecast',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
