# Generated by Django 4.2.25 on 2026-02-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_compliance_governance'),
        ('core', '0010_remove_clinicaleventlog_is_deleted_and_more'),
    ]

    operations = [
    ]
