# Generated by Django 4.2.25 on 2026-02-10 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260209_1403'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complianceauditlog',
            new_name='core_compli_actor_i_bc364e_idx',
            old_name='core_compliance_a_actor_action_idx',
        ),
        migrations.RenameIndex(
            model_name='complianceauditlog',
            new_name='core_compli_severit_5cf53d_idx',
            old_name='core_compliance_a_severity_idx',
        ),
        migrations.AlterField(
            model_name='complianceauditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='credentialverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='dataaccessconsent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
