# Generated by Django 4.2.25 on 2026-02-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_onboarding_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalprofile',
            old_name='compliance_documents',
            new_name='compliance_documents_metadata',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_document_records', to='core.healthcareorganization'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_document_records', to='core.medicalprofile'),
        ),
        migrations.AlterField(
            model_name='healthcareorganization',
            name='compliance_officer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='healthcareorganization',
            name='onboarding_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='healthcareorganization',
            name='risk_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='healthcareorganization',
            index=models.Index(fields=['onboarding_status'], name='core_org_onboarding_idx'),
        ),
    ]
