# Generated by Django 4.2.25 on 2026-04-25 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_rename_compliance_documents_medicalprofile_compliance_documents_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure_name', models.CharField(max_length=180)),
                ('procedure_code', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=24)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='core.patientmasterrecord')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile')),
            ],
            options={
                'db_table': 'core_procedure_record',
                'ordering': ['-performed_at', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='core_proced_patient_d71041_idx'), models.Index(fields=['procedure_code'], name='core_proced_procedu_e673f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProblemRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_system', models.CharField(blank=True, max_length=64)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('inactive', 'Inactive')], default='active', max_length=24)),
                ('verification_status', models.CharField(choices=[('provisional', 'Provisional'), ('confirmed', 'Confirmed'), ('refuted', 'Refuted')], default='provisional', max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('diagnosed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_problems', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.patientmasterrecord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile')),
            ],
            options={
                'db_table': 'core_problem_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'clinical_status'], name='core_proble_patient_9e7bc8_idx'), models.Index(fields=['code'], name='core_proble_code_0bcb30_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=180)),
                ('vaccine_code', models.CharField(blank=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('due', 'Due'), ('declined', 'Declined')], default='completed', max_length=24)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('dose_number', models.PositiveIntegerField(blank=True, null=True)),
                ('series_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_immunizations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='core.patientmasterrecord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile')),
            ],
            options={
                'db_table': 'core_immunization_record',
                'ordering': ['-administered_at', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='core_immuni_patient_8c8bd7_idx'), models.Index(fields=['vaccine_code'], name='core_immuni_vaccine_a69bc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('lab', 'Lab'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('discharge', 'Discharge'), ('insurance', 'Insurance'), ('referral', 'Referral'), ('general', 'General')], default='general', max_length=24)),
                ('source_type', models.CharField(choices=[('user', 'User'), ('provider', 'Provider'), ('import', 'Import')], default='user', max_length=24)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.patientmasterrecord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_health_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_health_document',
                'ordering': ['-issued_at', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'category'], name='core_health_patient_f6259d_idx'), models.Index(fields=['status'], name='core_health_status_1fcdb6_idx')],
            },
        ),
    ]
