# Generated by Django 4.2.25 on 2026-04-25 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_procedurerecord_problemrecord_immunizationrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecordExchangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], max_length=16)),
                ('exchange_format', models.CharField(choices=[('fhir_bundle', 'FHIR Bundle'), ('kis_bundle', 'KIS Bundle')], default='fhir_bundle', max_length=24)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_record_exchanges', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_logs', to='core.patientmasterrecord')),
            ],
            options={
                'db_table': 'core_health_record_exchange_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'direction'], name='core_health_patient_e72d25_idx'), models.Index(fields=['status'], name='core_health_status_5f9058_idx')],
            },
        ),
    ]
