# Generated by Django 4.2.25 on 2026-04-25 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_healthrecordexchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('steps', 'Steps'), ('sleep', 'Sleep'), ('heart_rate', 'Heart rate'), ('weight', 'Weight'), ('blood_pressure', 'Blood pressure'), ('blood_glucose', 'Blood glucose'), ('workout', 'Workout')], max_length=40)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('clinical', 'Clinical'), ('apple_health', 'Apple Health'), ('health_connect', 'Health Connect'), ('google_fit', 'Google Fit'), ('wearable', 'Wearable'), ('imported', 'Imported')], default='manual', max_length=40)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('measurement_window', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('sleep_session', 'Sleep session'), ('workout_session', 'Workout session')], default='instant', max_length=40)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(blank=True, max_length=24)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('normalized_units', models.CharField(blank=True, max_length=24)),
                ('secondary_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('secondary_units', models.CharField(blank=True, max_length=24)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('is_clinically_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_metrics', to='core.patientmasterrecord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicalprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_wellness_metric',
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'metric_type'], name='core_wellne_patient_31e64d_idx'), models.Index(fields=['patient', 'metric_type', 'recorded_at'], name='core_wellne_patient_734b6f_idx'), models.Index(fields=['source', 'metric_type'], name='core_wellne_source_6cd21e_idx')],
            },
        ),
    ]
