# Generated by Django 4.2.25 on 2026-04-25 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_wellnessmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDataAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('caregiver', 'Caregiver'), ('family', 'Family'), ('guardian', 'Guardian'), ('clinician', 'Clinician')], default='caregiver', max_length=24)),
                ('scope', models.CharField(choices=[('summary', 'Summary'), ('emergency', 'Emergency'), ('records', 'Records'), ('full', 'Full')], default='summary', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', max_length=24)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_emergency_override', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_health_data_access', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data_access_grants', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.patientmasterrecord')),
            ],
            options={
                'db_table': 'core_health_data_access_grant',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='core_health_patient_c83e03_idx'), models.Index(fields=['granted_to', 'status'], name='core_health_granted_dcac1c_idx'), models.Index(fields=['expires_at'], name='core_health_expires_40b5fd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='healthdataaccessgrant',
            constraint=models.UniqueConstraint(fields=('patient', 'granted_to', 'role', 'scope'), name='core_health_access_grant_unique_active_scope'),
        ),
    ]
