# Generated by Django 4.2.25 on 2025-10-11 12:08

import apps.moderation.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('actor_id', models.UUIDField()),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('AI', 'AI')], max_length=16)),
                ('target_type', models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('GROUP', 'Group'), ('CHANNEL', 'Channel'), ('USER', 'User')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('reporter_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=16)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('escalation_level', models.CharField(choices=[('AUTO', 'Auto'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], default='AUTO', max_length=16)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('target_type', models.CharField(max_length=32)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('action_json', models.JSONField(blank=True, default=dict)),
                ('escalation_json', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('score', models.FloatField(default=100.0)),
                ('flags_received', models.IntegerField(default=0)),
                ('actions_taken', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('alert_type', models.CharField(choices=[('HIGH_SEVERITY', 'High Severity'), ('LEGAL', 'Legal'), ('COMMUNITY_RISK', 'Community Risk')], max_length=32)),
                ('message', models.TextField()),
                ('sent_to_ids', models.JSONField(blank=True, default=list)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Moderation.flag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('WARN', 'Warn'), ('SUSPEND', 'Suspend'), ('DELETE', 'Delete'), ('BAN', 'Ban'), ('TEMP_RESTRICT', 'Temporary Restrict'), ('ESCALATE', 'Escalate')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('performed_by_id', models.UUIDField()),
                ('scheduled_action_at', models.DateTimeField(blank=True, null=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='Moderation.flag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
