# Generated by Django 4.2.25 on 2026-01-08 16:25

import apps.moderation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0002_userblock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userblock',
            new_name='Moderation__blocker_4526d5_idx',
            old_name='moderation_blocker_blocked_idx',
        ),
        migrations.RenameIndex(
            model_name='userblock',
            new_name='Moderation__blocker_85a467_idx',
            old_name='moderation_blocker_created_idx',
        ),
        migrations.AlterField(
            model_name='userblock',
            name='id',
            field=models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
