# Generated by Django 4.2.25 on 2026-04-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0003_rename_moderation_blocker_blocked_idx_moderation__blocker_4526d5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='target_type',
            field=models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('GROUP', 'Group'), ('CHANNEL', 'Channel'), ('USER', 'User'), ('STATUS', 'Status')], max_length=32),
        ),
    ]
