# Generated by Django 4.2.25 on 2026-09-01 03:15

import apps.moderation.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0004_alter_flag_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageReport',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conversation_id', models.CharField(db_index=True, max_length=64)),
                ('message_id', models.CharField(db_index=True, max_length=64)),
                ('reported_by_id', models.UUIDField()),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('conversation_id', 'message_id', 'reported_by_id')},
            },
        ),
    ]
