# Generated by Django 4.2.25 on 2026-09-01 03:32

import apps.moderation.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0005_chatmessagereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('WARN', 'Warn'), ('SUSPEND', 'Suspend'), ('DELETE', 'Delete'), ('BAN', 'Ban'), ('TEMP_RESTRICT', 'Temporary Restrict'), ('ESCALATE', 'Escalate'), ('REINSTATE', 'Reinstate')], max_length=32),
        ),
        migrations.CreateModel(
            name='ModerationAppeal',
            fields=[
                ('id', models.UUIDField(default=apps.moderation.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('target_type', models.CharField(choices=[('flag', 'Flag'), ('media_safety_scan', 'Media safety scan'), ('channel_moderation_record', 'Channel moderation record'), ('chat_message_report', 'Chat message report')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('appellant_id', models.UUIDField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('UPHELD', 'Upheld'), ('OVERTURNED', 'Overturned')], default='PENDING', max_length=16)),
                ('decided_by_id', models.UUIDField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_applied', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('target_type', 'target_id', 'appellant_id', 'status')},
            },
        ),
    ]
