# Generated by Django 4.2.25 on 2026-03-06 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0017_broadcast_health_profile_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDashboardAvailabilityDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_value', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('fully_booked', 'Fully Booked'), ('on_call', 'On Call'), ('holiday', 'Holiday'), ('blocked', 'Blocked')], default='available', max_length=32)),
            ],
            options={
                'db_table': 'health_dashboard_availability_day',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('institution_type', models.CharField(default='clinic', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('about_text', models.TextField(blank=True, default='')),
                ('staff_display_enabled', models.BooleanField(default=True)),
                ('pricing_visibility_enabled', models.BooleanField(default=True)),
                ('emergency_banner_enabled', models.BooleanField(default=False)),
                ('emergency_banner_message', models.TextField(blank=True, default='')),
                ('landing_background_image_url', models.TextField(blank=True, default='')),
                ('landing_background_color_key', models.CharField(blank=True, default='', max_length=64)),
                ('landing_logo_url', models.TextField(blank=True, default='')),
                ('broadcast_institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_dashboard', to='broadcasts.broadcasthealthinstitution')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_dashboard_institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_dashboard_institution',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_uid', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('section_type', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_section',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardSeo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_seo',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardServiceAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_uid', models.CharField(db_index=True, max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('slot_gap_min', models.PositiveIntegerField(default=10)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_availability_rows', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_service_availability',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardSeoKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='health_dashboard.healthdashboardseo')),
            ],
            options={
                'db_table': 'health_dashboard_seo_keyword',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardSectionField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_path', models.CharField(db_index=True, max_length=255)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('null', 'Null'), ('empty_list', 'Empty List'), ('empty_object', 'Empty Object')], default='string', max_length=24)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='health_dashboard.healthdashboardsection')),
            ],
            options={
                'db_table': 'health_dashboard_section_field',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('service_uid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('patient_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='scheduled', max_length=32)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_schedule_entry',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardRecurringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_key', models.CharField(max_length=16)),
                ('frequency', models.CharField(default='weekly', max_length=32)),
                ('start_time', models.CharField(blank=True, default='', max_length=16)),
                ('end_time', models.CharField(blank=True, default='', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_recurring_rule',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardOperatingHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_operating_hour',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardHero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('slogan', models.TextField(blank=True, default='')),
                ('cta_label', models.CharField(blank=True, default='Book Now', max_length=255)),
                ('cta_url', models.TextField(blank=True, default='')),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_hero',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardGalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_url', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_gallery_item',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardFinancialSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_revenue_cents', models.BigIntegerField(default=0)),
                ('insurance_revenue_cents', models.BigIntegerField(default=0)),
                ('direct_revenue_cents', models.BigIntegerField(default=0)),
                ('pending_payments_cents', models.BigIntegerField(default=0)),
                ('refunds_cents', models.BigIntegerField(default=0)),
                ('disputes_count', models.PositiveIntegerField(default=0)),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_financial_summary',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardFaq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_faq',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_contact',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardComplianceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_log_count', models.PositiveIntegerField(default=0)),
                ('pending_credential_reviews', models.PositiveIntegerField(default=0)),
                ('license_expiring_soon_count', models.PositiveIntegerField(default=0)),
                ('active_consents', models.PositiveIntegerField(default=0)),
                ('pending_documents', models.PositiveIntegerField(default=0)),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_summary', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_compliance_summary',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_certification',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardBlockedTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_value', models.DateField(db_index=True)),
                ('start_time', models.CharField(max_length=16)),
                ('end_time', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_blocked_time',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardAvailabilityTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_value', models.CharField(max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('availability_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='health_dashboard.healthdashboardavailabilityday')),
            ],
            options={
                'db_table': 'health_dashboard_availability_time',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardAvailabilityService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_uid', models.CharField(db_index=True, max_length=128)),
                ('availability_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='health_dashboard.healthdashboardavailabilityday')),
            ],
            options={
                'db_table': 'health_dashboard_availability_service',
            },
        ),
        migrations.AddField(
            model_name='healthdashboardavailabilityday',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='health_dashboard.healthdashboardinstitution'),
        ),
        migrations.CreateModel(
            name='HealthDashboardAnalyticsRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('booking', 'Booking'), ('consultation', 'Consultation'), ('schedule', 'Schedule'), ('payment', 'Payment'), ('rating', 'Rating'), ('traffic', 'Traffic')], db_index=True, max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(blank=True, default='', max_length=64)),
                ('service_uid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('patient_uid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('value_decimal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_dashboard_analytics_records', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_records', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_analytics_record',
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardSocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_social_link',
                'indexes': [models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_2648d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardSlotTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_key', models.CharField(max_length=16)),
                ('start_time', models.CharField(max_length=16)),
                ('end_time', models.CharField(max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_slot_template',
                'indexes': [models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_fc61dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthDashboardServiceVisibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_uid', models.CharField(db_index=True, max_length=128)),
                ('is_visible', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_visibilities', to='health_dashboard.healthdashboardinstitution')),
            ],
            options={
                'db_table': 'health_dashboard_service_visibility',
                'indexes': [models.Index(fields=['dashboard', 'service_uid'], name='health_dash_dashboa_276963_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='healthdashboardservicevisibility',
            constraint=models.UniqueConstraint(fields=('dashboard', 'service_uid'), name='health_dashboard_service_visibility_unique'),
        ),
        migrations.AddConstraint(
            model_name='healthdashboardserviceavailability',
            constraint=models.UniqueConstraint(fields=('dashboard', 'service_uid'), name='health_dashboard_service_availability_unique'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardseokeyword',
            index=models.Index(fields=['seo', 'sort_order'], name='health_dash_seo_id_18a0bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthdashboardseokeyword',
            constraint=models.UniqueConstraint(fields=('seo', 'keyword', 'sort_order'), name='health_dashboard_seo_keyword_unique'),
        ),
        migrations.AddConstraint(
            model_name='healthdashboardsectionfield',
            constraint=models.UniqueConstraint(fields=('section', 'field_path'), name='health_dashboard_section_field_unique'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardsection',
            index=models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_67c5bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthdashboardsection',
            constraint=models.UniqueConstraint(fields=('dashboard', 'section_uid'), name='health_dashboard_section_unique'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardscheduleentry',
            index=models.Index(fields=['dashboard', 'starts_at'], name='health_dash_dashboa_90da40_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardscheduleentry',
            index=models.Index(fields=['dashboard', 'status'], name='health_dash_dashboa_30cf74_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardrecurringrule',
            index=models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_24bd30_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardoperatinghour',
            index=models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_d00da9_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardinstitution',
            index=models.Index(fields=['owner_user', 'institution_type'], name='health_dash_owner_u_2a55df_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardinstitution',
            index=models.Index(fields=['is_active'], name='health_dash_is_acti_9750a7_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardgalleryitem',
            index=models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_ecb40b_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardfaq',
            index=models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_ede6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardcertification',
            index=models.Index(fields=['dashboard', 'sort_order'], name='health_dash_dashboa_32431e_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardblockedtime',
            index=models.Index(fields=['dashboard', 'date_value'], name='health_dash_dashboa_fb2e88_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardavailabilitytime',
            index=models.Index(fields=['availability_day', 'sort_order'], name='health_dash_availab_636386_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthdashboardavailabilitytime',
            constraint=models.UniqueConstraint(fields=('availability_day', 'time_value', 'sort_order'), name='health_dashboard_availability_time_unique'),
        ),
        migrations.AddConstraint(
            model_name='healthdashboardavailabilityservice',
            constraint=models.UniqueConstraint(fields=('availability_day', 'service_uid'), name='health_dashboard_availability_service_unique'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardavailabilityday',
            index=models.Index(fields=['dashboard', 'date_value'], name='health_dash_dashboa_d052a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthdashboardavailabilityday',
            constraint=models.UniqueConstraint(fields=('dashboard', 'date_value'), name='health_dashboard_availability_day_unique'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardanalyticsrecord',
            index=models.Index(fields=['dashboard', 'metric_type', 'occurred_at'], name='health_dash_dashboa_b5b5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdashboardanalyticsrecord',
            index=models.Index(fields=['dashboard', 'occurred_at'], name='health_dash_dashboa_a784f1_idx'),
        ),
    ]
