# Generated by Django 4.2.25 on 2026-03-09 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def _normalize_medium_pairs(medium_ids, medium_names):
    ids = [str(item or "").strip() for item in (medium_ids or []) if str(item or "").strip()]
    names = [str(item or "").strip() for item in (medium_names or []) if str(item or "").strip()]
    max_len = max(len(ids), len(names))
    out = []
    for index in range(max_len):
        medium_uid = ids[index] if index < len(ids) else ""
        medium_name = names[index] if index < len(names) else ""
        if not medium_uid and not medium_name:
            continue
        out.append((medium_uid, medium_name))
    return out


def forwards_populate_relational_health_data(apps, schema_editor):
    HealthDashboardInstitution = apps.get_model("health_dashboard", "HealthDashboardInstitution")
    HealthDashboardCard = apps.get_model("health_dashboard", "HealthDashboardCard")
    HealthDashboardContact = apps.get_model("health_dashboard", "HealthDashboardContact")
    HealthDashboardInstitutionService = apps.get_model("health_dashboard", "HealthDashboardInstitutionService")
    HealthDashboardInstitutionServiceMedium = apps.get_model("health_dashboard", "HealthDashboardInstitutionServiceMedium")
    HealthDashboardInstitutionLandingPage = apps.get_model("health_dashboard", "HealthDashboardInstitutionLandingPage")
    HealthDashboardLandingPageAddress = apps.get_model("health_dashboard", "HealthDashboardLandingPageAddress")
    HealthDashboardLandingPageContact = apps.get_model("health_dashboard", "HealthDashboardLandingPageContact")
    BroadcastHealthInstitutionService = apps.get_model("broadcasts", "BroadcastHealthInstitutionService")

    for dashboard in HealthDashboardInstitution.objects.select_related("broadcast_institution").all().iterator():
        HealthDashboardCard.objects.get_or_create(
            dashboard=dashboard,
            defaults={
                "tagline": "",
                "short_description": str(dashboard.about_text or ""),
                "accent_color_key": str(dashboard.landing_background_color_key or ""),
            },
        )

        has_landing_content = any(
            [
                str(dashboard.about_text or "").strip(),
                str(dashboard.landing_background_image_url or "").strip(),
                str(dashboard.landing_logo_url or "").strip(),
            ]
        )
        if has_landing_content:
            landing_page, _ = HealthDashboardInstitutionLandingPage.objects.get_or_create(
                dashboard=dashboard,
                defaults={
                    "title": str(dashboard.name or ""),
                    "description": str(dashboard.about_text or ""),
                    "hero_headline": str(dashboard.name or ""),
                    "hero_subheadline": str(dashboard.about_text or ""),
                    "hero_cta_label": "Book Appointment",
                    "hero_cta_url": "",
                    "logo_url": str(dashboard.landing_logo_url or ""),
                    "background_image_url": str(dashboard.landing_background_image_url or ""),
                    "background_color_key": str(dashboard.landing_background_color_key or ""),
                    "is_published": True,
                    "created_by_id": dashboard.owner_user_id,
                    "updated_by_id": dashboard.owner_user_id,
                },
            )
            contact_row = HealthDashboardContact.objects.filter(dashboard=dashboard).first()
            if contact_row:
                HealthDashboardLandingPageContact.objects.get_or_create(
                    landing_page=landing_page,
                    defaults={
                        "primary_phone": str(contact_row.phone or ""),
                        "secondary_phone": "",
                        "email": str(contact_row.email or ""),
                        "website_url": "",
                        "whatsapp_phone": "",
                    },
                )
                if str(contact_row.address or "").strip():
                    HealthDashboardLandingPageAddress.objects.get_or_create(
                        landing_page=landing_page,
                        defaults={
                            "line_one": str(contact_row.address or ""),
                            "line_two": "",
                            "city": "",
                            "state": "",
                            "postal_code": "",
                            "country": "",
                            "landmark": "",
                        },
                    )

        service_rows = (
            BroadcastHealthInstitutionService.objects.filter(institution=dashboard.broadcast_institution)
            .order_by("created_at")
        )
        for index, source_row in enumerate(service_rows):
            service_uid = str(source_row.service_uid or "").strip() or f"service-{index + 1}"
            service, _ = HealthDashboardInstitutionService.objects.update_or_create(
                dashboard=dashboard,
                service_uid=service_uid,
                defaults={
                    "name": str(source_row.name or f"Service {index + 1}"),
                    "description": str(source_row.description or ""),
                    "active": bool(source_row.active),
                    "base_price_cents": source_row.base_price_cents,
                    "sort_order": index,
                    "source_broadcast_service_id": source_row.id,
                },
            )

            HealthDashboardInstitutionServiceMedium.objects.filter(service=service).delete()
            medium_rows = []
            for medium_index, (medium_uid, medium_name) in enumerate(
                _normalize_medium_pairs(source_row.medium_ids, source_row.medium_names)
            ):
                medium_rows.append(
                    HealthDashboardInstitutionServiceMedium(
                        service=service,
                        medium_uid=medium_uid,
                        medium_name=medium_name,
                        sort_order=medium_index,
                    )
                )
            if medium_rows:
                HealthDashboardInstitutionServiceMedium.objects.bulk_create(medium_rows)


def backwards_populate_relational_health_data(apps, schema_editor):
    # Intentionally no-op: legacy fields/tables are still present for compatibility.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("health_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthDashboardCard",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tagline", models.CharField(blank=True, default="", max_length=255)),
                ("short_description", models.TextField(blank=True, default="")),
                ("accent_color_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card",
                        to="health_dashboard.healthdashboardinstitution",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_card",
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardInstitutionLandingPage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("hero_headline", models.CharField(blank=True, default="", max_length=255)),
                ("hero_subheadline", models.TextField(blank=True, default="")),
                ("hero_cta_label", models.CharField(blank=True, default="Book Appointment", max_length=120)),
                ("hero_cta_url", models.TextField(blank=True, default="")),
                ("logo_url", models.TextField(blank=True, default="")),
                ("background_image_url", models.TextField(blank=True, default="")),
                ("background_color_key", models.CharField(blank=True, default="", max_length=64)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_dashboard_landing_pages_created",
                        to="accounts.user",
                    ),
                ),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_page",
                        to="health_dashboard.healthdashboardinstitution",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_dashboard_landing_pages_updated",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_institution_landing_page",
                "indexes": [models.Index(fields=["dashboard", "is_published"], name="health_dash_dashboa_02326d_idx")],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardInstitutionService",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_uid", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("base_price_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_services",
                        to="health_dashboard.healthdashboardinstitution",
                    ),
                ),
                (
                    "source_broadcast_service",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_service",
                        to="broadcasts.broadcasthealthinstitutionservice",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_institution_service",
                "indexes": [
                    models.Index(fields=["dashboard", "sort_order"], name="health_dash_dashboa_03042c_idx"),
                    models.Index(fields=["dashboard", "active"], name="health_dash_dashboa_b2aa40_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dashboard", "service_uid"),
                        name="health_dashboard_institution_service_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardLandingPageAddress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_one", models.CharField(blank=True, default="", max_length=255)),
                ("line_two", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                ("postal_code", models.CharField(blank=True, default="", max_length=32)),
                ("country", models.CharField(blank=True, default="", max_length=120)),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "landing_page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="health_dashboard.healthdashboardinstitutionlandingpage",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_landing_page_address",
                "indexes": [
                    models.Index(fields=["city", "state", "country"], name="health_dash_city_ff8b07_idx"),
                    models.Index(fields=["country", "postal_code"], name="health_dash_country_8fa1b9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardLandingPageContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("primary_phone", models.CharField(blank=True, default="", max_length=64)),
                ("secondary_phone", models.CharField(blank=True, default="", max_length=64)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("website_url", models.TextField(blank=True, default="")),
                ("whatsapp_phone", models.CharField(blank=True, default="", max_length=64)),
                (
                    "landing_page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="health_dashboard.healthdashboardinstitutionlandingpage",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_landing_page_contact",
                "indexes": [
                    models.Index(fields=["primary_phone"], name="health_dash_primary_270e9e_idx"),
                    models.Index(fields=["email"], name="health_dash_email_d1bffb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardLandingPageImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.TextField()),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="health_dashboard.healthdashboardinstitutionlandingpage",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_landing_page_image",
                "indexes": [models.Index(fields=["landing_page", "sort_order"], name="health_dash_landing_30e6fd_idx")],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardLandingPageOperatingHour",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_key", models.CharField(max_length=16)),
                ("opens_at", models.CharField(blank=True, default="", max_length=16)),
                ("closes_at", models.CharField(blank=True, default="", max_length=16)),
                ("is_closed", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="health_dashboard.healthdashboardinstitutionlandingpage",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_landing_page_operating_hour",
                "indexes": [models.Index(fields=["landing_page", "sort_order"], name="health_dash_landing_51dd6a_idx")],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardLandingPageService",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("price_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "institution_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landing_page_entries",
                        to="health_dashboard.healthdashboardinstitutionservice",
                    ),
                ),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="health_dashboard.healthdashboardinstitutionlandingpage",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_landing_page_service",
                "indexes": [
                    models.Index(fields=["landing_page", "sort_order"], name="health_dash_landing_5e9161_idx"),
                    models.Index(fields=["landing_page", "is_active"], name="health_dash_landing_2a60a3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardLandingPageSocialLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(blank=True, default="", max_length=64)),
                ("url", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="health_dashboard.healthdashboardinstitutionlandingpage",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_landing_page_social_link",
                "indexes": [models.Index(fields=["landing_page", "sort_order"], name="health_dash_landing_f6d931_idx")],
            },
        ),
        migrations.CreateModel(
            name="HealthDashboardInstitutionServiceMedium",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medium_uid", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("medium_name", models.CharField(blank=True, default="", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medium_rows",
                        to="health_dashboard.healthdashboardinstitutionservice",
                    ),
                ),
            ],
            options={
                "db_table": "health_dashboard_institution_service_medium",
                "indexes": [models.Index(fields=["service", "sort_order"], name="health_dash_service_c8dd02_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "medium_uid", "medium_name"),
                        name="health_dashboard_service_medium_unique",
                    )
                ],
            },
        ),
        migrations.RunPython(
            code=forwards_populate_relational_health_data,
            reverse_code=backwards_populate_relational_health_data,
        ),
    ]
