# Generated by Codex on 2026-03-11

from django.db import migrations


BLOCKED_SERVICE_MEDIUM_NAMES = (
    "Emergency Dispatch Engine",
    "Home Logistics Engine",
    "Imaging Order Engine",
    "Lab Order Engine",
    "Surgery Scheduling Engine",
    "My test medium",
)


def _normalize_label(value):
    return " ".join(str(value or "").strip().lower().split())


def _clean_pairs(raw_ids, raw_names, blocked_ids):
    medium_ids = [str(value or "").strip() for value in (raw_ids or []) if str(value or "").strip()]
    medium_names = [str(value or "").strip() for value in (raw_names or []) if str(value or "").strip()]
    max_len = max(len(medium_ids), len(medium_names))
    had_mediums = max_len > 0
    removed_any = False
    pairs = []
    seen = set()
    blocked_name_set = {_normalize_label(value) for value in BLOCKED_SERVICE_MEDIUM_NAMES}

    for index in range(max_len):
        medium_id = medium_ids[index] if index < len(medium_ids) else ""
        medium_name = medium_names[index] if index < len(medium_names) else ""
        if not medium_id and not medium_name:
            continue
        if (medium_id and medium_id in blocked_ids) or _normalize_label(medium_name) in blocked_name_set:
            removed_any = True
            continue
        key = (medium_id, medium_name)
        if key in seen:
            continue
        seen.add(key)
        pairs.append(key)

    return pairs, had_mediums, removed_any


def cleanup_dashboard_unavailable_engines(apps, schema_editor):
    Medium = apps.get_model("broadcasts", "Medium")
    HealthDashboardInstitutionService = apps.get_model("health_dashboard", "HealthDashboardInstitutionService")
    HealthDashboardInstitutionServiceMedium = apps.get_model("health_dashboard", "HealthDashboardInstitutionServiceMedium")

    blocked_name_set = {_normalize_label(value) for value in BLOCKED_SERVICE_MEDIUM_NAMES}
    blocked_medium_ids = {
        str(medium.id)
        for medium in Medium.objects.all()
        if _normalize_label(getattr(medium, "name", "")) in blocked_name_set
    }

    for service in HealthDashboardInstitutionService.objects.all():
        medium_rows = list(
            HealthDashboardInstitutionServiceMedium.objects.filter(service=service).order_by("sort_order", "created_at")
        )
        pairs, had_mediums, removed_any = _clean_pairs(
            [row.medium_uid for row in medium_rows],
            [row.medium_name for row in medium_rows],
            blocked_medium_ids,
        )
        if had_mediums and removed_any and not pairs:
            service.delete()
            continue

        next_ids = [medium_id for medium_id, _medium_name in pairs if medium_id]
        next_names = [medium_name for _medium_id, medium_name in pairs if medium_name]
        current_ids = [str(row.medium_uid or "").strip() for row in medium_rows if str(row.medium_uid or "").strip()]
        current_names = [str(row.medium_name or "").strip() for row in medium_rows if str(row.medium_name or "").strip()]
        if next_ids == current_ids and next_names == current_names:
            continue

        HealthDashboardInstitutionServiceMedium.objects.filter(service=service).delete()
        for index, (medium_id, medium_name) in enumerate(pairs):
            HealthDashboardInstitutionServiceMedium.objects.create(
                service=service,
                medium_uid=medium_id,
                medium_name=medium_name,
                sort_order=index,
            )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("health_dashboard", "0003_landing_page_default_unpublished"),
        ("broadcasts", "0018_cleanup_unavailable_health_engines"),
    ]

    operations = [
        migrations.RunPython(cleanup_dashboard_unavailable_engines, noop_reverse),
    ]
