# Generated by Django 4.2.25 on 2026-01-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_advanced'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupban',
            new_name='group_ban_group_i_ecec29_idx',
            old_name='group_ban_group_i_8f2d9b_idx',
        ),
        migrations.RenameIndex(
            model_name='groupjoinrequest',
            new_name='group_join__group_i_eb8a3f_idx',
            old_name='group_join__group_i_8b3ee7_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_group_i_0d8860_idx',
            old_name='group_membe_group_i_8d7e25_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_user_id_9b3eba_idx',
            old_name='group_membe_user_i_b0e4b4_idx',
        ),
    ]
