# Generated by Django 4.2.25 on 2026-01-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_channel'),
        ('groups', '0003_rename_group_ban_group_i_8f2d9b_idx_group_ban_group_i_ecec29_idx_and_more'),
    ]

    operations = [
    ]
