# Generated by Django 5.2.8 on 2025-11-18 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_conversation_avatar_url_conversation_description_and_more'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Optional avatar/cover image URL for this community.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_conversation', models.OneToOneField(blank=True, help_text='Optional main conversation for this community (e.g. lobby).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_main', to='chat.conversation')),
                ('owner', models.ForeignKey(help_text='Primary owner of this community.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_communities', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Owning partner.', on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='partners.partner')),
            ],
            options={
                'db_table': 'community_community',
                'unique_together': {('partner', 'slug')},
            },
        ),
    ]
