# Generated by Django 5.2.8 on 2025-11-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Owning partner.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='partners.partner'),
        ),
    ]
