# Generated by Django 5.2.8 on 2025-11-18 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_avatar_url_conversation_description_and_more'),
        ('communities', '0002_alter_community_partner'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='community',
            name='posts_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='community',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='main_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_main', to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='community',
            table='kis_community',
        ),
    ]
