# Generated by Django 4.2.25 on 2026-01-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_advanced'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communityban',
            new_name='community_b_communi_5b27df_idx',
            old_name='community_ba_community_5dbd6d_idx',
        ),
        migrations.RenameIndex(
            model_name='communitycommentreaction',
            new_name='community_c_comment_e1368f_idx',
            old_name='community_co_comment__c3ad60_idx',
        ),
        migrations.RenameIndex(
            model_name='communityjoinrequest',
            new_name='community_j_communi_57761b_idx',
            old_name='community_jo_community_2f5c60_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymembership',
            new_name='community_m_communi_3aa8c5_idx',
            old_name='community_me_community_8f4fb0_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymembership',
            new_name='community_m_user_id_107bff_idx',
            old_name='community_me_user_97c8e5_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='community_p_communi_421ed6_idx',
            old_name='community_po_community_8bc2d1_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='community_p_communi_fc2720_idx',
            old_name='community_po_community_9b5a7e_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='community_p_communi_a10523_idx',
            old_name='community_po_community_0f83d7_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypostcomment',
            new_name='community_p_post_id_fe1b1b_idx',
            old_name='community_po_post_id_5a1864_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypostreaction',
            new_name='community_p_post_id_ef6402_idx',
            old_name='community_po_post_id_b8ad22_idx',
        ),
    ]
