# Generated by Django 4.2.25 on 2026-01-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_membership_group_access'),
        ('communities', '0005_rename_community_ba_community_5dbd6d_idx_community_b_communi_5b27df_idx_and_more'),
    ]

    operations = [
    ]
