# Generated by Django 4.2.25 on 2026-01-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_communitypost_rich_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='text',
            field=models.JSONField(blank=True, default=dict, help_text='ProseMirror-style document for the post content.'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='text_plain',
            field=models.TextField(blank=True, help_text='Plain text fallback (used for previews/search).'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='text_preview',
            field=models.CharField(blank=True, help_text='Short preview extracted from the rich document.', max_length=512),
        ),
    ]
