# Generated by Django 4.2.25 on 2026-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_community_broadcast_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='allow_join_link',
            field=models.BooleanField(default=True, help_text='If false, join links are disabled; joins must go through approval.'),
        ),
        migrations.AlterField(
            model_name='community',
            name='require_join_survey',
            field=models.BooleanField(default=False, help_text='When true, new joiners must complete a survey/workflow before being approved.'),
        ),
    ]
