# Generated by Django 4.2.25 on 2026-09-08 02:03

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    """
    Derive the new single-source-of-truth `status` from the existing
    left_at/is_banned columns for every pre-existing row. Historical rows
    have no way to distinguish a voluntary leave from an admin removal
    (both only ever set left_at before this migration), so both backfill
    to LEFT - REMOVED only starts getting used going forward, for rows
    created/updated after this migration via CommunityMembership.mark_removed().
    """
    CommunityMembership = apps.get_model("communities", "CommunityMembership")
    CommunityMembership.objects.filter(is_banned=True).update(status="banned")
    CommunityMembership.objects.filter(is_banned=False, left_at__isnull=False).update(status="left")
    CommunityMembership.objects.filter(is_banned=False, left_at__isnull=True).update(status="active")


def noop_reverse(apps, schema_editor):
    # Nothing to reverse - left_at/is_banned are untouched by this
    # migration in either direction, so there is no data loss on rollback,
    # only the (harmless) status column being dropped by RemoveField.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_community_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed'), ('banned', 'Banned')], db_index=True, default='active', help_text='Single source of truth for membership state - see CommunityMembershipStatus.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'status'], name='community_m_communi_651946_idx'),
        ),
        migrations.RunPython(backfill_status, noop_reverse),
    ]
