# Generated by Django 4.2.25 on 2026-01-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_shop_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productshare',
            name='platform',
        ),
        migrations.AddField(
            model_name='productsubscription',
            name='platform',
            field=models.CharField(default='kis-platform', max_length=64),
        ),
        migrations.AlterField(
            model_name='productsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
