# Generated by Django 4.2.25 on 2026-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_add_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('KISC', 'KISC')], default='KISC', max_length=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(choices=[('KISC', 'KISC')], default='KISC', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KISC', 'KISC')], default='KISC', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('KISC', 'KISC')], default='KISC', max_length=8),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('KISC', 'KISC')], default='KISC', max_length=8),
        ),
    ]
