# Generated by Django 4.2.25 on 2026-03-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_add_shop_membership_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='membership_public',
            field=models.BooleanField(default=False),
        ),
    ]
