# Generated by Django 4.2.25 on 2026-03-19 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_shopteammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopteammember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
