# Generated by Django 4.2.25 on 2026-03-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_shoplandingpage_shoplandingtestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='availability_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='coverage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='other_shops_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
