# Generated by Django 4.2.25 on 2026-03-20 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


def copy_service_products(apps, schema_editor):
    Product = apps.get_model('commerce', 'Product')
    ShopService = apps.get_model('commerce', 'ShopService')
    for product in Product.objects.filter(inventory_type='SERVICE'):
        ShopService.objects.create(
            id=product.id,
            created_at=product.created_at,
            updated_at=product.updated_at,
            is_deleted=product.is_deleted,
            shop_id=product.shop_id,
            name=product.name or '',
            slug=product.slug or f'service-{product.id}',
            description=product.description or '',
            price=product.price or 0,
            currency=product.currency or 'KISC',
            category_id=product.category_id,
            service_type=product.service_type or '',
            availability=product.availability or '',
            availability_rules=product.availability_rules or [],
            coverage=product.coverage or '',
            location=product.location or '',
            other_shops_discount=product.other_shops_discount,
            image_url=product.image_url or '',
            is_active=product.is_active,
            is_featured=product.is_featured,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_product_availability_product_availability_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('KISC', 'KISC')], default='KISC', max_length=8)),
                ('service_type', models.CharField(blank=True, default='', max_length=64)),
                ('availability', models.CharField(blank=True, default='', max_length=128)),
                ('availability_rules', models.JSONField(blank=True, default=list)),
                ('coverage', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('other_shops_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='commerce/services/')),
                ('image_url', models.URLField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='commerce.shopcategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commerce.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'name'], name='commerce_sh_shop_id_bdfd16_idx')],
                'unique_together': {('shop', 'slug')},
            },
        ),
        migrations.RunPython(copy_service_products, reverse_code=migrations.RunPython.noop),
    ]
