# Generated by Django 4.2.25 on 2026-03-20 07:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_shopservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopServiceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='commerce/service-images/')),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commerce.shopservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
