# Generated by Django 4.2.25 on 2026-03-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_shopserviceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopservice',
            name='location',
        ),
    ]
