# Generated by Django 4.2.25 on 2026-03-21 01:48

from django.db import migrations, models


def _fill_list_field(apps, schema_editor, field_name):
    ShopService = apps.get_model('commerce', 'ShopService')
    kwargs = {f"{field_name}__isnull": True}
    if schema_editor.connection.vendor != 'postgresql':
        return
    ShopService.objects.filter(**kwargs).update(**{field_name: []})


def _fill_addons(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'addons')


def _fill_delivery_modes(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'delivery_modes')


def _fill_packages(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'packages')


def _fill_remote_regions(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'remote_regions')


def _fill_requirements(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'requirements')


def _fill_tags(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'tags')


def _fill_blackout_dates(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'blackout_dates')


def _fill_coverage(apps, schema_editor):
    _fill_list_field(apps, schema_editor, 'coverage')


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_remove_shopservice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopservice',
            name='currency',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='addons',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='addons',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_addons, migrations.RunPython.noop),
        migrations.AddField(
            model_name='shopservice',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='auto_confirm_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='blackout_dates',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='blackout_dates',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_blackout_dates, migrations.RunPython.noop),
        migrations.AddField(
            model_name='shopservice',
            name='cancellation_window_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='cleanup_buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='delivery_modes',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='delivery_modes',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_delivery_modes, migrations.RunPython.noop),
        migrations.AddField(
            model_name='shopservice',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='deposit_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='group_booking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='max_advance_booking_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='max_bookings_per_slot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='max_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='min_notice_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='packages',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='packages',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_packages, migrations.RunPython.noop),
        migrations.AddField(
            model_name='shopservice',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='prep_buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='pricing_model',
            field=models.CharField(blank=True, default='standard', max_length=32),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='quote_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='refund_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='remote_regions',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='remote_regions',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_remote_regions, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='requirements',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='requirements',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_requirements, migrations.RunPython.noop),
        migrations.AddField(
            model_name='shopservice',
            name='reschedule_window_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='service_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='short_summary',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='staff_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='state',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused')], default='draft', max_length=16),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='tags',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='shopservice',
                    name='tags',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_tags, migrations.RunPython.noop),
        migrations.AddField(
            model_name='shopservice',
            name='tax_inclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='travel_radius_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='turnaround_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='warranty_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='shopservice',
                    name='coverage',
                    field=models.JSONField(blank=True, null=True),
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='shopservice',
                    name='coverage',
                    field=models.JSONField(blank=True, default=list, null=True),
                    preserve_default=False,
                )
            ],
        ),
        migrations.RunPython(_fill_coverage, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shopservice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='service_type',
            field=models.CharField(blank=True, default='Appointment', max_length=64),
        ),
    ]
