# Generated by Django 4.2.25 on 2026-03-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_remove_shopservice_currency_shopservice_addons_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shopservice',
            index=models.Index(fields=['status'], name='commerce_sh_status_d0e663_idx'),
        ),
        migrations.AddIndex(
            model_name='shopservice',
            index=models.Index(fields=['visibility'], name='commerce_sh_visibil_c8300c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopservice',
            index=models.Index(fields=['shop'], name='commerce_sh_shop_id_5f05dc_idx'),
        ),
        migrations.AddIndex(
            model_name='shopservice',
            index=models.Index(fields=['price'], name='commerce_sh_price_ffd12c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopservice',
            index=models.Index(fields=['published_at'], name='commerce_sh_publish_b32f11_idx'),
        ),
    ]
