# Generated by Django 4.2.25 on 2026-03-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_servicerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopservice',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='blackout_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='coverage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='delivery_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='remote_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
