# Generated by Django 4.2.25 on 2026-03-21 06:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_servicerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopservice',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='blackout_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='coverage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='delivery_modes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='remote_regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
    ]
