# Generated by Django 4.2.25 on 2026-03-22 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0024_alter_shopservice_addons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('price_cents', models.BigIntegerField(default=0)),
                ('deposit_cents', models.BigIntegerField(default=0)),
                ('balance_cents', models.BigIntegerField(default=0)),
                ('instructions', models.TextField(blank=True, default='')),
                ('payment_tx_ref', models.CharField(blank=True, default='', max_length=128)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='commerce.shopservice')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='commerce.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['service', 'scheduled_at'], name='commerce_se_service_069189_idx'), models.Index(fields=['user', 'status'], name='commerce_se_user_id_da6b58_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='servicebooking',
            constraint=models.UniqueConstraint(fields=('service', 'scheduled_at'), name='unique_service_schedule'),
        ),
    ]
