# Generated by Django 4.2.25 on 2026-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_servicebooking_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicebooking',
            name='unique_service_schedule',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='remote_meeting_link',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='remote_meeting_link',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
