# Generated by Django 4.2.25 on 2026-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_booking_escrow_and_complaints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicebookingcomplaint',
            new_name='commerce_se_status_4c1f93_idx',
            old_name='commerce_sc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebookingcomplaint',
            new_name='commerce_se_action_e8b937_idx',
            old_name='commerce_sc_action_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebookingcomplaint',
            new_name='commerce_se_created_10c580_idx',
            old_name='commerce_sc_created_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebookingescrow',
            new_name='commerce_se_status_298906_idx',
            old_name='commerce_se_status_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebookingescrow',
            new_name='commerce_se_locked__c41bef_idx',
            old_name='commerce_se_locked_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebookingescrow',
            new_name='commerce_se_release_232dde_idx',
            old_name='commerce_se_released_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebookingescrow',
            new_name='commerce_se_refunde_9a5676_idx',
            old_name='commerce_se_refunded_idx',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('awaiting_satisfaction', 'Awaiting satisfaction'), ('dispute', 'Dispute'), ('refunded', 'Refunded')], default='pending', max_length=32),
        ),
    ]
