# Generated by Django 4.2.25 on 2026-03-23 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_rename_commerce_sc_status_idx_commerce_se_status_4c1f93_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='KISC', max_length=12)),
                ('payment_method', models.CharField(blank=True, default='wallet', max_length=64)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('satisfied', 'Satisfied')], default='pending', max_length=32)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='commerce.servicebooking')),
            ],
            options={
                'indexes': [models.Index(fields=['payment_status'], name='commerce_se_payment_9646f4_idx'), models.Index(fields=['paid_at'], name='commerce_se_paid_at_db0451_idx'), models.Index(fields=['satisfied_at'], name='commerce_se_satisfi_7d1614_idx')],
            },
        ),
    ]
