# Generated by Django 4.2.25 on 2026-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_add_payment_to_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebookingcomplaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('resolved_release_provider', 'Resolved • Release payment'), ('resolved_refund_customer', 'Resolved • Refund customer'), ('rejected', 'Rejected')], default='submitted', max_length=32),
        ),
    ]
