# Generated by Django 4.2.25 on 2026-03-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_add_servicebooking_metadata'),
        ('commerce', '0033_alter_servicebookingcomplaint_status'),
    ]

    operations = [
    ]
