# Generated by Django 4.2.25 on 2026-03-29 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0034_merge_20260329_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookingReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='KISC', max_length=12)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=128)),
                ('phase', models.CharField(choices=[('deposit', 'Deposit payment'), ('remaining', 'Remaining payment')], default='deposit', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='commerce.servicebooking')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'phase'], name='commerce_se_booking_0b5cbe_idx'), models.Index(fields=['transaction_reference'], name='commerce_se_transac_7145de_idx')],
            },
        ),
    ]
