# Generated by Django 4.2.25 on 2026-03-31 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0037_cart_cartitem_cart_commerce_ca_user_id_d347c3_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, default='', max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=64)),
                ('sku', models.CharField(blank=True, default='', max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_qty', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='commerce.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='commerce_variant_product_idx'), models.Index(fields=['sku'], name='commerce_variant_sku_idx')],
            },
        ),
    ]
