# Generated by Django 4.2.25 on 2026-04-08 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0042_remove_shop_category_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='category_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=16),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
