# Generated by Django 4.2.25 on 2026-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0043_remove_shopservice_commerce_sh_categor_8518c5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allow_backorder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ar_preview_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='authenticity_proof',
        ),
        migrations.RemoveField(
            model_name='product',
            name='authenticity_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability_rules',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_shops_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_avg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_guide',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='commerce/products/main/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='KISC', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original retail price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted selling price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='commerce_pr_shop_id_198eee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['inventory_type'], name='commerce_pr_invento_dde468_idx'),
        ),
    ]
