# Generated by Django 4.2.25 on 2026-04-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0044_alter_product_options_remove_product_ai_score_and_more'),
        ('commerce', '0044_productimage_alt_text'),
    ]

    operations = [
    ]
