# Generated by Django 4.2.25 on 2026-04-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0045_merge_20260409_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
    ]
