# Generated by Django 4.2.25 on 2026-04-09 14:31

from django.db import migrations, models
from django.db.models import Count


def dedupe_cart_items(apps, schema_editor):
    CartItem = apps.get_model('commerce', 'CartItem')
    duplicates = (
        CartItem.objects.values('cart_id', 'product_id', 'variant')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for entry in duplicates:
        items = list(
            CartItem.objects.filter(
                cart_id=entry['cart_id'],
                product_id=entry['product_id'],
                variant=entry['variant'],
            ).order_by('created_at')
        )
        for duplicate in items[1:]:
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0052_cartitem_custom_metadata'),
    ]

    operations = [
        migrations.RunPython(dedupe_cart_items, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
