# Generated by Django 4.2.25 on 2026-04-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0053_cartitem_color_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attribute_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
