# Generated by Django 4.2.25 on 2026-04-09 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_alter_walletledgerentry_kind'),
        ('commerce', '0055_marketplace_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='commerce/complaints/')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered_at',
            new_name='escrow_expires_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='variant',
            new_name='metadata',
        ),
        migrations.RenameIndex(
            model_name='marketplacecomplaint',
            new_name='commerce_ma_order_i_1970c1_idx',
            old_name='commerce_marketplacecomplaint_order_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceorder',
            new_name='commerce_ma_buyer_i_fdd978_idx',
            old_name='commerce_marketplaceorder_buyer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceorder',
            new_name='commerce_ma_shop_id_262f65_idx',
            old_name='commerce_marketplaceorder_shop_status_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceorderitem',
            new_name='commerce_ma_order_i_cf54da_idx',
            old_name='commerce_marketorderitem_order_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fraud_score',
        ),
        migrations.AddField(
            model_name='order',
            name='is_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_orders', to='billing.wallettransaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.wallettransaction'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_payments', to='commerce.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer debit'), ('provider', 'Provider payout'), ('escrow_release', 'Escrow release')], default='buyer', max_length=32),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='currency',
            field=models.CharField(default='KISC', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='KISC', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('escrow', 'Escrow'), ('cancelled', 'Cancelled'), ('satisfied', 'Satisfied'), ('completed', 'Completed')], default='temporal', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('escrow', 'Escrow'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product', 'variant_id')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='commerce_or_status_ab9590_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='commerce_or_user_id_ba7ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop'], name='commerce_or_shop_id_1f8e04_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='commerce_or_product_317f80_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='commerce_pa_order_i_4ff196_idx'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='commerce.order'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='applied_discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['order', 'user'], name='commerce_co_order_i_a29545_idx'),
        ),
    ]
