# Generated by Django 4.2.25 on 2026-04-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0058_shoplandingpage_builder_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('cancelled', 'Cancelled'), ('awaiting_satisfaction', 'Awaiting satisfaction'), ('satisfied', 'Satisfied'), ('completed', 'Completed'), ('complaint', 'Complaint')], default='temporal', max_length=32),
        ),
    ]
