# Generated by Django 4.2.25 on 2026-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0059_alter_marketplaceorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='currency',
            field=models.CharField(default='USD', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='servicebookingpayment',
            name='currency',
            field=models.CharField(default='USD', max_length=12),
        ),
        migrations.AlterField(
            model_name='servicebookingreceipt',
            name='currency',
            field=models.CharField(default='USD', max_length=12),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=8),
        ),
    ]
