# Generated by Django 4.2.25 on 2026-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0063_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingspace',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN'), ('GHS', 'GHS'), ('KES', 'KES'), ('ZAR', 'ZAR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='crowdfundcampaign',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN'), ('GHS', 'GHS'), ('KES', 'KES'), ('ZAR', 'ZAR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN'), ('GHS', 'GHS'), ('KES', 'KES'), ('ZAR', 'ZAR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='savingsgroup',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN'), ('GHS', 'GHS'), ('KES', 'KES'), ('ZAR', 'ZAR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='USD', max_length=3),
        ),
    ]
