# Generated by Django 4.2.25 on 2026-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0064_currency_choices_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacecomplaint',
            name='attachment',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='commerce/marketplace/complaints/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='commerce/products/main/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(max_length=1024, upload_to='commerce/products/gallery/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image_file',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='commerce/shops/'),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='image_file',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='commerce/services/'),
        ),
        migrations.AlterField(
            model_name='shopserviceimage',
            name='image_file',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='commerce/service-images/'),
        ),
    ]
