# Generated by Django 4.2.25 on 2026-08-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0042_partnerorganizationlink_and_more'),
        ('commerce', '0067_shop_stripe_account_id_shop_stripe_charges_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='partners.partner'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['partner'], name='commerce_sh_partner_5c6d91_idx'),
        ),
    ]
