# Generated by Django 4.2.25 on 2026-10-02 11:14

import apps.commerce.shipping_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0069_add_saved_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('ready_for_shipment', 'Ready for shipment'), ('partially_shipped', 'Partially shipped'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=24)),
                ('shipping_cost_cents', models.PositiveIntegerField(default=0)),
                ('delivery_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('estimated_delivery_min', models.DateField(blank=True, null=True)),
                ('estimated_delivery_max', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='commerce.marketplaceorder')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference', models.CharField(default=apps.commerce.shipping_models._generate_shipment_reference, max_length=32, unique=True)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=128)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('label_created', 'Label created'), ('ready_for_pickup', 'Ready for pickup'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('origin_snapshot', models.JSONField(blank=True, default=dict)),
                ('destination_snapshot', models.JSONField(blank=True, default=dict)),
                ('shipping_cost_cents', models.PositiveIntegerField(default=0)),
                ('estimated_delivery_min', models.DateField(blank=True, null=True)),
                ('estimated_delivery_max', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='commerce.fulfillment')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('method_type', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('same_day', 'Same-Day Delivery'), ('pickup', 'Pickup'), ('seller_delivery', 'Seller Delivery'), ('carrier', 'Carrier Delivery')], default='standard', max_length=20)),
                ('provider_code', models.CharField(default='manual', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('min_days', models.PositiveIntegerField(default=1)),
                ('max_days', models.PositiveIntegerField(default=3)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='commerce.shop')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2. Required - every zone matches within one country.', max_length=2)),
                ('state', models.CharField(blank=True, default='', help_text='Blank = any state/province in this country.', max_length=128)),
                ('city', models.CharField(blank=True, default='', help_text='Blank = any city in this state.', max_length=128)),
                ('postal_code_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Tie-break only, used when two zones match with equal specificity.')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='commerce.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat rate'), ('free', 'Free shipping'), ('threshold', 'Free above a subtotal threshold'), ('quantity', 'Per-item rate'), ('weight', 'Weight-based rate')], default='flat', max_length=20)),
                ('base_cents', models.PositiveIntegerField(default=0, help_text='Flat price / per-item price / per-kg price, depending on rate_type.')),
                ('free_above_cents', models.PositiveIntegerField(blank=True, help_text='THRESHOLD only: order subtotal (pre-shipping) at or above which shipping is free.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='commerce.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='commerce.shippingzone')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='commerce.marketplaceorderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('label_created', 'Label created'), ('ready_for_pickup', 'Ready for pickup'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=24)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('carrier_webhook', 'Carrier webhook')], default='manual', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_event_id', models.CharField(blank=True, default='', help_text='Carrier-provided event id, for webhook replay idempotency.', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commerce.shipment')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='commerce.shippingmethod'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='commerce.shippingmethod'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='commerce.shippingzone'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='commerce.shop'),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=32)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. NG, US, CM', max_length=2)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_instructions', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='shippingzone',
            index=models.Index(fields=['shop', 'country', 'is_active'], name='commerce_sh_shop_id_9497a9_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingzone',
            index=models.Index(fields=['shop', 'is_active'], name='commerce_sh_shop_id_ffc911_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['method', 'zone', 'is_active'], name='commerce_sh_method__9b8107_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('method', 'zone')},
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['shop', 'is_active'], name='commerce_sh_shop_id_b953bb_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['order_item'], name='commerce_sh_order_i_27f1c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'occurred_at'], name='commerce_sh_shipmen_2601f3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['fulfillment', 'status'], name='commerce_sh_fulfill_f6fae4_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['shop', 'status'], name='commerce_fu_shop_id_8c476e_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['user', 'is_default'], name='commerce_cu_user_id_350ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['user', 'is_deleted'], name='commerce_cu_user_id_d26de5_idx'),
        ),
    ]
