# Generated by Django 4.2.25 on 2026-10-02 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0070_add_shipping_fulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='seller_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productreview',
            name='seller_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='seller_response_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_product_review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductReviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('offensive', 'Offensive content'), ('fake', 'Suspected fake review'), ('irrelevant', 'Not about this product'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_review_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='commerce.productreview')),
            ],
            options={
                'indexes': [models.Index(fields=['review'], name='commerce_pr_review__03b8bb_idx')],
                'unique_together': {('review', 'reporter')},
            },
        ),
    ]
