# Generated by Django 4.2.25 on 2026-10-02 22:49

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0071_add_review_verification_response_reporting'),
    ]

    operations = [
        # Must run before the GIN index below - gin_trgm_ops only exists
        # once this extension is enabled.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='commerce_product_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
