# Generated by Django 4.2.25 on 2026-10-05 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0075_add_complaint_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cover_url', models.URLField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='drops', to='commerce.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='commerce.shop')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['shop', 'starts_at'], name='commerce_ma_shop_id_75b64a_idx'), models.Index(fields=['starts_at', 'ends_at'], name='commerce_ma_starts__3b19f7_idx')],
            },
        ),
    ]
