# Generated by Django 4.2.25 on 2026-01-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statusitem',
            new_name='statuses_st_user_id_ba9de4_idx',
            old_name='statuses_st_user_i_4ef6f1_idx',
        ),
        migrations.RenameIndex(
            model_name='statusitem',
            new_name='statuses_st_user_id_406c54_idx',
            old_name='statuses_st_user_i_2703c8_idx',
        ),
    ]
