# Generated by Django 4.2.25 on 2026-01-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_statuses_st_user_i_4ef6f1_idx_statuses_st_user_id_ba9de4_idx_and_more'),
        ('statuses', '0002_statusitem_style'),
    ]

    operations = [
    ]
