# Generated by Django 4.2.25 on 2026-01-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_statusitem_view'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statusitemview',
            new_name='statuses_st_status__9bf5c8_idx',
            old_name='statuses_st_status__8c4b0c_idx',
        ),
        migrations.RenameIndex(
            model_name='statusitemview',
            new_name='statuses_st_user_id_c4b3bb_idx',
            old_name='statuses_st_user_i_8fd571_idx',
        ),
    ]
