# Generated by Django 4.2.25 on 2026-04-24 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0005_rename_statuses_st_status__8c4b0c_idx_statuses_st_status__9bf5c8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusitem',
            name='reply_permission',
            field=models.CharField(choices=[('contacts', 'Contacts'), ('nobody', 'Nobody')], default='contacts', max_length=16),
        ),
        migrations.AddField(
            model_name='statusitem',
            name='visibility',
            field=models.CharField(choices=[('contacts', 'My contacts'), ('contacts_except', 'My contacts except'), ('only_share_with', 'Only share with')], db_index=True, default='contacts', max_length=32),
        ),
        migrations.CreateModel(
            name='StatusAudienceTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_targets', to='statuses.statusitem')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_audience_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('muted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_in_statuses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'muted_user'], name='statuses_st_user_id_71aa0b_idx'), models.Index(fields=['user', 'created_at'], name='statuses_st_user_id_fa98fb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='statusmute',
            constraint=models.UniqueConstraint(fields=('user', 'muted_user'), name='status_mute_unique'),
        ),
        migrations.AddIndex(
            model_name='statusaudiencetarget',
            index=models.Index(fields=['status', 'target_user'], name='statuses_st_status__7f3060_idx'),
        ),
        migrations.AddIndex(
            model_name='statusaudiencetarget',
            index=models.Index(fields=['target_user', 'created_at'], name='statuses_st_target__7714db_idx'),
        ),
        migrations.AddConstraint(
            model_name='statusaudiencetarget',
            constraint=models.UniqueConstraint(fields=('status', 'target_user'), name='status_audience_target_unique'),
        ),
    ]
