# Generated by Django 4.2.25 on 2026-09-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0006_statusitem_reply_permission_statusitem_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusitem',
            name='moderation_status',
            field=models.CharField(choices=[('passed', 'Passed'), ('pending_review', 'Pending review'), ('blocked', 'Blocked')], db_index=True, default='passed', help_text='Content-safety gate — see StatusModerationStatus and can_view_status().', max_length=16),
        ),
    ]
