# Generated by Django 4.2.25 on 2026-09-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0007_statusitem_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusitem',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='statusitem',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('document', 'Document')], max_length=16),
        ),
    ]
