# Generated by Django 4.2.25 on 2026-09-10 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0008_statusitem_original_filename_alter_statusitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='statuses.statusitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'user'], name='statuses_st_status__a2909b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='statusreaction',
            constraint=models.UniqueConstraint(fields=('status', 'user'), name='status_item_unique_reaction'),
        ),
    ]
