# Generated by Django 4.2.25 on 2026-08-13 01:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('coin_amount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedemptionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('context', models.CharField(default='subscription_upgrade', max_length=64, unique=True)),
                ('normal_max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('absolute_max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('min_cash_contribution_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('coin_value_cents', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeatableRewardRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('coin_amount', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_event', 'Per event')], max_length=16)),
                ('max_per_period', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RewardLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(choices=[('achievement', 'Achievement'), ('repeatable', 'Repeatable'), ('referral', 'Referral'), ('promo', 'Promo'), ('redemption', 'Redemption'), ('admin_adjustment', 'Admin adjustment'), ('reversal', 'Reversal'), ('expiration', 'Expiration')], db_index=True, max_length=32)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('redeemed', 'Redeemed'), ('reversed', 'Reversed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('reference_type', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='rewards.rewardledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='rewards_rew_user_id_538648_idx'), models.Index(fields=['user', 'type', 'status'], name='rewards_rew_user_id_3571da_idx'), models.Index(fields=['status', 'expires_at'], name='rewards_rew_status_0c4c7f_idx'), models.Index(fields=['reference_type', 'reference_id'], name='rewards_rew_referen_81da06_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rewardledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uniq_reward_ledger_idempotency_key'),
        ),
    ]
