# Generated by Django 5.2.8 on 2025-12-13 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundRemovalJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('original_image', models.ImageField(upload_to='bg_removal/originals/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='bg_removal/processed/')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
