# Generated by Django 4.2.25 on 2025-10-12 13:17

import apps.surveys.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('vote_type', django_enumfield.db.fields.EnumField(enum=apps.surveys.models.VoteType)),
                ('options', models.JSONField(default=list)),
                ('required', models.BooleanField(default=True)),
                ('ai_score', models.FloatField(default=0.0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('answer', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('social_impact_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('org_id', models.UUIDField(blank=True, null=True)),
                ('group_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', django_enumfield.db.fields.EnumField(enum=apps.surveys.models.SurveyType)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('reward_points', models.IntegerField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('visibility', django_enumfield.db.fields.EnumField(default=0, enum=apps.surveys.models.Visibility)),
                ('ai_score', models.FloatField(default=0.0)),
                ('popularity_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shared_by_id', models.UUIDField()),
                ('platform', models.CharField(max_length=64)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='surveys.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_responses', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('average_time', models.FloatField(default=0.0)),
                ('top_choices', models.JSONField(default=dict)),
                ('demographic_breakdown', models.JSONField(default=dict)),
                ('trend_score', models.FloatField(default=0.0)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['owner_id'], name='surveys_sur_owner_i_6e0624_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['org_id'], name='surveys_sur_org_id_eb937c_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['-created_at'], name='surveys_sur_created_d3765d_idx'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.question'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['survey', 'question'], name='surveys_res_survey__2bf0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['user_id'], name='surveys_res_user_id_859e54_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['survey', 'order'], name='surveys_que_survey__d73192_idx'),
        ),
    ]
