# Generated by Django 4.2.25 on 2026-08-19 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('shop', 'Shop'), ('health_institution', 'Health Institution'), ('education_institution', 'Education Institution'), ('partner', 'Partner'), ('broadcast_channel', 'Broadcast Channel')], db_index=True, max_length=32)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('default_seo', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('seeded_from_legacy', models.BooleanField(default=False)),
                ('seeded_from_legacy_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website',
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=140)),
                ('title', models.CharField(max_length=255)),
                ('is_home', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_pages_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_pages_updated', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='websites.website')),
            ],
            options={
                'db_table': 'website_page',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['website', 'status'], name='website_pag_website_0a50b7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='websitepage',
            constraint=models.UniqueConstraint(fields=('website', 'slug'), name='website_page_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='websitepage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_home', True)), fields=('website',), name='website_one_home_page'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['owner_type', 'owner_id'], name='website_owner_t_3bbafd_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['status'], name='website_status_4c379e_idx'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('owner_type', 'owner_id'), name='website_unique_owner'),
        ),
    ]
