# Generated by Django 4.2.25 on 2026-08-19 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_id', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('spam_score', models.FloatField(default=0.0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='websites.websitepage')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='websites.website')),
            ],
            options={
                'db_table': 'website_form_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['website', 'created_at'], name='website_for_website_50fb11_idx'), models.Index(fields=['page', 'section_id'], name='website_for_page_id_f7fbe0_idx')],
            },
        ),
    ]
