# Generated by Django 4.2.25 on 2026-08-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0002_websiteformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('form_submitted', 'Form Submitted')], max_length=32)),
                ('target_url', models.URLField(max_length=500)),
                ('secret', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_webhooks_created', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='websites.website')),
            ],
            options={
                'db_table': 'website_webhook',
                'indexes': [models.Index(fields=['website', 'event_type', 'is_active'], name='website_web_website_faf735_idx')],
            },
        ),
    ]
