# Generated by Django 4.2.25 on 2026-08-19 11:28

import apps.websites.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0003_websitewebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.websites.models.generate_website_invite_code, max_length=32, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor')], default='editor', max_length=16)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_invites_created', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='websites.website')),
            ],
            options={
                'db_table': 'website_invite',
                'indexes': [models.Index(fields=['website', 'is_active'], name='website_inv_website_9d10f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor')], default='editor', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_collaborators_invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_collaborations', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='websites.website')),
            ],
            options={
                'db_table': 'website_collaborator',
                'indexes': [models.Index(fields=['website', 'is_active'], name='website_col_website_b9c210_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='websitecollaborator',
            constraint=models.UniqueConstraint(fields=('website', 'user'), name='website_collaborator_unique_user'),
        ),
    ]
