# Generated by Django 4.2.25 on 2026-08-19 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_websiteinvite_websitecollaborator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('referrer_host', models.CharField(blank=True, default='', max_length=255)),
                ('session_hash', models.CharField(db_index=True, max_length=64)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='websites.websitepage')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='websites.website')),
            ],
            options={
                'db_table': 'website_analytics_event',
                'indexes': [models.Index(fields=['website', 'created_at'], name='website_ana_website_dc9f88_idx'), models.Index(fields=['website', 'page', 'created_at'], name='website_ana_website_30a4b5_idx')],
            },
        ),
    ]
