# Generated by Django 4.2.25 on 2026-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_websiteanalyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='website',
            name='custom_domain_cloudflare_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='website',
            name='custom_domain_status',
            field=models.CharField(choices=[('none', 'Not configured'), ('pending', 'Pending verification'), ('active', 'Active'), ('failed', 'Failed')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='website',
            name='custom_domain_txt_record',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
