# Generated by Django 4.2.25 on 2026-08-19 12:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_website_custom_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('shop', 'Shop'), ('health_institution', 'Health Institution'), ('education_institution', 'Education Institution'), ('partner', 'Partner'), ('broadcast_channel', 'Broadcast Channel')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('seed_pages', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_template',
                'ordering': ['owner_type', 'name'],
                'indexes': [models.Index(fields=['owner_type', 'is_active'], name='website_tem_owner_t_72220b_idx')],
            },
        ),
    ]
