# Generated by Django 4.2.25 on 2026-08-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_seed_more_website_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteanalyticsevent',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
