# Generated by Django 4.2.25 on 2026-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'register'), ('login', 'login'), ('reset', 'reset')], max_length=16),
        ),
    ]
