# Generated by Django 4.2.25 on 2026-08-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_phoneotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'register'), ('login', 'login'), ('reset', 'reset'), ('email_verify', 'email_verify')], max_length=16),
        ),
    ]
