"""Tests for common/media_urls.py's presigned-URL self-healing fix.

Regression coverage for a real, reproduced production bug: a value
resolved for temporary display (a presigned S3 GET URL, generated by
apps.broadcasts.serializers.EducationInstitutionSerializer.to_representation
and equivalents for the whole Education academic hierarchy — Program,
Course, Lesson, ClassSession, Material, Assessment, Event, Broadcast, all
sharing this same strip_backend_origin/normalize_media_reference call)
was being round-tripped by an edit form's unmodified save back into
storage, permanently replacing the stable object key with a frozen URL
that stopped working the moment its signature expired. Confirmed in
production: EducationInstitution "Kingdom Impact Tech Academy"'s
branding.logo_url/logoUrl held a signed URL with X-Amz-Expires=3600,
over 7 hours past expiry.
"""
from __future__ import annotations

from django.test import SimpleTestCase

from common.media_urls import strip_backend_origin


class PresignedUrlSelfHealingTests(SimpleTestCase):
    def test_presigned_path_style_s3_url_is_reduced_to_its_object_key(self):
        # Path-style — https://s3.<region>.amazonaws.com/<bucket>/<key> —
        # is what apps.media.storage_backends' boto3 client actually
        # generates in production (confirmed against the real corrupted
        # value found for Kingdom Impact Tech Academy). The bucket name
        # is the FIRST path segment here, not part of the object key.
        signed_url = (
            "https://s3.eu-west-2.amazonaws.com/kis-production-media-prod-387362988707-eu-west-2-an/"
            "private/education/logo/user123/abc.jpg"
            "?X-Amz-Algorithm=AWS4-HMAC-SHA256"
            "&X-Amz-Credential=AKIA%2F20260821%2Feu-west-2%2Fs3%2Faws4_request"
            "&X-Amz-Date=20260821T193803Z"
            "&X-Amz-Expires=3600"
            "&X-Amz-SignedHeaders=host"
            "&X-Amz-Signature=deadbeef"
        )
        result = strip_backend_origin(signed_url)
        self.assertEqual(result, "private/education/logo/user123/abc.jpg")
        # The whole point: no query string (signature/expiry) survives —
        # a raw object key never expires. And no bucket name leaks in.
        self.assertNotIn("X-Amz", result)
        self.assertNotIn("?", result)
        self.assertNotIn("kis-production-media", result)

    def test_presigned_virtual_hosted_style_s3_url_is_reduced_to_its_object_key(self):
        # Virtual-hosted-style — https://<bucket>.s3.<region>.amazonaws.com/<key>
        # — the whole path already IS the key, no bucket segment to strip.
        signed_url = (
            "https://kis-production-media.s3.eu-west-2.amazonaws.com/"
            "private/education/logo/user123/abc.jpg?X-Amz-Signature=deadbeef"
        )
        result = strip_backend_origin(signed_url)
        self.assertEqual(result, "private/education/logo/user123/abc.jpg")

    def test_already_raw_object_key_is_unchanged(self):
        raw_key = "private/education/logo/user123/abc.jpg"
        self.assertEqual(strip_backend_origin(raw_key), raw_key)

    def test_external_url_without_signature_marker_is_left_alone(self):
        # Only the X-Amz-Signature marker triggers self-healing — an
        # arbitrary external image URL a seller might legitimately paste
        # in must not be mangled.
        external = "https://example.com/photos/logo.png?size=large"
        self.assertEqual(strip_backend_origin(external), external)

    def test_non_s3_query_string_containing_similar_looking_params_is_untouched(self):
        almost = "https://example.com/img.jpg?X-Amz-Something=not-a-signature"
        self.assertEqual(strip_backend_origin(almost), almost)

    def test_empty_value_returns_empty_string(self):
        self.assertEqual(strip_backend_origin(""), "")
        self.assertEqual(strip_backend_origin(None), "")

    def test_presigned_url_without_leading_slash_in_path(self):
        # A bucket path-style URL with no object-key leading slash should
        # still normalize to a key with no leading slash, matching the
        # existing stored convention (confirmed in production data: keys
        # are stored as "private/..." not "/private/...").
        signed_url = "https://bucket.s3.amazonaws.com/a/b/c.jpg?X-Amz-Signature=xyz"
        self.assertEqual(strip_backend_origin(signed_url), "a/b/c.jpg")
