# Generated by Django 4.2.25 on 2026-02-04 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedAffinityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_score', models.FloatField(default=0.0)),
                ('community_score', models.FloatField(default=0.0)),
                ('partner_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed_affinity_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_affinity_profile',
            },
        ),
        migrations.CreateModel(
            name='FeedInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=32)),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_interaction',
                'indexes': [models.Index(fields=['user', 'feed_type', 'created_at'], name='feed_intera_user_id_d3d0ad_idx')],
            },
        ),
    ]
