# Generated by Django 4.2.25 on 2025-10-11 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('three_d', '3D')], max_length=32)),
                ('bucket_key', models.CharField(max_length=1024)),
                ('canonical_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=256)),
                ('bytes', models.BigIntegerField(default=0)),
                ('dims', models.CharField(blank=True, help_text='WxH or duration', max_length=128)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(db_index=True, default='pending', max_length=64)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('storage', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(default='invisible', max_length=32)),
                ('proof', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermarks', to='media.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('origin_hash', models.CharField(max_length=256)),
                ('anchor', models.JSONField(blank=True, default=dict)),
                ('version_log', models.JSONField(blank=True, default=list)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_detail', to='media.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('pipeline', models.CharField(choices=[('transcode', 'Transcode'), ('phash', 'PerceptualHash'), ('watermark', 'Watermark'), ('analyze', 'Analyze'), ('redact', 'Redact')], max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32)),
                ('priority', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('worker_meta', models.JSONField(blank=True, default=dict)),
                ('result_meta', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='media.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('views', models.BigIntegerField(default=0)),
                ('stream_minutes', models.BigIntegerField(default=0)),
                ('downloads', models.BigIntegerField(default=0)),
                ('reaction_summary', models.JSONField(blank=True, default=dict)),
                ('carbon_grams', models.FloatField(default=0.0)),
                ('cost_cents', models.BigIntegerField(default=0)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='media.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('drm', models.JSONField(blank=True, default=dict)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy', to='media.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('purpose', models.CharField(max_length=64)),
                ('codec', models.CharField(blank=True, max_length=128)),
                ('dims', models.CharField(blank=True, max_length=128)),
                ('bytes', models.BigIntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('variant_meta', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media.mediaasset')),
            ],
            options={
                'unique_together': {('asset', 'purpose', 'codec')},
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['type', 'status'], name='media_media_type_acfd40_idx'),
        ),
    ]
