# Generated by Django 4.2.25 on 2026-05-14 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSafetyScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('upload_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('context', models.CharField(db_index=True, default='general', max_length=64)),
                ('original_name', models.CharField(blank=True, max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=256)),
                ('bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('provider', models.CharField(db_index=True, default='stub', max_length=64)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('passed', 'Passed'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('not_configured', 'Not Configured')], db_index=True, default='pending_review', max_length=32)),
                ('quarantine', models.BooleanField(db_index=True, default=True)),
                ('requires_review', models.BooleanField(db_index=True, default=True)),
                ('policy_version', models.CharField(default='kis-christian-safety-v1', max_length=64)),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_scans', to='media.mediaasset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_safety_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['context', 'status'], name='media_media_context_7a15ea_idx'), models.Index(fields=['owner', 'status'], name='media_media_owner_i_295025_idx'), models.Index(fields=['upload_id', 'status'], name='media_media_upload__bb48cf_idx')],
            },
        ),
    ]
