# Generated by Django 4.2.25 on 2026-07-16 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_mediasafetyscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('context', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('object_key', models.CharField(max_length=1024)),
                ('content_type', models.CharField(max_length=256)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired'), ('aborted', 'Aborted')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_upload_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status'], name='media_media_owner_i_efcb62_idx'), models.Index(fields=['status', 'expires_at'], name='media_media_status_c7f60f_idx'), models.Index(fields=['context', 'status'], name='media_media_context_a15315_idx')],
            },
        ),
    ]
