# Generated by Django 4.2.25 on 2026-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediauploadintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediauploadintent',
            name='attached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
