# Generated by Django 4.2.25 on 2026-09-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_canonical_media_asset_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasafetyscan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediasafetyscan',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mediasafetyscan',
            index=models.Index(fields=['status', 'scheduled_deletion_at', 'deleted_at'], name='media_media_status_1dbfcc_idx'),
        ),
    ]
