# Generated by Django 4.2.25 on 2026-06-09 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0041_job_detail_fields'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partnerlocationattendance',
            name='unique_attendance_per_event',
        ),
        migrations.RemoveConstraint(
            model_name='partnerlocationconsent',
            name='unique_consent_per_partner',
        ),
        migrations.AlterUniqueTogether(
            name='partnerlocationattendance',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerlocationconsent',
            unique_together={('user', 'partner')},
        ),
    ]
