# Generated by Django 4.2.25 on 2025-10-12 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('org_id', models.UUIDField(blank=True, null=True)),
                ('partner_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('auto_update', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('audience', models.JSONField(default=dict)),
                ('experiment_id', models.UUIDField(blank=True, null=True)),
                ('partner_visible', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('system', 'system'), ('engagement', 'engagement'), ('partner', 'partner'), ('predictive', 'predictive')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.JSONField(default=dict)),
                ('source', models.CharField(default='internal', max_length=64)),
                ('predicted_value', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'captured_at'], name='analytics_m_name_44fdfd_idx'), models.Index(fields=['kind'], name='analytics_m_kind_36e489_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_2c503c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EngagementScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('target_id', models.UUIDField()),
                ('score_type', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['target_id', 'score_type', 'calculated_at'], name='analytics_e_target__b73818_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField(default=dict)),
                ('scope', models.CharField(choices=[('global', 'global'), ('org', 'org'), ('user', 'user'), ('partner', 'partner')], default='global', max_length=32)),
                ('audience', models.JSONField(blank=True, null=True)),
                ('adaptive_rules', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('key', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=16)),
                ('condition', models.JSONField(default=dict)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.UUIDField(blank=True, null=True)),
                ('audience', models.JSONField(blank=True, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
