from __future__ import annotations

from copy import deepcopy
from typing import Any


def _mb(value_gb: int) -> int:
    return int(value_gb) * 1024


TIER_PRESETS: list[dict[str, Any]] = [
    {
        "name": "Free",
        "price_cents": 0,
        "rank": 0,
        "billing_period_days": 30,
        "features_json": {
            "feature_tagline": "Start free, upgrade anytime",
            "feature_highlight": "Everything you need to begin",
            "feature_list": [
                "Direct messaging",
                "Core community access",
                "Standard profile",
                "Basic storage (1 GB for broadcast feeds and profile gallery)",
                "Search & discovery",
                "Standard support",
                "Limited community/group creation (create 1 community and 2 groups)",
            ],
            "communities": 1,
            "groups_per_community": 2,
            "channels_create": 0,
            "channels_follow": True,
            "media_storage_mb": _mb(1),
            "storage_gb": 1,
            "status_retention_days": 2,
            "ads": True,
            "support": "standard",
            "profile_articles": True,
            "privacy_custom": True,
            "shops_limit": 0,
            "products_per_shop_limit": 0,
            "market_profiles": 0,
            "health_profiles": 0,
            "education_profiles": 0,
            "partner_accounts": 0,
            "websites_limit": 0,
            "website_pages_limit": 0,
            "website_kis_content_sections_limit": 0,
            "website_custom_branding": False,
            "website_publish": False,
        },
    },
    {
        "name": "Pro",
        "price_cents": 1000,
        "rank": 1,
        "billing_period_days": 30,
        "features_json": {
            "feature_tagline": "Creators and power users",
            "feature_highlight": "Enhanced profile + higher limits",
            "feature_list": [
                "Free +",
                "More communities & groups",
                "Enhanced profile visibility",
                "Higher media limits (5 GB for broadcast feeds and profile gallery)",
                "Advanced messaging tools",
                "Priority search ranking",
                "Extended support",
            ],
            "communities": 3,
            "groups_per_community": 20,
            "channels_create": 1,
            "channels_follow": True,
            "media_storage_mb": _mb(5),
            "storage_gb": 5,
            "status_retention_days": 3,
            "ads": False,
            "support": "extended",
            "profile_articles": True,
            "privacy_custom": True,
            "shops_limit": 0,
            "products_per_shop_limit": 0,
            "market_profiles": 0,
            "health_profiles": 0,
            "education_profiles": 0,
            "partner_accounts": 0,
            "websites_limit": 1,
            "website_pages_limit": 3,
            "website_kis_content_sections_limit": 2,
            "website_custom_branding": False,
            "website_publish": True,
        },
    },
    {
        "name": "Business",
        "price_cents": 2500,
        "rank": 2,
        "billing_period_days": 30,
        "features_json": {
            "feature_tagline": "Teams, growth, and visibility",
            "feature_highlight": "KIS Business broadcast + storefront",
            "feature_list": [
                "Pro +",
                "KIS Business broadcast channel",
                "Business profile + CTA buttons",
                "Multiple admins for business page",
                "Business insights & audience metrics",
                "Basic catalog for services/products",
                "Higher media limits (7 GB for broadcast feeds and profile gallery)",
                "Promo codes + offers",
                "Auto-reply & business hours",
                "Featured discovery boost",
            ],
            "communities": 10,
            "groups_per_community": 50,
            "channels_create": 5,
            "channels_follow": True,
            "media_storage_mb": _mb(7),
            "storage_gb": 7,
            "status_retention_days": 4,
            "ads": False,
            "support": "priority",
            "admin_tools": True,
            "analytics_basic": True,
            "team_seats": 3,
            "shops_limit": 2,
            "products_per_shop_limit": 60,
            "market_profiles": 1,
            "health_profiles": 0,
            "education_profiles": 0,
            "partner_accounts": 0,
            "websites_limit": 1,
            "website_pages_limit": 5,
            "website_kis_content_sections_limit": 5,
            "website_custom_branding": True,
            "website_publish": True,
        },
    },
    {
        "name": "Business Pro",
        "price_cents": 3500,
        "rank": 3,
        "billing_period_days": 30,
        "features_json": {
            "feature_tagline": "High-impact teams and creators",
            "feature_badge": "Most popular",
            "feature_highlight": "Advanced analytics + team workflows",
            "feature_list": [
                "Business +",
                "Unlimited communities & groups",
                "Team collaboration tools",
                "Advanced insights & reporting",
                "Priority moderation tools",
                "Limited health profiles creation (1)",
                "Limited education profiles creation (1)",
                "Higher media limits (10 GB for broadcast feeds, profile gallery, and market items)",
                "Unlimited market profile creation",
                "Branding controls",
                "Faster support response",
                "Web control panel — manage your shops from any computer",
            ],
            "communities": "unlimited",
            "groups_per_community": "unlimited",
            "channels_create": 15,
            "channels_follow": True,
            "media_storage_mb": _mb(10),
            "storage_gb": 10,
            "status_retention_days": 7,
            "ads": False,
            "support": "priority",
            "admin_tools": True,
            "analytics_advanced": True,
            "crm_tools": True,
            "team_seats": 20,
            "verification_badge": True,
            "shops_limit": "unlimited",
            "products_per_shop_limit": 200,
            "market_analytics": True,
            "market_pro_insights": True,
            "market_profiles": "unlimited",
            "health_profiles": 1,
            "education_profiles": 1,
            "partner_accounts": 0,
            "websites_limit": 3,
            "website_pages_limit": "unlimited",
            "website_kis_content_sections_limit": "unlimited",
            "website_custom_branding": True,
            "website_publish": True,
            "web_control_panel": True,
        },
    },
    {
        "name": "Partner",
        "price_cents": 6000,
        "rank": 4,
        "billing_period_days": 30,
        "features_json": {
            "feature_tagline": "Organizations, ministries, and enterprises",
            "feature_badge": "Partner",
            "feature_highlight": "Multi-account orgs + revenue tools",
            "feature_list": [
                "Business Pro +",
                "Verified organization profile",
                "Multiple admins & roles",
                "Live streaming + events",
                "Donations & revenue tools",
                "Advanced analytics dashboard",
                "Community & group management at scale",
                "Priority support",
                "Partner webhooks & automations",
                "Higher media limits (13 GB for broadcast feeds and profile gallery)",
                "Unlimited health profiles creation",
                "Unlimited education profiles creation",
                "Post job openings",
                "Web control panel — manage your partner org from any computer",
                "Custom roles & granular permissions",
                "Member moderation (mute, timeout, kick, ban) with a full audit log",
                "Channels, categories, and per-channel permission overwrites",
                "Verified organization badge request & review",
                "Task management & team collaboration boards in every channel",
            ],
            "communities": "unlimited",
            "groups_per_community": "unlimited",
            "channels_create": 50,
            "channels_follow": True,
            "media_storage_mb": _mb(13),
            "storage_gb": 13,
            "status_retention_days": 10,
            "ads": False,
            "support": "priority",
            "admin_tools": True,
            "analytics_advanced": True,
            "crm_tools": True,
            "team_seats": 50,
            "revenue_tools": True,
            "api_access": True,
            "privacy_custom": True,
            "profile_articles": True,
            "partner_accounts": 5,
            "partner_integrations": True,
            "partner_webhooks": True,
            "partner_automation": True,
            "partner_insight": True,
            "access_control": True,
            "job_posting": True,
            "task_management": True,
            "shops_limit": "unlimited",
            "products_per_shop_limit": "unlimited",
            "market_analytics": True,
            "market_pro_insights": True,
            "market_profiles": "unlimited",
            "health_profiles": "unlimited",
            "education_profiles": "unlimited",
            "live_streaming": True,
            "events": True,
            "websites_limit": 1,
            "website_pages_limit": 5,
            "website_kis_content_sections_limit": 5,
            "website_custom_branding": True,
            "website_publish": True,
            "web_control_panel": True,
        },
    },
    {
        "name": "Partner Pro",
        "price_cents": 12000,
        "rank": 5,
        "billing_period_days": 30,
        "features_json": {
            "feature_tagline": "Global partner networks & enterprise ops",
            "feature_badge": "Partner Pro",
            "feature_highlight": "Unlimited partner orgs + automation ops",
            "feature_list": [
                "Partner +",
                "Unlimited partner organizations",
                "Enterprise automation & API/webhooks",
                "Dedicated revenue & giving ops hub",
                "Advanced analytics & forecasting",
                "Priority compliance & governance controls",
                "Global roles & permission teams",
                "Concierge onboarding & migration",
                "Unlimited media limits",
                "Better groups, communities, channels, and feeds management",
                "Organizational management tools",
                "Post job openings",
                "Web control panel — manage your entire partner network from any computer",
                "Custom roles & granular permissions",
                "Member moderation (mute, timeout, kick, ban) with a full audit log",
                "Voice channels",
                "Channels, categories, and per-channel permission overwrites",
                "Verified organization badge request & review",
                "Task management & team collaboration boards in every channel",
            ],
            "communities": "unlimited",
            "groups_per_community": "unlimited",
            "channels_create": "unlimited",
            "channels_follow": True,
            "media_storage_mb": "unlimited",
            "storage_gb": "unlimited",
            "status_retention_days": 14,
            "ads": False,
            "support": "concierge",
            "admin_tools": True,
            "analytics_advanced": True,
            "crm_tools": True,
            "team_seats": "unlimited",
            "revenue_tools": True,
            "api_access": True,
            "privacy_custom": True,
            "profile_articles": True,
            "partner_accounts": "unlimited",
            "partner_integrations": True,
            "partner_webhooks": True,
            "partner_automation": True,
            "partner_insight": True,
            "partner_forecasting": True,
            "priority_compliance": True,
            "access_control": True,
            "voice_channels": True,
            "task_management": True,
            "job_posting": True,
            "shops_limit": "unlimited",
            "products_per_shop_limit": "unlimited",
            "market_analytics": True,
            "market_pro_insights": True,
            "market_profiles": "unlimited",
            "health_profiles": "unlimited",
            "education_profiles": "unlimited",
            "live_streaming": True,
            "events": True,
            "websites_limit": "unlimited",
            "website_pages_limit": "unlimited",
            "website_kis_content_sections_limit": "unlimited",
            "website_custom_branding": True,
            "website_publish": True,
            "web_control_panel": True,
        },
    },
]


def _normalize_tier_name(name: str | None) -> str:
    return str(name or "").strip().lower()


def iter_tier_presets() -> list[dict[str, Any]]:
    return deepcopy(TIER_PRESETS)


def get_tier_preset(name: str | None) -> dict[str, Any] | None:
    normalized = _normalize_tier_name(name)
    for preset in TIER_PRESETS:
        if _normalize_tier_name(preset.get("name")) == normalized:
            return deepcopy(preset)
    return None


def get_tier_preset_features(name: str | None) -> dict[str, Any]:
    preset = get_tier_preset(name)
    if not preset:
        return {}
    features = preset.get("features_json")
    return deepcopy(features) if isinstance(features, dict) else {}
