# Generated by Django 5.2.8 on 2025-11-18 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_conversation_avatar_url_conversation_description_and_more'),
        ('communities', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Optional avatar / icon for this channel.')),
                ('is_archived', models.BooleanField(default=False, help_text='Soft-archive the channel (and usually its conversation).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, help_text='Owning community (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='communities.community')),
                ('conversation', models.OneToOneField(help_text='The chat conversation backing this channel.', on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_channels', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='Owning partner (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='partners.partner')),
            ],
            options={
                'db_table': 'channel_channel',
                'unique_together': {('community', 'slug')},
            },
        ),
    ]
