# Generated by Django 4.2.25 on 2026-04-20 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_alter_community_allow_join_link_and_more'),
        ('partners', '0036_partnerservercategory'),
        ('channels', '0002_channel_invite_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('partner', 'slug'), ('community', 'slug')},
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional partner server category used to group channels in the sidebar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='partners.partnerservercategory'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('text', 'Text'), ('announcement', 'Announcement'), ('private', 'Private')], db_index=True, default='announcement', max_length=24),
        ),
        migrations.AddField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['partner', 'category', 'order'], name='channel_cha_partner_6e734b_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['partner', 'channel_type'], name='channel_cha_partner_3d81a5_idx'),
        ),
    ]
