# Generated by Django 4.2.25 on 2026-08-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_subchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('text', 'Text'), ('announcement', 'Announcement'), ('private', 'Private'), ('voice', 'Voice')], db_index=True, default='announcement', max_length=24),
        ),
    ]
