from typing import List, Dict


PARTNER_SETTINGS_SECTIONS: List[Dict] = [
    {
        "key": "org_setup",
        "title": "Organization Setup",
        "description": "Structure, units, teams, and core settings.",
        "features": [
            {"key": "org_profile", "title": "Organization Profile", "description": "Name, brand kit, mission statement, and public summary.", "access": ["owner", "admin"]},
            {"key": "landing_page_builder", "title": "Landing Page Builder", "description": "Dynamic landing page sections, styling, and preview configuration.", "access": ["owner", "admin", "manager"]},
            {"key": "units_departments", "title": "Departments & Units", "description": "Create and manage departments, regions, and divisions.", "access": ["owner", "admin", "manager"]},
            {"key": "org_locations", "title": "Locations & Branches", "description": "Add offices/branches and assign leaders.", "access": ["owner", "admin", "manager"]},
            {"key": "org_policies", "title": "Policies & Guidelines", "description": "Publish internal policies, conduct rules, and onboarding.", "access": ["owner", "admin"]},
            {"key": "org_integrations", "title": "Integrations", "description": "Connect external tools and data sources.", "access": ["owner", "admin"]},
        ],
    },
    {
        "key": "team_access",
        "title": "Team & Access",
        "description": "Members, roles, moderation, and verification.",
        "features": [
            {"key": "team_members", "title": "Members", "description": "View, promote, and manage everyone in this organization.", "access": ["owner", "admin", "manager"]},
            {"key": "roles_permissions", "title": "Roles & Permissions", "description": "Create custom roles and assign granular permissions.", "access": ["owner", "admin"]},
            {"key": "moderation_log", "title": "Moderation Log", "description": "History of mutes, timeouts, kicks, and bans.", "access": ["owner", "admin"]},
            {"key": "verification", "title": "Get Verified", "description": "Request the verified or official partner badge for this organization.", "access": ["owner", "admin"]},
        ],
    },
    {
        "key": "organization_apps",
        "title": "Organization Apps",
        "description": "Manage the custom KIS app, Bible experience, and external integrations for your org.",
        "features": [
            {"key": "org_apps_catalog", "title": "App catalog", "description": "List and manage organization apps.", "access": ["owner", "admin", "manager"]},
            {"key": "org_apps_bible", "title": "Bible app", "description": "Configure the bible experience that KCAN maintains.", "access": ["owner", "admin", "manager"]},
            {"key": "org_apps_builder", "title": "App Builder", "description": "Build custom tab apps with layouts, pages, and content blocks.", "access": ["owner", "admin", "manager"]},
        ],
    },
    {
        "key": "location_attendance",
        "title": "Location & Attendance",
        "description": "Manage geofenced attendance events for meetings, services, classes, and field assignments.",
        "features": [
            {"key": "location_events", "title": "Location Events", "description": "Create and manage geofenced attendance events.", "access": ["owner", "admin", "manager"]},
            {"key": "location_attendance_report", "title": "Attendance Reports", "description": "View check-in lists, arrival order, and export attendance.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "location_consent_settings", "title": "Consent Settings", "description": "View member consent status for location attendance.", "access": ["owner", "admin"]},
        ],
    },
    {
        "key": "community_ops",
        "title": "Communities, Groups & Channels",
        "description": "Create spaces and set posting rules.",
        "features": [
            {"key": "create_community", "title": "Create Community", "description": "Open new communities under this partner.", "access": ["owner", "admin", "manager"]},
            {"key": "create_group", "title": "Create Group", "description": "Create member groups with sub-groups.", "access": ["owner", "admin", "manager"]},
            {"key": "create_channel", "title": "Create Channel", "description": "Launch broadcast or topic channels.", "access": ["owner", "admin", "manager"]},
            {"key": "content_rules", "title": "Posting Policies", "description": "Who can post, approval flows, and moderation rules.", "access": ["owner", "admin"]},
            {"key": "membership_rules", "title": "Membership Rules", "description": "Join/leave rules, approvals, and thresholds.", "access": ["owner", "admin", "manager"]},
            {"key": "recruitment_pipeline", "title": "Recruitment Pipeline", "description": "Job posts, screening steps, and auto-assign onboarding.", "access": ["owner", "admin"]},
            {"key": "spaces_directory", "title": "Spaces Directory", "description": "Show/hide spaces in the directory.", "access": ["owner", "admin"]},
        ],
    },
    {
        "key": "learning_courses",
        "title": "Learning & Courses",
        "description": "Create Bible courses and partner training programs.",
        "features": [
            {"key": "course_builder", "title": "Course Builder", "description": "Create structured courses with modules and lessons.", "access": ["owner", "admin"]},
            {"key": "lesson_library", "title": "Lesson Library", "description": "Manage lesson content, audio, and study prompts.", "access": ["owner", "admin", "manager"]},
            {"key": "course_pricing", "title": "Course Pricing", "description": "Set free vs paid access for partner courses.", "access": ["owner", "admin"]},
            {"key": "course_enrollments", "title": "Enrollments", "description": "Track member progress and completion.", "access": ["owner", "admin", "manager"]},
        ],
    },
    {
        "key": "permissions",
        "title": "Permissions & Admins",
        "description": "Roles, approvals, and access gates.",
        "features": [
            {"key": "role_matrix", "title": "Role Matrix", "description": "Configure permissions per role and unit.", "access": ["owner", "admin"]},
            {"key": "assign_admins", "title": "Assign Admins", "description": "Set admins for communities, groups, and channels.", "access": ["owner", "admin"]},
            {"key": "approval_flows", "title": "Approval Flows", "description": "Post, join, and role change approvals.", "access": ["owner", "admin"]},
            {"key": "access_requests", "title": "Access Requests", "description": "Review and approve access requests.", "access": ["owner", "admin", "manager"]},
            {"key": "audit_log", "title": "Audit Log", "description": "See administrative actions and approvals.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "member_blocks", "title": "Member Blocks", "description": "Block, restore, and review restrictions.", "access": ["owner", "admin"]},
        ],
    },
    {
        "key": "analytics",
        "title": "Analytics & Insights",
        "description": "Business and community intelligence.",
        "features": [
            {"key": "engagement_overview", "title": "Engagement Overview", "description": "Daily and weekly engagement summary.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "reaction_trends", "title": "Reaction Trends", "description": "Reactions by content type and period.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "top_contributors", "title": "Top Contributors", "description": "Most active members and teams.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "message_velocity", "title": "Message Velocity", "description": "Messages per hour/day with peaks.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "retention", "title": "Member Retention", "description": "Cohort retention and churn risks.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "growth_funnel", "title": "Growth Funnel", "description": "Join requests -> approvals -> active.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "content_performance", "title": "Content Performance", "description": "Posts that drive the most activity.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "channel_health", "title": "Channel Health", "description": "Channel activity and drops.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "community_heatmap", "title": "Community Heatmap", "description": "Where engagement is highest.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "campaign_tracking", "title": "Campaign Tracking", "description": "Track promotions and broadcasts.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "response_times", "title": "Response Times", "description": "Average response times per team.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "participation_depth", "title": "Participation Depth", "description": "Depth of conversations by topic.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "sentiment_snapshot", "title": "Sentiment Snapshot", "description": "Tag sentiment from reactions.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "event_uptake", "title": "Event Uptake", "description": "Participation for events and polls.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "resource_downloads", "title": "Resource Downloads", "description": "File and media usage insights.", "access": ["owner", "admin", "manager", "analyst"]},
        ],
    },
    {
        "key": "leadership_tree",
        "title": "Leadership & Org Tree",
        "description": "Structure, leadership, and reporting lines.",
        "features": [
            {"key": "org_tree_view", "title": "Org Tree View", "description": "Interactive org structure map.", "access": ["owner", "admin", "manager"]},
            {"key": "leadership_roles", "title": "Leadership Roles", "description": "Define leadership roles by unit.", "access": ["owner", "admin"]},
            {"key": "succession_plan", "title": "Succession Planning", "description": "Assign backups and succession.", "access": ["owner", "admin"]},
            {"key": "team_health", "title": "Team Health", "description": "Pulse of each team unit.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "leadership_directory", "title": "Leadership Directory", "description": "Public leadership contact list.", "access": ["owner", "admin", "manager"]},
            {"key": "mentorship_routes", "title": "Mentorship Routes", "description": "Assign mentors for teams.", "access": ["owner", "admin", "manager"]},
            {"key": "skills_matrix", "title": "Skills Matrix", "description": "Skill coverage across teams.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "capacity_planning", "title": "Capacity Planning", "description": "Workload capacity per unit.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "role_alignment", "title": "Role Alignment", "description": "Role-to-team alignment checks.", "access": ["owner", "admin", "manager"]},
            {"key": "org_announcements", "title": "Org Announcements", "description": "Leadership communications hub.", "access": ["owner", "admin", "manager"]},
            {"key": "org_tree_notes", "title": "Org Tree Notes", "description": "Attach notes and rationale to org nodes.", "access": ["owner", "admin", "manager"]},
            {"key": "role_requirements", "title": "Role Requirements", "description": "Define requirements and competencies per role.", "access": ["owner", "admin"]},
            {"key": "onboarding_paths", "title": "Onboarding Paths", "description": "Role-based onboarding routes and mentors.", "access": ["owner", "admin", "manager"]},
            {"key": "leadership_goals", "title": "Leadership Goals", "description": "Quarterly goals and scorecards by unit.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "cross_team_projects", "title": "Cross-team Projects", "description": "Track multi-team initiatives and owners.", "access": ["owner", "admin", "manager"]},
            {"key": "reporting_lines", "title": "Reporting Lines", "description": "Edit reporting lines and dotted-line links.", "access": ["owner", "admin"]},
            {"key": "span_of_control", "title": "Span of Control", "description": "Monitor team size per leader.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "diversity_dashboard", "title": "Diversity Dashboard", "description": "Representation and inclusion insights.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "conflict_resolution", "title": "Conflict Resolution", "description": "Escalations and mediation workflows.", "access": ["owner", "admin"]},
            {"key": "leadership_scorecards", "title": "Leadership Scorecards", "description": "Performance snapshots per leader.", "access": ["owner", "admin", "manager", "analyst"]},
        ],
    },
    {
        "key": "general_tools",
        "title": "General Tools",
        "description": "Operational tools for organizations.",
        "features": [
            {"key": "task_boards", "title": "Task Boards", "description": "Boards for team initiatives.", "access": ["owner", "admin", "manager"]},
            {"key": "resource_library", "title": "Resource Library", "description": "Store files and playbooks.", "access": ["owner", "admin", "manager"]},
            {"key": "training_tracks", "title": "Training Tracks", "description": "Assign training modules.", "access": ["owner", "admin", "manager"]},
            {"key": "events_calendar", "title": "Events Calendar", "description": "Org-wide event scheduling.", "access": ["owner", "admin", "manager"]},
            {"key": "broadcast_center", "title": "Broadcast Center", "description": "Schedule broadcasts and updates.", "access": ["owner", "admin", "manager"]},
            {"key": "support_inbox", "title": "Support Inbox", "description": "Manage member support tickets.", "access": ["owner", "admin"]},
            {"key": "automation_rules", "title": "Automation Rules", "description": "Automate routine workflows.", "access": ["owner", "admin"]},
            {"key": "templates", "title": "Templates", "description": "Saved templates for posts.", "access": ["owner", "admin", "manager"]},
            {"key": "feedback_hub", "title": "Feedback Hub", "description": "Collect structured feedback.", "access": ["owner", "admin", "manager", "analyst"]},
            {"key": "compliance_center", "title": "Compliance Center", "description": "Track policy acknowledgments.", "access": ["owner", "admin"]},
            {"key": "surveys", "title": "Surveys", "description": "Run internal surveys and polls.", "access": ["owner", "admin", "manager"]},
            {"key": "knowledge_base", "title": "Knowledge Base", "description": "Document SOPs and FAQs.", "access": ["owner", "admin", "manager"]},
            {"key": "announcement_scheduler", "title": "Announcement Scheduler", "description": "Plan announcements by audience.", "access": ["owner", "admin", "manager"]},
            {"key": "helpdesk", "title": "Helpdesk", "description": "Route support questions to teams.", "access": ["owner", "admin"]},
            {"key": "budget_tracking", "title": "Budget Tracking", "description": "Track budgets by department.", "access": ["owner", "admin"]},
            {"key": "volunteer_roster", "title": "Volunteer Roster", "description": "Schedule volunteers and shifts.", "access": ["owner", "admin", "manager"]},
            {"key": "donation_tracking", "title": "Donation Tracking", "description": "Track donations and receipts.", "access": ["owner", "admin"]},
            {"key": "security_center", "title": "Security Center", "description": "Security policies and incident logs.", "access": ["owner", "admin"]},
            {"key": "data_exports", "title": "Data Exports", "description": "Export reports for audits.", "access": ["owner", "admin"]},
            {"key": "workspace_branding", "title": "Workspace Branding", "description": "Theme and branding controls.", "access": ["owner", "admin"]},
        ],
    },
]
