# Generated by Django 4.2.25 on 2026-02-20 14:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('is_fixed', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('default_step_count', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'health_ops_engine_registry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_step', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('is_paused', models.BooleanField(db_index=True, default=False)),
                ('is_unlocked', models.BooleanField(db_index=True, default=False)),
                ('state_blob', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'health_ops_engine_session',
            },
        ),
        migrations.CreateModel(
            name='EngineStepDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('validation_schema', models.JSONField(blank=True, default=dict)),
                ('completion_rule', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_definitions', to='health_ops.engineregistry')),
            ],
            options={
                'db_table': 'health_ops_engine_step_definition',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='HealthInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('institution_type', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('lab', 'Laboratory'), ('diagnostics', 'Diagnostics Center'), ('pharmacy', 'Pharmacy'), ('wellness_center', 'Wellness Center')], db_index=True, default='clinic', max_length=40)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_owned_institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_institution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_assessment', models.BooleanField(default=False)),
                ('assessment_schema', models.JSONField(blank=True, default=dict)),
                ('base_cost_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='health_ops.healthinstitution')),
            ],
            options={
                'db_table': 'health_ops_service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEngineMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_order', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('cost_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_required', models.BooleanField(default=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='health_ops.engineregistry')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_mappings', to='health_ops.healthservice')),
            ],
            options={
                'db_table': 'health_ops_service_engine_map',
                'ordering': ['execution_order'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_wallet',
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkflowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', max_length=32)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('completed_steps', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_locked_by_payment', models.BooleanField(default=False)),
                ('requires_assessment', models.BooleanField(default=False)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_engine_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_workflow_sessions', to='health_ops.serviceenginemap')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_workflow_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_workflow_session',
            },
        ),
        migrations.CreateModel(
            name='HealthOpsAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ops_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='health_ops.healthinstitution')),
            ],
            options={
                'db_table': 'health_ops_audit_log',
            },
        ),
        migrations.CreateModel(
            name='HealthInstitutionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('member', 'Member')], db_index=True, default='member', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='health_ops.healthinstitution')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ops_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_membership',
            },
        ),
        migrations.CreateModel(
            name='EngineStepProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(db_index=True, max_length=120)),
                ('content_position', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('engine_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='health_ops.enginesession')),
                ('step_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_progress', to='health_ops.enginestepdefinition')),
            ],
            options={
                'db_table': 'health_ops_engine_step_progress',
            },
        ),
        migrations.AddField(
            model_name='enginesession',
            name='engine_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_sessions', to='health_ops.serviceenginemap'),
        ),
        migrations.AddField(
            model_name='enginesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_engine_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enginesession',
            name='workflow_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_sessions', to='health_ops.serviceworkflowsession'),
        ),
        migrations.CreateModel(
            name='EngineContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('file', 'File'), ('interactive', 'Interactive')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_content_blocks', to=settings.AUTH_USER_MODEL)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='health_ops.engineregistry')),
            ],
            options={
                'db_table': 'health_ops_engine_content_block',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=16)),
                ('amount_micro', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reference', models.CharField(db_index=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('engine_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='health_ops.enginesession')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='health_ops.wallet')),
            ],
            options={
                'db_table': 'health_ops_wallet_transaction',
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='health_ops__wallet__80945e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='serviceworkflowsession',
            index=models.Index(fields=['user', 'status'], name='health_ops__user_id_ccec1d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceworkflowsession',
            index=models.Index(fields=['service', 'created_at'], name='health_ops__service_37da03_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceenginemap',
            constraint=models.UniqueConstraint(fields=('service', 'engine'), name='health_ops_service_engine_unique'),
        ),
        migrations.AddConstraint(
            model_name='serviceenginemap',
            constraint=models.UniqueConstraint(fields=('service', 'execution_order'), name='health_ops_service_engine_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='healthservice',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='health_ops_service_name_per_institution'),
        ),
        migrations.AddIndex(
            model_name='healthopsauditlog',
            index=models.Index(fields=['action', 'created_at'], name='health_ops__action_4fa731_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinstitutionmembership',
            index=models.Index(fields=['role', 'is_active'], name='health_ops__role_fb64e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthinstitutionmembership',
            constraint=models.UniqueConstraint(fields=('institution', 'user'), name='health_ops_membership_unique'),
        ),
        migrations.AddIndex(
            model_name='healthinstitution',
            index=models.Index(fields=['owner', 'institution_type'], name='health_ops__owner_i_7ae549_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinstitution',
            index=models.Index(fields=['is_active'], name='health_ops__is_acti_330cdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='enginestepprogress',
            constraint=models.UniqueConstraint(fields=('engine_session', 'step_key'), name='health_ops_engine_step_progress_unique'),
        ),
        migrations.AddConstraint(
            model_name='enginestepdefinition',
            constraint=models.UniqueConstraint(fields=('engine', 'step_key'), name='health_ops_engine_step_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='enginestepdefinition',
            constraint=models.UniqueConstraint(fields=('engine', 'step_order'), name='health_ops_engine_step_order_unique'),
        ),
        migrations.AddIndex(
            model_name='enginesession',
            index=models.Index(fields=['user', 'is_completed'], name='health_ops__user_id_e62667_idx'),
        ),
        migrations.AddConstraint(
            model_name='enginesession',
            constraint=models.UniqueConstraint(fields=('workflow_session', 'engine_map'), name='health_ops_workflow_engine_session_unique'),
        ),
        migrations.AddConstraint(
            model_name='enginecontentblock',
            constraint=models.UniqueConstraint(fields=('engine', 'order'), name='health_ops_engine_content_order_unique'),
        ),
    ]
