# Generated by Django 4.2.25 on 2026-02-20 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_start', models.DateTimeField(db_index=True)),
                ('slot_end', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='booked', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_bookings', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_bookings', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_appointment_bookings', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_booking', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_appointment_booking',
                'indexes': [models.Index(fields=['service', 'slot_start', 'status'], name='health_ops__service_934ef8_idx'), models.Index(fields=['institution', 'slot_start'], name='health_ops__institu_928502_idx'), models.Index(fields=['user', 'slot_start'], name='health_ops__user_id_3ba885_idx')],
            },
        ),
    ]
