# Generated by Django 4.2.25 on 2026-02-20 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0002_appointmentbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConsultationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_code', models.CharField(db_index=True, max_length=48)),
                ('host_join_token', models.CharField(max_length=120)),
                ('participant_join_token', models.CharField(max_length=120)),
                ('token_expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting_room', 'Waiting Room'), ('in_session', 'In Session'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=24)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('waiting_room_enabled', models.BooleanField(default=True)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_consultation', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_consultation', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_video_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_consultation', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_video_consultation_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_2d191c_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_d89203_idx'), models.Index(fields=['token_expires_at'], name='health_ops__token_e_0a2634_idx')],
            },
        ),
    ]
