# Generated by Django 4.2.25 on 2026-02-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0003_videoconsultationsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureMessagingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_code', models.CharField(db_index=True, max_length=48)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='waiting', max_length=24)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_messaging', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secure_messaging', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_messaging_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_messaging_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_secure_messaging_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secure_messaging', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_secure_messaging_session',
            },
        ),
        migrations.CreateModel(
            name='SecureMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('voice', 'Voice'), ('system', 'System')], default='text', max_length=16)),
                ('body', models.TextField(blank=True, default='')),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_secure_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='health_ops.securemessagingsession')),
            ],
            options={
                'db_table': 'health_ops_secure_message',
            },
        ),
        migrations.CreateModel(
            name='ClinicalEngineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine_code', models.CharField(choices=[('ehr_records', 'EHR / Health Records'), ('lab_order', 'Lab Order'), ('imaging_order', 'Imaging Order')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='waiting', max_length=24)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_engine_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_session', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_engine_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_engine_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_clinical_engine_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_engine_sessions', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_clinical_engine_session',
            },
        ),
        migrations.AddIndex(
            model_name='securemessagingsession',
            index=models.Index(fields=['user', 'status'], name='health_ops__user_id_c37c96_idx'),
        ),
        migrations.AddIndex(
            model_name='securemessagingsession',
            index=models.Index(fields=['service', 'created_at'], name='health_ops__service_a85b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='securemessagingsession',
            index=models.Index(fields=['thread_code'], name='health_ops__thread__bb229b_idx'),
        ),
        migrations.AddIndex(
            model_name='securemessage',
            index=models.Index(fields=['session', 'created_at'], name='health_ops__session_5e5456_idx'),
        ),
        migrations.AddIndex(
            model_name='securemessage',
            index=models.Index(fields=['sender', 'created_at'], name='health_ops__sender__8bea32_idx'),
        ),
        migrations.AddIndex(
            model_name='securemessage',
            index=models.Index(fields=['is_read', 'created_at'], name='health_ops__is_read_0b49c5_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalenginesession',
            index=models.Index(fields=['user', 'status'], name='health_ops__user_id_0851d9_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalenginesession',
            index=models.Index(fields=['service', 'engine_code'], name='health_ops__service_c46b19_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalenginesession',
            index=models.Index(fields=['workflow_session', 'engine_code'], name='health_ops__workflo_0e816b_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalenginesession',
            constraint=models.UniqueConstraint(fields=('workflow_session', 'engine_code'), name='health_ops_clinical_engine_unique'),
        ),
    ]
