# Generated by Django 4.2.25 on 2026-02-20 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0004_securemessagingsession_securemessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDispatchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_code', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('triaging', 'Triaging'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=24)),
                ('triage_level', models.CharField(blank=True, default='', max_length=40)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ambulance_reference', models.CharField(blank=True, default='', max_length=120)),
                ('current_eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tracking_events', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_tracking_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_dispatch_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_dispatch', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_dispatch_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_dispatch_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_emergency_dispatch_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_dispatch', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_emergency_dispatch_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_73e648_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_ddaaca_idx'), models.Index(fields=['dispatch_code'], name='health_ops__dispatc_1a289b_idx'), models.Index(fields=['last_tracking_at'], name='health_ops__last_tr_4eb457_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionBedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('intake', 'Intake'), ('bed_assigned', 'Bed Assigned'), ('admitted', 'Admitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=24)),
                ('ward_name', models.CharField(blank=True, default='', max_length=120)),
                ('bed_code', models.CharField(blank=True, default='', max_length=80)),
                ('triage_level', models.CharField(blank=True, default='', max_length=40)),
                ('requires_isolation', models.BooleanField(default=False)),
                ('requires_icu', models.BooleanField(default=False)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_bed_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_bed', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_bed_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_bed_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_admission_bed_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_bed', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_admission_bed_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_b70c10_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_778be2_idx'), models.Index(fields=['ward_name', 'bed_code'], name='health_ops__ward_na_039c7a_idx')],
            },
        ),
    ]
