# Generated by Django 4.2.25 on 2026-02-20 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0005_emergencydispatchsession_admissionbedsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyFulfillmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('verifying', 'Verifying'), ('inventory_confirmed', 'Inventory Confirmed'), ('fulfillment_in_progress', 'Fulfillment In Progress'), ('ready_for_collection', 'Ready For Collection'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=32)),
                ('cart_items', models.JSONField(blank=True, default=list)),
                ('delivery_mode', models.CharField(blank=True, default='', max_length=32)),
                ('payment_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('fulfillment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('current_eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tracking_events', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_tracking_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_fulfillment_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_fulfillment', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_fulfillment_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_fulfillment_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_pharmacy_fulfillment_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_fulfillment', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_pharmacy_fulfillment_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_6d4877_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_d9ad34_idx'), models.Index(fields=['payment_reference'], name='health_ops__payment_ff347b_idx'), models.Index(fields=['last_tracking_at'], name='health_ops__last_tr_52914b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentBillingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('quote_ready', 'Quote Ready'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('invoiced', 'Invoiced'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=24)),
                ('total_amount_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_coverage_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payable_amount_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_provider', models.CharField(blank=True, default='', max_length=40)),
                ('payment_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_billing_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_payment_billing_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_payment_billing_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_048066_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_13b4c4_idx'), models.Index(fields=['payment_reference'], name='health_ops__payment_2b313e_idx'), models.Index(fields=['invoice_number'], name='health_ops__invoice_c3c4db_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeLogisticsSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logistics_code', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('scheduling', 'Scheduling'), ('route_assigned', 'Route Assigned'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=24)),
                ('task_type', models.CharField(blank=True, default='', max_length=40)),
                ('route_reference', models.CharField(blank=True, default='', max_length=120)),
                ('assignee_name', models.CharField(blank=True, default='', max_length=120)),
                ('current_eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('scheduled_window_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_window_end', models.DateTimeField(blank=True, null=True)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tracking_events', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_tracking_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_logistics_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_logistics', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_logistics_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_logistics_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_home_logistics_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_logistics', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_home_logistics_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_f6dfbd_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_a0b69d_idx'), models.Index(fields=['logistics_code'], name='health_ops__logisti_8cb28b_idx'), models.Index(fields=['last_tracking_at'], name='health_ops__last_tr_0d9f6d_idx')],
            },
        ),
    ]
