# Generated by Django 4.2.25 on 2026-02-20 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0006_pharmacyfulfillmentsession_paymentbillingsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessProgramSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=24)),
                ('program_name', models.CharField(blank=True, default='', max_length=160)),
                ('goal_payload', models.JSONField(blank=True, default=dict)),
                ('habit_payload', models.JSONField(blank=True, default=dict)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('completion_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('activity_events', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellness_program_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_program', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_program_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_program_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_wellness_program_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_program', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_wellness_program_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_4e705c_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_2c9586_idx'), models.Index(fields=['program_name'], name='health_ops__program_79dbb4_idx'), models.Index(fields=['last_activity_at'], name='health_ops__last_ac_1a2300_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationReminderSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('configuring', 'Configuring'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('disabled', 'Disabled'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=24)),
                ('channel_config', models.JSONField(blank=True, default=dict)),
                ('rule_config', models.JSONField(blank=True, default=dict)),
                ('reminder_timezone', models.CharField(default='UTC', max_length=64)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivery_events', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_reminder_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reminder', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reminder_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reminder_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_notification_reminder_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reminder', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_notification_reminder_session',
                'indexes': [models.Index(fields=['user', 'status'], name='health_ops__user_id_2bde83_idx'), models.Index(fields=['service', 'created_at'], name='health_ops__service_99c7fe_idx'), models.Index(fields=['next_run_at'], name='health_ops__next_ru_b072d4_idx'), models.Index(fields=['last_delivery_at'], name='health_ops__last_de_2ca2fa_idx')],
            },
        ),
    ]
