# Generated by Django 4.2.25 on 2026-03-09 09:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0008_remove_health_ops_billing_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEngineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ops_video_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_video_engine_item',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='enginesession',
            name='expired_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enginesession',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enginesession',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='enginesession',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceenginemap',
            name='access_window_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceenginemap',
            name='completion_mode',
            field=models.CharField(choices=[('step_progress', 'Step Progress'), ('video_items', 'Video Items')], db_index=True, default='step_progress', max_length=32),
        ),
        migrations.CreateModel(
            name='VideoEngineItemLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_item_likes', to='health_ops.enginesession')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='health_ops.videoengineitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_video_item_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_video_engine_item_like',
            },
        ),
        migrations.CreateModel(
            name='VideoEngineItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('engine_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_item_comments', to='health_ops.enginesession')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='health_ops.videoengineitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_video_item_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_video_engine_item_comment',
            },
        ),
        migrations.AddField(
            model_name='videoengineitem',
            name='engine_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_items', to='health_ops.serviceenginemap'),
        ),
        migrations.AddField(
            model_name='videoengineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ops_video_items_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentBillingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('quote_ready', 'Quote Ready'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('invoiced', 'Invoiced'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=24)),
                ('total_amount_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_coverage_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payable_amount_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_provider', models.CharField(blank=True, default='', max_length=40)),
                ('payment_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_billing_sessions', to='health_ops.appointmentbooking')),
                ('engine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing', to='health_ops.enginesession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing_sessions', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing_sessions', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_payment_billing_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_billing', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_payment_billing_session',
            },
        ),
        migrations.CreateModel(
            name='VideoEngineItemProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_watched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('engine_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_item_progress_rows', to='health_ops.enginesession')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='health_ops.videoengineitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_video_item_progress_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_video_engine_item_progress',
                'indexes': [models.Index(fields=['engine_session', 'user'], name='health_ops__engine__3a2102_idx'), models.Index(fields=['item', 'is_completed'], name='health_ops__item_id_a8e9dc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='videoengineitemprogress',
            constraint=models.UniqueConstraint(fields=('item', 'engine_session', 'user'), name='health_ops_video_item_progress_unique'),
        ),
        migrations.AddIndex(
            model_name='videoengineitemlike',
            index=models.Index(fields=['item', 'created_at'], name='health_ops__item_id_48fe94_idx'),
        ),
        migrations.AddIndex(
            model_name='videoengineitemlike',
            index=models.Index(fields=['engine_session', 'created_at'], name='health_ops__engine__85d379_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoengineitemlike',
            constraint=models.UniqueConstraint(fields=('item', 'engine_session', 'user'), name='health_ops_video_item_like_unique'),
        ),
        migrations.AddIndex(
            model_name='videoengineitemcomment',
            index=models.Index(fields=['item', 'created_at'], name='health_ops__item_id_d86f43_idx'),
        ),
        migrations.AddIndex(
            model_name='videoengineitemcomment',
            index=models.Index(fields=['engine_session', 'created_at'], name='health_ops__engine__d23593_idx'),
        ),
        migrations.AddIndex(
            model_name='videoengineitemcomment',
            index=models.Index(fields=['user', 'created_at'], name='health_ops__user_id_1d4107_idx'),
        ),
        migrations.AddIndex(
            model_name='videoengineitem',
            index=models.Index(fields=['engine_map', 'sort_order'], name='health_ops__engine__e757dc_idx'),
        ),
        migrations.AddIndex(
            model_name='videoengineitem',
            index=models.Index(fields=['engine_map', 'is_active'], name='health_ops__engine__f6ba48_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbillingsession',
            index=models.Index(fields=['user', 'status'], name='health_ops__user_id_048066_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbillingsession',
            index=models.Index(fields=['service', 'created_at'], name='health_ops__service_13b4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbillingsession',
            index=models.Index(fields=['payment_reference'], name='health_ops__payment_2b313e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbillingsession',
            index=models.Index(fields=['invoice_number'], name='health_ops__invoice_c3c4db_idx'),
        ),
    ]
