# Generated by Django 4.2.25 on 2026-03-09 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0010_seed_fixed_engines'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionEngineManagedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine_key', models.SlugField(max_length=120)),
                ('engine_name', models.CharField(blank=True, default='', max_length=255)),
                ('item_kind', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('amount_micro', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_managed_items_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_managed_items', to='health_ops.healthinstitution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='health_ops.institutionenginemanageditem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ops_managed_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_institution_engine_managed_item',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['institution', 'engine_key'], name='health_ops__institu_b612d5_idx'), models.Index(fields=['institution', 'engine_key', 'item_kind'], name='health_ops__institu_d87ea1_idx'), models.Index(fields=['institution', 'engine_key', 'parent'], name='health_ops__institu_7766e4_idx')],
            },
        ),
    ]
