# Generated by Django 4.2.25 on 2026-03-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_ops', '0011_institutionenginemanageditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionenginemanageditem',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
