# Generated by Django 4.2.25 on 2026-05-14 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0013_remove_appointment_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthVitalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate'), ('temperature', 'Temperature'), ('oxygen_saturation', 'Oxygen Saturation'), ('blood_glucose', 'Blood Glucose'), ('weight', 'Weight'), ('custom', 'Custom')], db_index=True, default='custom', max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, default='manual', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='health_ops.healthinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_vital_readings', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_readings', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_vital_reading',
                'ordering': ['-measured_at', '-created_at'],
                'indexes': [models.Index(fields=['institution', 'reading_type'], name='health_ops__institu_2d7e73_idx'), models.Index(fields=['user', 'reading_type', 'measured_at'], name='health_ops__user_id_2065cd_idx'), models.Index(fields=['workflow_session', 'reading_type'], name='health_ops__workflo_00cae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthCarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=24)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('medication_summary', models.JSONField(blank=True, default=dict)),
                ('reminder_summary', models.JSONField(blank=True, default=dict)),
                ('next_review_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='health_ops.healthinstitution')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='health_ops.healthservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ops_care_plans', to=settings.AUTH_USER_MODEL)),
                ('workflow_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_care_plan',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['institution', 'status'], name='health_ops__institu_0ece7f_idx'), models.Index(fields=['user', 'status'], name='health_ops__user_id_aec8dd_idx'), models.Index(fields=['workflow_session', 'status'], name='health_ops__workflo_87f4dd_idx'), models.Index(fields=['next_review_at'], name='health_ops__next_re_676bf8_idx')],
            },
        ),
    ]
