# Generated by Django 4.2.25 on 2026-06-19 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0014_healthvitalreading_healthcareplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddictionRecoveryGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('addiction_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('drugs', 'Drugs'), ('gambling', 'Gambling'), ('pornography', 'Pornography'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meeting_schedule', models.JSONField(default=dict)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_recovery_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_recovery_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemedicineConsult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], db_index=True, default='scheduled', max_length=16)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('prescription_notes', models.TextField(blank=True, default='')),
                ('recording_url', models.URLField(blank=True, default='')),
                ('call_url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tele_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_telemedicine_consult',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_sober', models.IntegerField()),
                ('milestone_type', models.CharField(choices=[('day_1', 'Day 1'), ('day_7', 'Day 7'), ('day_30', 'Day 30'), ('day_90', 'Day 90'), ('day_180', 'Day 180'), ('year_1', 'Year 1'), ('year_2', 'Year 2'), ('year_5', 'Year 5'), ('custom', 'Custom')], db_index=True, max_length=16)),
                ('addiction_type', models.CharField(blank=True, default='', max_length=64)),
                ('celebrated_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_recovery_milestone',
                'ordering': ['-celebrated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('sobriety_start_date', models.DateField(blank=True, null=True)),
                ('sponsor_id', models.UUIDField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='health_ops.addictionrecoverygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_recovery_membership',
            },
        ),
        migrations.CreateModel(
            name='PregnancyTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('current_week', models.IntegerField(blank=True, null=True)),
                ('last_appointment', models.DateField(blank=True, null=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('symptoms', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_pregnancy_tracker',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_score', models.IntegerField()),
                ('emotion_tags', models.JSONField(default=list)),
                ('journal_text', models.TextField(blank=True, default='')),
                ('entry_date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_mood_entry',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='MentalHealthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('crisis', 'Crisis')], db_index=True, default='individual', max_length=16)),
                ('modality', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], default='video', max_length=8)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('session_notes', models.TextField(blank=True, default='')),
                ('is_faith_based', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mh_patient', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mh_therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_mental_health_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentalHealthJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('mood_score', models.IntegerField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('entry_date', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mh_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_mh_journal',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('sleep', 'Sleep'), ('weight', 'Weight'), ('mental', 'Mental'), ('chronic_disease', 'Chronic Disease'), ('other', 'Other')], db_index=True, default='fitness', max_length=16)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_health_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('sos', 'SOS'), ('medical', 'Medical'), ('fire', 'Fire'), ('security', 'Security')], db_index=True, default='sos', max_length=12)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=12)),
                ('notified_contacts', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_emergency_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('prescribed_by', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('refill_due', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('interaction_warnings', models.JSONField(default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emedications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_emedication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='health_ops.telemedicineconsult')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_consult_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodTypeRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.CharField(choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], db_index=True, max_length=8)),
                ('is_available_to_donate', models.BooleanField(db_index=True, default=False)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, default='', max_length=120)),
                ('location_country', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_type_registry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_blood_type_registry',
            },
        ),
        migrations.CreateModel(
            name='BabyMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baby_name', models.CharField(blank=True, default='', max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('milestone_type', models.CharField(choices=[('birth_weight', 'Birth Weight'), ('first_smile', 'First Smile'), ('first_steps', 'First Steps'), ('first_words', 'First Words'), ('other', 'Other')], db_index=True, max_length=16)),
                ('milestone_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ext_baby_milestone',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telemedicineconsult',
            index=models.Index(fields=['patient', 'status'], name='health_ext__patient_1e2ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicineconsult',
            index=models.Index(fields=['doctor', 'status'], name='health_ext__doctor__552858_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverymilestone',
            index=models.Index(fields=['user', 'milestone_type'], name='health_ext__user_id_629065_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverymembership',
            index=models.Index(fields=['group', 'user'], name='health_ext__group_i_a08d76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recoverymembership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='pregnancytracker',
            index=models.Index(fields=['patient', 'is_active'], name='health_ext__patient_ab2dce_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'entry_date'], name='health_ext__user_id_e3d6ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together={('user', 'entry_date')},
        ),
        migrations.AddIndex(
            model_name='mentalhealthsession',
            index=models.Index(fields=['patient', 'status'], name='health_ext__patient_3fe289_idx'),
        ),
        migrations.AddIndex(
            model_name='mentalhealthsession',
            index=models.Index(fields=['therapist', 'status'], name='health_ext__therapi_594915_idx'),
        ),
        migrations.AddIndex(
            model_name='mentalhealthjournal',
            index=models.Index(fields=['user', 'entry_date'], name='health_ext__user_id_8ecd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='healthgoal',
            index=models.Index(fields=['user', 'category'], name='health_ext__user_id_5500a9_idx'),
        ),
        migrations.AddIndex(
            model_name='healthgoal',
            index=models.Index(fields=['user', 'is_achieved'], name='health_ext__user_id_48f268_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['user', 'status'], name='health_ext__user_id_9e6104_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['alert_type', 'status'], name='health_ext__alert_t_cd9376_idx'),
        ),
        migrations.AddIndex(
            model_name='emedication',
            index=models.Index(fields=['patient', 'is_active'], name='health_ext__patient_915e39_idx'),
        ),
        migrations.AddIndex(
            model_name='emedication',
            index=models.Index(fields=['refill_due'], name='health_ext__refill__4d3f08_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodtyperegistry',
            index=models.Index(fields=['blood_type', 'is_available_to_donate'], name='health_ext__blood_t_e6da9a_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodtyperegistry',
            index=models.Index(fields=['location_country', 'blood_type'], name='health_ext__locatio_04dbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='babymilestone',
            index=models.Index(fields=['patient', 'milestone_type'], name='health_ext__patient_b23bed_idx'),
        ),
    ]
