# Generated by Django 4.2.25 on 2026-08-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0042_partnerorganizationlink_and_more'),
        ('health_ops', '0017_healthinstitution_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinstitution',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_institutions', to='partners.partner'),
        ),
        migrations.AddIndex(
            model_name='healthinstitution',
            index=models.Index(fields=['partner'], name='health_ops__partner_d91396_idx'),
        ),
    ]
