# Generated by Django 4.2.25 on 2026-09-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_ops', '0018_healthinstitution_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinstitution',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
