# Generated by Django 4.2.25 on 2026-10-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_channel_channel_type'),
        ('communities', '0016_communitymembership_status_and_more'),
        ('health_ops', '0019_healthinstitution_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinstitution',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_institutions', to='communities.community'),
        ),
        migrations.AddField(
            model_name='healthservice',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_services', to='channels.channel'),
        ),
    ]
