# Generated by Django 4.2.25 on 2026-10-03 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0020_healthinstitution_community_healthservice_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPractitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('profession_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('dentist', 'Dentist'), ('pharmacist', 'Pharmacist'), ('physiotherapist', 'Physiotherapist'), ('psychologist', 'Psychologist / Mental Health Professional'), ('nutritionist', 'Nutritionist / Dietitian'), ('lab_professional', 'Laboratory Professional'), ('specialist', 'Specialist'), ('other', 'Other Licensed Healthcare Professional')], db_index=True, max_length=32)),
                ('specialty', models.CharField(blank=True, default='', max_length=255)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('registration_authority', models.CharField(blank=True, default='', max_length=255)),
                ('license_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=120)),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('license_expires_at', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='health_ops.healthinstitution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_practitioner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_practitioner',
                'indexes': [models.Index(fields=['profession_type', 'is_active'], name='health_ops__profess_f8b53f_idx'), models.Index(fields=['institution', 'is_active'], name='health_ops__institu_6e7e50_idx'), models.Index(fields=['license_number'], name='health_ops__license_f12d69_idx')],
            },
        ),
    ]
