# Generated by Django 4.2.25 on 2026-10-03 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0021_healthpractitioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('lot_number', models.CharField(blank=True, default='', max_length=100)),
                ('next_dose_due', models.DateField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('self_reported', 'Self-reported by patient'), ('clinician_recorded', 'Recorded by a clinician')], default='self_reported', max_length=24)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_immunizations', to='health_ops.healthpractitioner')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_immunizations', to='health_ops.healthinstitution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_immunizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_immunization',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='health_ops__patient_f2b404_idx'), models.Index(fields=['next_dose_due'], name='health_ops__next_do_d607c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icd_code', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('remission', 'In remission')], db_index=True, default='active', max_length=16)),
                ('source', models.CharField(choices=[('self_reported', 'Self-reported by patient'), ('clinician_recorded', 'Recorded by a clinician')], default='self_reported', max_length=24)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_conditions', to='health_ops.healthinstitution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_conditions', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_conditions', to='health_ops.healthpractitioner')),
            ],
            options={
                'db_table': 'health_ops_condition',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='health_ops__patient_2cd51f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.CharField(max_length=255)),
                ('reaction', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-threatening')], default='mild', max_length=20)),
                ('source', models.CharField(choices=[('self_reported', 'Self-reported by patient'), ('clinician_recorded', 'Recorded by a clinician')], default='self_reported', max_length=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_allergies', to='health_ops.healthinstitution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_allergies', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_allergies', to='health_ops.healthpractitioner')),
            ],
            options={
                'db_table': 'health_ops_allergy',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='health_ops__patient_aec61d_idx')],
            },
        ),
    ]
