# Generated by Django 4.2.25 on 2026-10-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_ops', '0022_immunization_condition_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter_type', models.CharField(choices=[('in_person', 'In-person visit'), ('video', 'Video consultation'), ('messaging', 'Secure messaging'), ('emergency', 'Emergency'), ('home_visit', 'Home visit'), ('other', 'Other')], default='in_person', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked in'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show'), ('closed', 'Closed')], db_index=True, default='scheduled', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('treatment_plan', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='health_ops.healthinstitution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_encounters', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='health_ops.healthpractitioner')),
                ('workflow_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='health_ops.serviceworkflowsession')),
            ],
            options={
                'db_table': 'health_ops_encounter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('specimen_collected', 'Specimen collected'), ('processing', 'Processing'), ('result_pending_verification', 'Result pending verification'), ('resulted', 'Resulted'), ('cancelled', 'Cancelled')], db_index=True, default='ordered', max_length=32)),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='health_ops.encounter')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='health_ops.healthinstitution')),
                ('ordering_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_placed', to='health_ops.healthpractitioner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_ops_lab_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specimen_type', models.CharField(blank=True, default='', max_length=100)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens_collected', to='health_ops.healthpractitioner')),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specimen', to='health_ops.laborder')),
            ],
            options={
                'db_table': 'health_ops_specimen',
            },
        ),
        migrations.CreateModel(
            name='LabTestCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('specimen_type', models.CharField(blank=True, default='', max_length=100)),
                ('reference_range', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_catalog_items', to='health_ops.healthinstitution')),
            ],
            options={
                'db_table': 'health_ops_lab_catalog_item',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('reference_range', models.CharField(blank=True, default='', max_length=255)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_entered', to='health_ops.healthpractitioner')),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='health_ops.laborder')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_verified', to='health_ops.healthpractitioner')),
            ],
            options={
                'db_table': 'health_ops_lab_result',
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='health_ops.labtestcatalogitem'),
        ),
        migrations.CreateModel(
            name='ClinicalReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_referrals', to='health_ops.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_clinical_referrals', to=settings.AUTH_USER_MODEL)),
                ('receiving_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_referrals_received', to='health_ops.healthinstitution')),
                ('receiving_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_referrals_received', to='health_ops.healthpractitioner')),
                ('referring_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_referrals_made', to='health_ops.healthinstitution')),
                ('referring_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_referrals_made', to='health_ops.healthpractitioner')),
            ],
            options={
                'db_table': 'health_ops_clinical_referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='labtestcatalogitem',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='health_ops_lab_catalog_code_unique'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'status'], name='health_ops__patient_13a4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordering_practitioner', 'status'], name='health_ops__orderin_1a59bb_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'status'], name='health_ops__patient_edcc0a_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['practitioner', 'status'], name='health_ops__practit_2c55f3_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['institution', 'status'], name='health_ops__institu_c693ef_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalreferral',
            index=models.Index(fields=['patient', 'status'], name='health_ops__patient_d7aa47_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalreferral',
            index=models.Index(fields=['receiving_practitioner', 'status'], name='health_ops__receivi_d1c37a_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalreferral',
            index=models.Index(fields=['receiving_institution', 'status'], name='health_ops__receivi_1629d3_idx'),
        ),
    ]
