# Generated by Django 4.2.25 on 2026-10-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_ops', '0023_encounter_laborder_specimen_labtestcatalogitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emedication',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='health_ops.encounter'),
        ),
        migrations.AddField(
            model_name='emedication',
            name='is_revoked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emedication',
            name='prescribing_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='health_ops.healthpractitioner'),
        ),
        migrations.AddField(
            model_name='emedication',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
