# Generated by Django 4.2.25 on 2026-10-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0064_education_program_class_details_and_broadcast'),
        ('health_ops', '0024_emedication_encounter_emedication_is_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinstitution',
            name='legacy_broadcast_institution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ops_institution', to='broadcasts.broadcasthealthinstitution'),
        ),
    ]
