# Generated by Django 4.2.25 on 2026-01-10 05:01

import apps.broadcasts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='broadcastitem',
            new_name='broadcast_i_source__17f53d_idx',
            old_name='broadcast_item_source_t_2c0f87_idx',
        ),
        migrations.RenameIndex(
            model_name='broadcastitem',
            new_name='broadcast_i_expires_4d2fb0_idx',
            old_name='broadcast_item_expires_9f4a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='broadcastreaction',
            new_name='broadcast_r_broadca_11c870_idx',
            old_name='broadcast_react_item_us_4a3b9d_idx',
        ),
        migrations.AlterField(
            model_name='broadcastitem',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=apps.broadcasts.models._default_expires_at),
        ),
    ]
