# Generated by Django 4.2.25 on 2026-01-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_broadcast_features_and_videos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='broadcastfeatureflag',
            new_name='broadcast_f_feature_b65c9e_idx',
            old_name='broadcast_feature_flag_feature_channel_idx',
        ),
    ]
