# Generated by Django 4.2.25 on 2026-01-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0005_broadcast_lessons'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='broadcastlesson',
            new_name='broadcast_l_lesson__2b4344_idx',
            old_name='broadcast_lesson_les_type_idx',
        ),
        migrations.RenameIndex(
            model_name='broadcastlesson',
            new_name='broadcast_l_partner_61d82a_idx',
            old_name='broadcast_lesson_part_idx',
        ),
        migrations.RenameIndex(
            model_name='broadcastlesson',
            new_name='broadcast_l_communi_1cf82c_idx',
            old_name='broadcast_lesson_comm_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonenrollment',
            new_name='lesson_enro_lesson__4029f3_idx',
            old_name='lesson_enrollment_les_user_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonenrollment',
            new_name='lesson_enro_user_id_e3dd38_idx',
            old_name='lesson_enrollment_user_stat_idx',
        ),
    ]
