# Generated by Django 4.2.25 on 2026-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0008_broadcastvideo_mime_type_broadcastvideo_storage_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastvideo',
            name='mime_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='broadcastvideo',
            name='storage_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
