# Generated by Django 4.2.25 on 2026-01-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0010_add_metadata_to_broadcastitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastitem',
            name='source_type',
            field=models.CharField(choices=[('community_post', 'Community Post'), ('partner_post', 'Partner Post'), ('channel_message', 'Channel Message'), ('market_product', 'Market Product'), ('education_course', 'Education Course')], db_index=True, max_length=32),
        ),
    ]
