# Generated by Django 4.2.25 on 2026-02-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0011_alter_broadcastitem_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastitem',
            name='source_type',
            field=models.CharField(choices=[('community_post', 'Community Post'), ('partner_post', 'Partner Post'), ('channel_message', 'Channel Message'), ('broadcast_feed_entry', 'Broadcast Feed Entry'), ('market_product', 'Market Product'), ('education_course', 'Education Course')], db_index=True, max_length=32),
        ),
    ]
