# Generated by Django 4.2.25 on 2026-02-04 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0012_alter_broadcastitem_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('profile_type', models.CharField(choices=[('course', 'Course'), ('degree', 'Degree Program'), ('camp', 'Camp'), ('vocational', 'Vocational Training'), ('workshop', 'Workshop'), ('misc', 'Other')], default='course', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_profile',
            },
        ),
        migrations.CreateModel(
            name='EducationProfileRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='broadcasts.educationprofile')),
            ],
            options={
                'db_table': 'education_profile_role',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationProfileModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('resource_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='broadcasts.educationprofile')),
            ],
            options={
                'db_table': 'education_profile_module',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationProfileCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='broadcasts.educationprofile')),
            ],
            options={
                'db_table': 'education_profile_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationProfileRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='broadcasts.educationprofilerole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_profile_role_assignment',
                'unique_together': {('role', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='educationprofile',
            index=models.Index(fields=['user', 'is_default'], name='education_p_user_id_3a7ace_idx'),
        ),
    ]
