# Generated by Django 4.2.25 on 2026-02-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0013_educationprofile_educationprofilerole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastitem',
            name='source_type',
            field=models.CharField(choices=[('community_post', 'Community Post'), ('partner_post', 'Partner Post'), ('channel_message', 'Channel Message'), ('broadcast_feed_entry', 'Broadcast Feed Entry'), ('market_product', 'Market Product'), ('education_course', 'Education Course'), ('education_profile', 'Education Profile')], db_index=True, max_length=32),
        ),
    ]
