# Generated by Django 4.2.25 on 2026-02-16 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def forwards_link_profiles_and_seed_payloads(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")
    EducationProfile = apps.get_model("broadcasts", "EducationProfile")
    BroadcastFeedProfile = apps.get_model("broadcasts", "BroadcastFeedProfile")
    BroadcastHealthProfile = apps.get_model("broadcasts", "BroadcastHealthProfile")
    BroadcastMarketProfile = apps.get_model("broadcasts", "BroadcastMarketProfile")

    for user in User.objects.all():
        profile = Profile.objects.filter(user_id=user.id).first()
        if not profile:
            continue

        EducationProfile.objects.filter(user_id=user.id, profile_id__isnull=True).update(profile_id=profile.id)

        preferences = getattr(user, "preferences", None) or {}
        if not isinstance(preferences, dict):
            continue
        raw_profiles = preferences.get("profiles") or {}
        if not isinstance(raw_profiles, dict):
            continue

        feed_payload = raw_profiles.get("broadcast_feed")
        if isinstance(feed_payload, dict):
            BroadcastFeedProfile.objects.update_or_create(
                profile_id=profile.id,
                defaults={"payload": feed_payload},
            )

        health_payload = raw_profiles.get("health")
        if isinstance(health_payload, dict):
            BroadcastHealthProfile.objects.update_or_create(
                profile_id=profile.id,
                defaults={"payload": health_payload},
            )

        market_payload = raw_profiles.get("market")
        if isinstance(market_payload, dict):
            BroadcastMarketProfile.objects.update_or_create(
                profile_id=profile.id,
                defaults={"payload": market_payload},
            )


def backwards_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_privacy_everywhere"),
        ("broadcasts", "0014_alter_broadcastitem_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastFeedProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_feed_profile",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_feed_profile",
            },
        ),
        migrations.CreateModel(
            name="BroadcastHealthProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_health_profile",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_health_profile",
            },
        ),
        migrations.CreateModel(
            name="BroadcastMarketProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_market_profile",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_market_profile",
            },
        ),
        migrations.AddField(
            model_name="educationprofile",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcast_education_profiles",
                to="accounts.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="educationprofile",
            index=models.Index(fields=["profile", "is_default"], name="education_p_profile_2af73b_idx"),
        ),
        migrations.RunPython(forwards_link_profiles_and_seed_payloads, backwards_noop),
    ]
