# Generated by Django 4.2.25 on 2026-02-17 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid

MEDIUM_DEFINITIONS = [
    ("Video Consultation Engine", "Secure telehealth sessions with call logs and in-call notes."),
    ("Secure Messaging / Chat Engine", "Asynchronous consultation with text, files, and voice notes."),
    ("E-Prescription Engine", "Digital prescription issuance, drug references, and refill logic."),
    ("Lab Order Engine", "Diagnostic test ordering, sample tracking, and result vaulting."),
    ("Imaging Order Engine", "Radiology ordering, DICOM upload, and imaging review workflows."),
    ("Admission & Bed Management Engine", "Inpatient admission, bed allocation, and ICU flow controls."),
    ("Surgery Scheduling Engine", "Operating room scheduling, pre-op checklists, and team allocation."),
    ("Emergency Dispatch Engine", "SOS triage, ambulance tracking, and ER alerts."),
    ("Pharmacy & Fulfillment Engine", "Drug catalog, dispensing flow, refill subscriptions, and delivery orchestration."),
    ("Payment & Billing Engine", "Consultation billing, split payments, insurance logic, and invoice generation."),
    ("EHR / Health Records Engine", "Unified medical timeline with shareable records and clinical history."),
    ("Home Logistics Engine", "Home pickup/delivery routing and field agent tracking."),
    ("Wellness Program Engine", "Program enrollment, progress metrics, and behavior/habit management."),
    ("Notification & Reminder Engine", "Push, SMS, and email reminders for appointments, meds, and tasks."),
]

DEFAULT_SERVICE_DEFINITIONS = [
    ("General consultation", "Outpatient general consultation."),
    ("Pediatric consultation", "Child-focused clinic consultation."),
    ("Antenatal care", "Prenatal monitoring and care."),
    ("Vaccination", "Routine immunization service."),
    ("Minor procedures", "Low-risk outpatient procedures."),
    ("Teleconsultation", "Remote virtual consultation service."),
    ("Emergency care", "Acute emergency intake and treatment."),
    ("Surgery booking", "Surgical consultation and scheduling."),
    ("Specialist consultation", "Consultation by department specialists."),
    ("Inpatient admission", "Inpatient ward admission workflow."),
    ("ICU", "Critical care service line."),
    ("Maternity", "Maternal and neonatal care services."),
    ("Imaging", "Diagnostic imaging referral service."),
    ("Lab request", "Laboratory test request coordination."),
    ("Blood test", "General blood sampling and analysis."),
    ("Hormone panel", "Hormonal diagnostics panel."),
    ("Full blood count", "Complete blood count processing."),
    ("PCR test", "Molecular PCR diagnostics."),
    ("Urine analysis", "Urinalysis and report generation."),
    ("Home sample pickup", "Home collection logistics."),
    ("X-ray", "Radiographic imaging service."),
    ("MRI", "Magnetic resonance imaging service."),
    ("CT Scan", "Computed tomography service."),
    ("Ultrasound", "Ultrasound scan service."),
    ("Mammogram", "Breast imaging screening service."),
    ("ECG", "Cardiac electrical tracing service."),
    ("Prescription fulfillment", "Prescription verification and dispensing."),
    ("OTC purchase", "Over-the-counter medication sales."),
    ("Chronic medication refill", "Refill workflow for chronic care."),
    ("Home delivery", "Medication delivery logistics."),
    ("Nutrition consultation", "Dietary planning and counseling."),
    ("Fitness program", "Guided fitness and movement plans."),
    ("Stress management session", "Stress reduction coaching."),
    ("Weight loss program", "Weight management program enrollment."),
    ("Mental wellness session", "Mental wellness support session."),
    ("Wellness challenge enrollment", "Challenge and habit program enrollment."),
]

SERVICE_MEDIUM_MAP = {
    "General consultation": [
        "Video Consultation Engine",
        "E-Prescription Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
    ],
    "Pediatric consultation": [
        "E-Prescription Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Antenatal care": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Vaccination": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Minor procedures": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Teleconsultation": [
        "Video Consultation Engine",
        "Secure Messaging / Chat Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Emergency care": [
        "Admission & Bed Management Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
        "Payment & Billing Engine",
    ],
    "Surgery booking": [
        "Admission & Bed Management Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Specialist consultation": [
        "Video Consultation Engine",
        "E-Prescription Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
    ],
    "Inpatient admission": [
        "Admission & Bed Management Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "ICU": [
        "Admission & Bed Management Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Maternity": [
        "Admission & Bed Management Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Imaging": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Lab request": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Blood test": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Hormone panel": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Full blood count": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "PCR test": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Urine analysis": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Home sample pickup": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "X-ray": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "MRI": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "CT Scan": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Ultrasound": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Mammogram": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "ECG": [
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Prescription fulfillment": [
        "Pharmacy & Fulfillment Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "OTC purchase": [
        "Pharmacy & Fulfillment Engine",
        "Payment & Billing Engine",
        "Notification & Reminder Engine",
    ],
    "Chronic medication refill": [
        "E-Prescription Engine",
        "Pharmacy & Fulfillment Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Home delivery": [
        "Pharmacy & Fulfillment Engine",
        "Payment & Billing Engine",
        "Notification & Reminder Engine",
    ],
    "Nutrition consultation": [
        "Wellness Program Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Fitness program": [
        "Wellness Program Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Stress management session": [
        "Secure Messaging / Chat Engine",
        "Wellness Program Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
    ],
    "Weight loss program": [
        "Wellness Program Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Mental wellness session": [
        "Video Consultation Engine",
        "Secure Messaging / Chat Engine",
        "Wellness Program Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
    "Wellness challenge enrollment": [
        "Wellness Program Engine",
        "Payment & Billing Engine",
        "EHR / Health Records Engine",
        "Notification & Reminder Engine",
    ],
}


def seed_medium_service_architecture(apps, schema_editor):
    Medium = apps.get_model("broadcasts", "Medium")
    Service = apps.get_model("broadcasts", "Service")
    ServiceMediumMap = apps.get_model("broadcasts", "ServiceMediumMap")

    medium_by_name = {}
    for name, description in MEDIUM_DEFINITIONS:
        medium, _ = Medium.objects.get_or_create(
            name=name,
            defaults={
                "description": description,
                "system_flag": True,
            },
        )
        medium_by_name[name] = medium

    for name, description in DEFAULT_SERVICE_DEFINITIONS:
        service, _ = Service.objects.get_or_create(
            name=name,
            created_by=None,
            defaults={
                "description": description,
                "is_default": True,
            },
        )
        if not service.is_default:
            service.is_default = True
            service.save(update_fields=["is_default"])

        mapped_mediums = SERVICE_MEDIUM_MAP.get(name, [])
        for medium_name in mapped_mediums:
            medium = medium_by_name.get(medium_name)
            if not medium:
                continue
            ServiceMediumMap.objects.get_or_create(service=service, medium=medium)


def rollback_medium_service_architecture(apps, schema_editor):
    Medium = apps.get_model("broadcasts", "Medium")
    Service = apps.get_model("broadcasts", "Service")
    ServiceMediumMap = apps.get_model("broadcasts", "ServiceMediumMap")

    service_names = [name for name, _ in DEFAULT_SERVICE_DEFINITIONS]
    medium_names = [name for name, _ in MEDIUM_DEFINITIONS]

    services = Service.objects.filter(created_by__isnull=True, name__in=service_names)
    ServiceMediumMap.objects.filter(service__in=services).delete()
    services.delete()
    Medium.objects.filter(name__in=medium_names, system_flag=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0015_broadcast_profile_tables_and_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('system_flag', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mediums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_health_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMediumMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='broadcasts.medium')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium_links', to='broadcasts.service')),
            ],
            options={
                'db_table': 'service_medium_map',
            },
        ),
        migrations.AddConstraint(
            model_name='servicemediummap',
            constraint=models.UniqueConstraint(fields=('service', 'medium'), name='service_medium_unique'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='service_name_per_creator_uniq'),
        ),
        migrations.RunPython(seed_medium_service_architecture, rollback_medium_service_architecture),
    ]
