# Generated by Codex on 2026-03-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def _safe_text(value, default=""):
    text = str(value or "").strip()
    return text if text else default


def _safe_positive_int(value, default=0):
    try:
        parsed = int(float(value))
    except (TypeError, ValueError):
        return default
    return parsed if parsed >= 0 else default


def _safe_bool(value, default=False):
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    raw = str(value).strip().lower()
    if raw in {"1", "true", "yes", "y", "on"}:
        return True
    if raw in {"0", "false", "no", "n", "off"}:
        return False
    return default


def _safe_list(value):
    return value if isinstance(value, list) else []


def _safe_dict(value):
    return value if isinstance(value, dict) else {}


def forwards_seed_health_profile_tables(apps, schema_editor):
    BroadcastHealthProfile = apps.get_model("broadcasts", "BroadcastHealthProfile")
    BroadcastHealthInstitution = apps.get_model("broadcasts", "BroadcastHealthInstitution")
    BroadcastHealthInstitutionMember = apps.get_model("broadcasts", "BroadcastHealthInstitutionMember")
    BroadcastHealthInstitutionService = apps.get_model("broadcasts", "BroadcastHealthInstitutionService")

    for health_profile in BroadcastHealthProfile.objects.all():
        payload = health_profile.payload if isinstance(health_profile.payload, dict) else {}
        raw_institutions = _safe_list(payload.get("institutions"))
        keep_institutions = set()

        for idx, raw_inst in enumerate(raw_institutions):
            institution = _safe_dict(raw_inst)
            institution_uid = _safe_text(
                institution.get("id")
                or institution.get("institution_id")
                or institution.get("institutionId")
                or f"inst-{idx + 1}"
            )
            if not institution_uid or institution_uid in keep_institutions:
                continue
            keep_institutions.add(institution_uid)

            owner_contact = _safe_dict(institution.get("owner_contact"))
            if not owner_contact:
                owner_contact = _safe_dict(institution.get("ownerContact"))

            membership_settings = _safe_dict(institution.get("membership_settings"))
            if not membership_settings:
                membership_settings = _safe_dict(institution.get("membershipSettings"))

            membership_open = _safe_bool(
                membership_settings.get("open")
                if "open" in membership_settings
                else institution.get("membership_open", institution.get("membershipOpen")),
                False,
            )
            membership_discount_pct = _safe_positive_int(
                membership_settings.get("discountPercent")
                if "discountPercent" in membership_settings
                else institution.get("membership_discount_pct", institution.get("membershipDiscountPct")),
                10,
            )
            if membership_discount_pct < 10:
                membership_discount_pct = 10
            if membership_discount_pct > 100:
                membership_discount_pct = 100

            metadata = dict(institution)
            for key in (
                "id",
                "institution_id",
                "institutionId",
                "type",
                "name",
                "employees",
                "members",
                "services",
                "owner_contact",
                "ownerContact",
                "members_target_count",
                "membersTargetCount",
                "membership_open",
                "membershipOpen",
                "membership_discount_pct",
                "membershipDiscountPct",
                "membership_settings",
                "membershipSettings",
            ):
                metadata.pop(key, None)

            owner_user_id = _safe_text(owner_contact.get("userId") or owner_contact.get("user_id"))
            if not owner_user_id:
                owner_user_id = None

            institution_row, _ = BroadcastHealthInstitution.objects.update_or_create(
                health_profile=health_profile,
                institution_uid=institution_uid,
                defaults={
                    "institution_type": _safe_text(institution.get("type"), "clinic"),
                    "name": _safe_text(institution.get("name"), "Health Institution"),
                    "owner_user_id": owner_user_id,
                    "owner_name": _safe_text(owner_contact.get("name")),
                    "owner_phone": _safe_text(owner_contact.get("phone")),
                    "owner_email": _safe_text(owner_contact.get("email")),
                    "members_target_count": _safe_positive_int(
                        institution.get("members_target_count") or institution.get("membersTargetCount"),
                        1,
                    ),
                    "membership_open": membership_open,
                    "membership_discount_pct": membership_discount_pct,
                    "metadata": metadata,
                },
            )

            raw_members = _safe_list(institution.get("members"))
            if not raw_members:
                raw_members = _safe_list(institution.get("employees"))
            keep_members = set()
            for member_idx, raw_member in enumerate(raw_members):
                member = _safe_dict(raw_member)
                member_uid = _safe_text(member.get("id") or f"worker-{member_idx + 1}")
                if not member_uid or member_uid in keep_members:
                    continue
                keep_members.add(member_uid)

                member_metadata = dict(member)
                for key in ("id", "name", "role", "phone", "email", "userId", "user_id"):
                    member_metadata.pop(key, None)

                member_user_id = _safe_text(member.get("userId") or member.get("user_id"))
                if not member_user_id:
                    member_user_id = None

                BroadcastHealthInstitutionMember.objects.update_or_create(
                    institution=institution_row,
                    member_uid=member_uid,
                    defaults={
                        "name": _safe_text(member.get("name"), "Worker"),
                        "role": _safe_text(member.get("role"), "staff"),
                        "phone": _safe_text(member.get("phone")),
                        "email": _safe_text(member.get("email")),
                        "user_id": member_user_id,
                        "metadata": member_metadata,
                    },
                )
            if keep_members:
                BroadcastHealthInstitutionMember.objects.filter(institution=institution_row).exclude(member_uid__in=keep_members).delete()
            else:
                BroadcastHealthInstitutionMember.objects.filter(institution=institution_row).delete()

            raw_services = _safe_list(institution.get("services"))
            keep_services = set()
            for service_idx, raw_service in enumerate(raw_services):
                service = _safe_dict(raw_service)
                service_uid = _safe_text(service.get("id") or service.get("service_id") or f"service-{service_idx + 1}")
                if not service_uid or service_uid in keep_services:
                    continue
                keep_services.add(service_uid)

                service_metadata = dict(service)
                for key in (
                    "id",
                    "service_id",
                    "name",
                    "description",
                    "active",
                    "basePriceCents",
                    "medium_ids",
                    "mediumIds",
                    "medium_names",
                    "mediumNames",
                ):
                    service_metadata.pop(key, None)

                base_price_cents = service.get("basePriceCents")
                if base_price_cents is not None:
                    base_price_cents = _safe_positive_int(base_price_cents, None)

                medium_ids = [str(item or "").strip() for item in _safe_list(service.get("medium_ids") or service.get("mediumIds")) if str(item or "").strip()]
                medium_names = [str(item or "").strip() for item in _safe_list(service.get("medium_names") or service.get("mediumNames")) if str(item or "").strip()]

                BroadcastHealthInstitutionService.objects.update_or_create(
                    institution=institution_row,
                    service_uid=service_uid,
                    defaults={
                        "name": _safe_text(service.get("name"), f"Service {service_idx + 1}"),
                        "description": _safe_text(service.get("description")),
                        "active": _safe_bool(service.get("active"), True),
                        "base_price_cents": base_price_cents,
                        "medium_ids": medium_ids,
                        "medium_names": medium_names,
                        "metadata": service_metadata,
                    },
                )
            if keep_services:
                BroadcastHealthInstitutionService.objects.filter(institution=institution_row).exclude(service_uid__in=keep_services).delete()
            else:
                BroadcastHealthInstitutionService.objects.filter(institution=institution_row).delete()

        if keep_institutions:
            BroadcastHealthInstitution.objects.filter(health_profile=health_profile).exclude(institution_uid__in=keep_institutions).delete()
        else:
            BroadcastHealthInstitution.objects.filter(health_profile=health_profile).delete()

        slim_payload = dict(payload)
        for key in (
            "institutions",
            "employees_total",
            "owned_institutions",
            "ownedInstitutions",
            "member_institutions",
            "memberInstitutions",
            "viewer_access_mode",
            "viewerAccessMode",
            "has_owner_profile",
            "hasOwnerProfile",
        ):
            slim_payload.pop(key, None)

        health_profile.payload = slim_payload
        health_profile.save(update_fields=["payload", "updated_at"])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("broadcasts", "0016_medium_service_servicemediummap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastHealthInstitution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("institution_uid", models.CharField(db_index=True, max_length=128)),
                ("institution_type", models.CharField(default="clinic", max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("owner_name", models.CharField(blank=True, default="", max_length=255)),
                ("owner_phone", models.CharField(blank=True, default="", max_length=64)),
                ("owner_email", models.CharField(blank=True, default="", max_length=255)),
                ("members_target_count", models.PositiveIntegerField(default=1)),
                ("membership_open", models.BooleanField(default=False)),
                ("membership_discount_pct", models.PositiveIntegerField(default=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "health_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_rows",
                        to="broadcasts.broadcasthealthprofile",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_health_institutions_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_health_institution",
            },
        ),
        migrations.CreateModel(
            name="BroadcastHealthInstitutionMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("member_uid", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(default="staff", max_length=64)),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_rows",
                        to="broadcasts.broadcasthealthinstitution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_health_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_health_institution_member",
            },
        ),
        migrations.CreateModel(
            name="BroadcastHealthInstitutionService",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("service_uid", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("base_price_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("medium_ids", models.JSONField(blank=True, default=list)),
                ("medium_names", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_rows",
                        to="broadcasts.broadcasthealthinstitution",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_health_institution_service",
            },
        ),
        migrations.AddConstraint(
            model_name="broadcasthealthinstitution",
            constraint=models.UniqueConstraint(
                fields=("health_profile", "institution_uid"),
                name="broadcast_health_institution_unique_profile_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcasthealthinstitutionmember",
            constraint=models.UniqueConstraint(
                fields=("institution", "member_uid"),
                name="broadcast_health_member_unique_institution_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcasthealthinstitutionservice",
            constraint=models.UniqueConstraint(
                fields=("institution", "service_uid"),
                name="broadcast_health_service_unique_institution_uid",
            ),
        ),
        migrations.AddIndex(
            model_name="broadcasthealthinstitution",
            index=models.Index(fields=["health_profile", "institution_uid"], name="broadcast_h_health__bcb814_idx"),
        ),
        migrations.AddIndex(
            model_name="broadcasthealthinstitution",
            index=models.Index(fields=["owner_user"], name="broadcast_h_owner_u_d563e7_idx"),
        ),
        migrations.AddIndex(
            model_name="broadcasthealthinstitutionmember",
            index=models.Index(fields=["institution", "member_uid"], name="broadcast_h_institu_f07731_idx"),
        ),
        migrations.AddIndex(
            model_name="broadcasthealthinstitutionmember",
            index=models.Index(fields=["user"], name="broadcast_h_user_id_4d2980_idx"),
        ),
        migrations.AddIndex(
            model_name="broadcasthealthinstitutionservice",
            index=models.Index(fields=["institution", "service_uid"], name="broadcast_h_institu_fd5fcb_idx"),
        ),
        migrations.RunPython(forwards_seed_health_profile_tables, backwards_noop),
    ]
