# Generated by Django 4.2.25 on 2026-04-17 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_profilearticleallowtarget_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0019_alter_broadcastitem_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('academy', 'Academy'), ('training_center', 'Training Center'), ('bootcamp', 'Bootcamp'), ('community', 'Community'), ('other', 'Other')], default='academy', max_length=32)),
                ('membership_policy', models.CharField(choices=[('open', 'Open Membership'), ('application', 'Application Required'), ('closed', 'Closed Membership')], default='application', max_length=16)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_education_institutions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_institutions', to='accounts.profile')),
            ],
            options={
                'db_table': 'education_institution',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('administrator', 'Administrator'), ('lecturer', 'Lecturer'), ('academic_staff', 'Academic Staff'), ('student', 'Student')], default='student', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('invited', 'Invited'), ('removed', 'Removed')], default='pending', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_education_institution_memberships', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_education_institution_memberships', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='broadcasts.educationinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_institution_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_institution_membership',
                'indexes': [models.Index(fields=['institution', 'status'], name='education_i_institu_9f6818_idx'), models.Index(fields=['institution', 'role'], name='education_i_institu_c100ef_idx'), models.Index(fields=['user', 'status'], name='education_i_user_id_90135a_idx')],
                'unique_together': {('institution', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='educationinstitution',
            index=models.Index(fields=['owner', 'is_active'], name='education_i_owner_i_c9465d_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitution',
            index=models.Index(fields=['institution_type', 'is_active'], name='education_i_institu_86ecf4_idx'),
        ),
    ]
