# Generated by Django 4.2.25 on 2026-04-17 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0020_educationinstitution_educationinstitutionmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitutionCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_v2', to='broadcasts.educationinstitution')),
            ],
            options={
                'db_table': 'education_institution_course',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('lesson_order', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='broadcasts.educationinstitutioncourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_v2', to='broadcasts.educationinstitution')),
            ],
            options={
                'db_table': 'education_institution_lesson',
                'ordering': ['lesson_order', 'title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='broadcasts.educationinstitution')),
            ],
            options={
                'db_table': 'education_institution_program',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'Link'), ('slides', 'Slides'), ('assignment', 'Assignment'), ('reference', 'Reference')], default='document', max_length=16)),
                ('resource_url', models.URLField(blank=True, default='')),
                ('storage_path', models.CharField(blank=True, default='', max_length=512)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='broadcasts.educationinstitutioncourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='broadcasts.educationinstitution')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='broadcasts.educationinstitutionlesson')),
            ],
            options={
                'db_table': 'education_institution_material',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='educationinstitutioncourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.CreateModel(
            name='EducationInstitutionClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone_name', models.CharField(blank=True, default='UTC', max_length=64)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], default='online', max_length=16)),
                ('location_text', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_url', models.URLField(blank=True, default='')),
                ('seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='broadcasts.educationinstitutioncourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='broadcasts.educationinstitution')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='broadcasts.educationinstitutionlesson')),
            ],
            options={
                'db_table': 'education_institution_class_session',
                'ordering': ['starts_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='educationinstitutionprogram',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_94f819_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionprogram',
            index=models.Index(fields=['institution', 'code'], name='education_i_institu_9dea19_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionmaterial',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_18cf79_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionmaterial',
            index=models.Index(fields=['course', 'status'], name='education_i_course__ae4ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionmaterial',
            index=models.Index(fields=['lesson', 'status'], name='education_i_lesson__d9e69e_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionlesson',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_892961_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionlesson',
            index=models.Index(fields=['course', 'lesson_order'], name='education_i_course__282d41_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncourse',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_127160_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncourse',
            index=models.Index(fields=['institution', 'code'], name='education_i_institu_348171_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncourse',
            index=models.Index(fields=['program', 'status'], name='education_i_program_0f0193_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionclasssession',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_7dbc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionclasssession',
            index=models.Index(fields=['institution', 'starts_at'], name='education_i_institu_b72d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionclasssession',
            index=models.Index(fields=['course', 'starts_at'], name='education_i_course__d3b2b3_idx'),
        ),
    ]
