# Generated by Django 4.2.25 on 2026-04-17 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0021_educationinstitutioncourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitutionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('assessment_type', models.CharField(choices=[('mcq', 'MCQ'), ('theory', 'Theory'), ('mixed', 'Mixed')], default='mcq', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('passing_score_percent', models.PositiveIntegerField(default=0)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='broadcasts.educationinstitutionclasssession')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='broadcasts.educationinstitutioncourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='broadcasts.educationinstitution')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='broadcasts.educationinstitutionlesson')),
            ],
            options={
                'db_table': 'education_institution_assessment',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionAssessmentOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('option_order', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'education_institution_assessment_option',
                'ordering': ['option_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionAssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mcq', max_length=16)),
                ('question_order', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('is_required', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='broadcasts.educationinstitutionassessment')),
            ],
            options={
                'db_table': 'education_institution_assessment_question',
                'ordering': ['question_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionAssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grader_feedback', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='broadcasts.educationinstitutionassessmentquestion')),
            ],
            options={
                'db_table': 'education_institution_assessment_response',
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionAssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='started', max_length=16)),
                ('earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grader_feedback', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='broadcasts.educationinstitutionassessment')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_education_assessment_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_assessment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_institution_assessment_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionAssessmentResponseOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_links', to='broadcasts.educationinstitutionassessmentoption')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='broadcasts.educationinstitutionassessmentresponse')),
            ],
            options={
                'db_table': 'education_institution_assessment_response_option',
            },
        ),
        migrations.AddField(
            model_name='educationinstitutionassessmentresponse',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='broadcasts.educationinstitutionassessmentsubmission'),
        ),
        migrations.AddField(
            model_name='educationinstitutionassessmentoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='broadcasts.educationinstitutionassessmentquestion'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessmentsubmission',
            index=models.Index(fields=['assessment', 'status'], name='education_i_assessm_f06028_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessmentsubmission',
            index=models.Index(fields=['user', 'status'], name='education_i_user_id_79d957_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='educationinstitutionassessmentsubmission',
            unique_together={('assessment', 'user', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessmentresponseoption',
            index=models.Index(fields=['response', 'option'], name='education_i_respons_c59244_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='educationinstitutionassessmentresponseoption',
            unique_together={('response', 'option')},
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessmentresponse',
            index=models.Index(fields=['submission', 'question'], name='education_i_submiss_f99bdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='educationinstitutionassessmentresponse',
            unique_together={('submission', 'question')},
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessmentquestion',
            index=models.Index(fields=['assessment', 'question_order'], name='education_i_assessm_1f9016_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessmentquestion',
            index=models.Index(fields=['assessment', 'question_type'], name='education_i_assessm_a14130_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessmentoption',
            index=models.Index(fields=['question', 'option_order'], name='education_i_questio_e6ab4e_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessment',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_837fba_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessment',
            index=models.Index(fields=['course', 'status'], name='education_i_course__e5db2c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessment',
            index=models.Index(fields=['lesson', 'status'], name='education_i_lesson__df473a_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionassessment',
            index=models.Index(fields=['class_session', 'status'], name='education_i_class_s_4b19cc_idx'),
        ),
    ]
