# Generated by Django 4.2.25 on 2026-04-17 08:11

import apps.broadcasts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0022_educationinstitutionassessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastitem',
            name='source_type',
            field=models.CharField(choices=[('community_post', 'Community Post'), ('partner_post', 'Partner Post'), ('channel_message', 'Channel Message'), ('broadcast_feed_entry', 'Broadcast Feed Entry'), ('market_product', 'Market Product'), ('market_service', 'Market Service'), ('education_course', 'Education Course'), ('education_profile', 'Education Profile'), ('education_broadcast', 'Education Broadcast')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='EducationInstitutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('training_session', 'Training Session')], default='event', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone_name', models.CharField(blank=True, default='UTC', max_length=64)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], default='online', max_length=16)),
                ('location_text', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_url', models.URLField(blank=True, default='')),
                ('seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='broadcasts.educationinstitution')),
            ],
            options={
                'db_table': 'education_institution_event',
                'ordering': ['starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broadcast_kind', models.CharField(choices=[('course', 'Course'), ('lesson', 'Lesson'), ('class_session', 'Class Session'), ('training_session', 'Training Session'), ('event', 'Event')], max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_name', models.CharField(blank=True, default='UTC', max_length=64)),
                ('seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_enabled', models.BooleanField(default=False)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_currency', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=16)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=apps.broadcasts.models._default_expires_at)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_broadcast_row', to='broadcasts.broadcastitem')),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='broadcasts.educationinstitutionclasssession')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='broadcasts.educationinstitutioncourse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_broadcasts_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='broadcasts.educationinstitutionevent')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_broadcasts', to='broadcasts.educationinstitution')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='broadcasts.educationinstitutionlesson')),
            ],
            options={
                'db_table': 'education_institution_broadcast',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='educationinstitutionevent',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_b60eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionevent',
            index=models.Index(fields=['institution', 'event_type'], name='education_i_institu_bffd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionevent',
            index=models.Index(fields=['institution', 'starts_at'], name='education_i_institu_df209f_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbroadcast',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_badc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbroadcast',
            index=models.Index(fields=['institution', 'broadcast_kind'], name='education_i_institu_3b0c01_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbroadcast',
            index=models.Index(fields=['published_at'], name='education_i_publish_169f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbroadcast',
            index=models.Index(fields=['expires_at'], name='education_i_expires_7bef8e_idx'),
        ),
    ]
