# Generated by Django 4.2.25 on 2026-04-17 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_alter_walletledgerentry_kind'),
        ('broadcasts', '0023_alter_broadcastitem_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitutionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='broadcasts.educationinstitutionbroadcast')),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='broadcasts.educationinstitutionclasssession')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='broadcasts.educationinstitutioncourse')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='broadcasts.educationinstitutionevent')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='broadcasts.educationinstitution')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='broadcasts.educationinstitutionlesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_institution_enrollment',
                'indexes': [models.Index(fields=['institution', 'status'], name='education_i_institu_292cc1_idx'), models.Index(fields=['broadcast', 'status'], name='education_i_broadca_8aba61_idx'), models.Index(fields=['user', 'status'], name='education_i_user_id_088197_idx')],
                'unique_together': {('broadcast', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=24)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='broadcasts.educationinstitutionbroadcast')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='broadcasts.educationinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_bookings', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_bookings', to='billing.wallettransaction')),
            ],
            options={
                'db_table': 'education_institution_booking',
                'indexes': [models.Index(fields=['institution', 'status'], name='education_i_institu_040c80_idx'), models.Index(fields=['broadcast', 'status'], name='education_i_broadca_9357ba_idx'), models.Index(fields=['user', 'status'], name='education_i_user_id_bd3ffe_idx')],
                'unique_together': {('broadcast', 'user')},
            },
        ),
    ]
