# Generated by Django 4.2.25 on 2026-04-17 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0024_educationinstitutionenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitutionStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('coordinator', 'Coordinator'), ('examiner', 'Examiner'), ('advisor', 'Advisor'), ('moderator', 'Moderator'), ('event_host', 'Event Host')], default='instructor', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'education_institution_staff_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='broadcasts.educationinstitutionclasssession'),
        ),
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='broadcasts.educationinstitutioncourse'),
        ),
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='broadcasts.educationinstitutionevent'),
        ),
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.AddField(
            model_name='educationinstitutionbroadcast',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.AddField(
            model_name='educationinstitutionenrollment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.AddField(
            model_name='educationinstitutionevent',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='broadcasts.educationinstitutionclasssession'),
        ),
        migrations.AddField(
            model_name='educationinstitutionevent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='broadcasts.educationinstitutioncourse'),
        ),
        migrations.AddField(
            model_name='educationinstitutionevent',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='broadcasts.educationinstitutionassessment'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='broadcasts.educationinstitutionclasssession'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='resource_mime_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='resource_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='educationinstitutionbroadcast',
            name='broadcast_kind',
            field=models.CharField(choices=[('program', 'Program'), ('course', 'Course'), ('lesson', 'Lesson'), ('class_session', 'Class Session'), ('training_session', 'Training Session'), ('event', 'Event'), ('institution_notice', 'Institution Notice')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbooking',
            index=models.Index(fields=['program', 'status'], name='education_i_program_3bb0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbooking',
            index=models.Index(fields=['course', 'status'], name='education_i_course__f6d2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbooking',
            index=models.Index(fields=['class_session', 'status'], name='education_i_class_s_ef2340_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbooking',
            index=models.Index(fields=['event', 'status'], name='education_i_event_i_a751fb_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbroadcast',
            index=models.Index(fields=['program', 'status'], name='education_i_program_f057a1_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionenrollment',
            index=models.Index(fields=['program', 'status'], name='education_i_program_1a6f87_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionevent',
            index=models.Index(fields=['program', 'status'], name='education_i_program_408bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionevent',
            index=models.Index(fields=['course', 'status'], name='education_i_course__c6fd81_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionevent',
            index=models.Index(fields=['class_session', 'status'], name='education_i_class_s_7efbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionmaterial',
            index=models.Index(fields=['program', 'status'], name='education_i_program_69963e_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionmaterial',
            index=models.Index(fields=['class_session', 'status'], name='education_i_class_s_1e4604_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionmaterial',
            index=models.Index(fields=['assessment', 'status'], name='education_i_assessm_a758f9_idx'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='broadcasts.educationinstitutionassessment'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='broadcasts.educationinstitutionclasssession'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='broadcasts.educationinstitutioncourse'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_education_staff_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='broadcasts.educationinstitutionevent'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='broadcasts.educationinstitution'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='broadcasts.educationinstitutionmembership'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionstaffassignment',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_20f3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionstaffassignment',
            index=models.Index(fields=['membership', 'status'], name='education_i_members_f9196f_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionstaffassignment',
            index=models.Index(fields=['course', 'status'], name='education_i_course__b1af1e_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionstaffassignment',
            index=models.Index(fields=['class_session', 'status'], name='education_i_class_s_dbb782_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionstaffassignment',
            index=models.Index(fields=['event', 'status'], name='education_i_event_i_0893a1_idx'),
        ),
    ]
