# Generated by Django 4.2.25 on 2026-04-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_walletledgerentry_kind'),
        ('broadcasts', '0025_educationinstitutionstaffassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='payer_satisfied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='provider_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='provider_credit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_booking_provider_payouts', to='billing.wallettransaction'),
        ),
        migrations.AddField(
            model_name='educationinstitutionbooking',
            name='satisfaction_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationinstitutionbooking',
            name='currency',
            field=models.CharField(default='KISC', max_length=8),
        ),
        migrations.AlterField(
            model_name='educationinstitutionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('awaiting_satisfaction', 'Awaiting Satisfaction'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='educationinstitutionbroadcast',
            name='price_currency',
            field=models.CharField(blank=True, default='KISC', max_length=8),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbooking',
            index=models.Index(fields=['satisfaction_deadline'], name='education_i_satisfa_8a78c7_idx'),
        ),
    ]
