# Generated by Django 4.2.25 on 2026-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0026_educationinstitutionbooking_payer_satisfied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='assessment_links',
            field=models.ManyToManyField(blank=True, related_name='linked_materials', to='broadcasts.educationinstitutionassessment'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='class_session_links',
            field=models.ManyToManyField(blank=True, related_name='linked_materials', to='broadcasts.educationinstitutionclasssession'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='course_links',
            field=models.ManyToManyField(blank=True, related_name='linked_materials', to='broadcasts.educationinstitutioncourse'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='lesson_links',
            field=models.ManyToManyField(blank=True, related_name='linked_materials', to='broadcasts.educationinstitutionlesson'),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='program_links',
            field=models.ManyToManyField(blank=True, related_name='linked_materials', to='broadcasts.educationinstitutionprogram'),
        ),
    ]
