# Generated by Django 4.2.25 on 2026-04-18 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0027_educationinstitutionmaterial_assessment_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitutionCourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('module_order', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_v2', to='broadcasts.educationinstitutioncourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='broadcasts.educationinstitution')),
            ],
            options={
                'db_table': 'education_institution_course_module',
                'ordering': ['module_order', 'title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutionCourseModuleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('lesson', 'Lesson'), ('material', 'Material'), ('class_session', 'Class Session'), ('assessment', 'Assessment'), ('event', 'Event'), ('broadcast', 'Broadcast')], default='lesson', max_length=24)),
                ('item_order', models.PositiveIntegerField(default=0)),
                ('title_override', models.CharField(blank=True, default='', max_length=255)),
                ('summary_override', models.TextField(blank=True, default='')),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='broadcasts.educationinstitutionassessment')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='broadcasts.educationinstitutionbroadcast')),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='broadcasts.educationinstitutionclasssession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='broadcasts.educationinstitutioncourse')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='broadcasts.educationinstitutionevent')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_module_items', to='broadcasts.educationinstitution')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='broadcasts.educationinstitutionlesson')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='broadcasts.educationinstitutionmaterial')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='broadcasts.educationinstitutioncoursemodule')),
            ],
            options={
                'db_table': 'education_institution_course_module_item',
                'ordering': ['item_order', 'created_at'],
                'indexes': [models.Index(fields=['institution', 'item_type'], name='education_i_institu_1b7161_idx'), models.Index(fields=['course', 'item_order'], name='education_i_course__020b47_idx'), models.Index(fields=['module', 'item_order'], name='education_i_module__abdeda_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncoursemodule',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_6c9211_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncoursemodule',
            index=models.Index(fields=['course', 'module_order'], name='education_i_course__9cfae3_idx'),
        ),
    ]
