# Generated by Django 4.2.25 on 2026-04-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0028_educationinstitutioncoursemodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitutionassessment',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutionclasssession',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourse',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutionevent',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutionlesson',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutionmaterial',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
