# Generated by Django 4.2.25 on 2026-05-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0030_broadcast_engagement_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinstitutionbooking',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='educationinstitutionbroadcast',
            name='price_currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
    ]
