# Generated by Django 4.2.25 on 2026-05-12 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0031_alter_educationinstitutionbooking_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('health', 'Health institution'), ('education', 'Education institution'), ('partner', 'Partner organization')], db_index=True, max_length=24)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('handle', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('banner_url', models.URLField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('links', models.JSONField(blank=True, default=list)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('verification_badges', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('content_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_broadcast_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_channel',
            },
        ),
        migrations.CreateModel(
            name='BroadcastPlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='broadcasts.broadcastchannel')),
            ],
            options={
                'db_table': 'broadcast_playlist',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['channel', 'visibility'], name='broadcast_p_channel_de2fab_idx'), models.Index(fields=['channel', 'sort_order'], name='broadcast_p_channel_4238ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='BroadcastChannelSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.CharField(choices=[('none', 'None'), ('personalized', 'Personalized'), ('all', 'All')], default='personalized', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='broadcasts.broadcastchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_channel_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_channel_subscription',
                'indexes': [models.Index(fields=['channel', 'notifications'], name='broadcast_c_channel_b584a7_idx'), models.Index(fields=['user', 'notifications'], name='broadcast_c_user_id_9d86ce_idx')],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BroadcastChannelRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('editor', 'Editor'), ('moderator', 'Moderator'), ('analyst', 'Analyst')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='broadcasts.broadcastchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_channel_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_channel_role',
                'indexes': [models.Index(fields=['channel', 'role'], name='broadcast_c_channel_83492c_idx'), models.Index(fields=['user', 'role'], name='broadcast_c_user_id_daf366_idx')],
                'unique_together': {('channel', 'user', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='broadcastchannel',
            index=models.Index(fields=['owner_type', 'owner_id'], name='broadcast_c_owner_t_02eb13_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastchannel',
            index=models.Index(fields=['handle'], name='broadcast_c_handle_975573_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastchannel',
            index=models.Index(fields=['is_public', 'is_deleted'], name='broadcast_c_is_publ_40c430_idx'),
        ),
        migrations.AddConstraint(
            model_name='broadcastchannel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('handle'), name='broadcast_channel_handle_ci_unique'),
        ),
    ]
