# Generated by Django 4.2.25 on 2026-05-12 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0032_broadcastchannel_broadcastplaylist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_feed_entry_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('short_video', 'Short video'), ('image', 'Image'), ('gallery', 'Gallery'), ('text', 'Text'), ('rich_text', 'Rich text'), ('audio', 'Audio'), ('document', 'Document'), ('link', 'Link'), ('poll', 'Poll'), ('event', 'Event'), ('live_stream', 'Live stream'), ('replay', 'Replay')], db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('text_plain', models.TextField(blank=True, default='')),
                ('text_doc', models.JSONField(blank=True, default=dict)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], db_index=True, default='public', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('processing', 'Processing'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='broadcasts.broadcastchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_contents', to=settings.AUTH_USER_MODEL)),
                ('legacy_broadcast_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_content', to='broadcasts.broadcastitem')),
            ],
            options={
                'db_table': 'channel_content',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=32)),
                ('url', models.URLField(blank=True, default='')),
                ('storage_path', models.CharField(blank=True, default='', max_length=512)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(default='ready', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_asset',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['content', 'asset_type'], name='channel_con_content_9c1e07_idx'), models.Index(fields=['processing_status'], name='channel_con_process_7539d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='channelcontent',
            index=models.Index(fields=['channel', 'status', 'published_at'], name='channel_con_channel_3bf5db_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontent',
            index=models.Index(fields=['content_type', 'status'], name='channel_con_content_031413_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontent',
            index=models.Index(fields=['visibility', 'is_deleted'], name='channel_con_visibil_d87666_idx'),
        ),
    ]
