# Generated by Django 4.2.25 on 2026-05-12 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0033_channelcontent_channelcontentasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLiveStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=24)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_stream_id', models.CharField(blank=True, default='', max_length=160)),
                ('ingest_url', models.CharField(blank=True, default='', max_length=512)),
                ('stream_key_hash', models.CharField(blank=True, default='', max_length=128)),
                ('playback_url', models.URLField(blank=True, default='')),
                ('replay_url', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('peak_viewer_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='broadcasts.broadcastchannel')),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_stream', to='broadcasts.channelcontent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_live_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_live_stream',
                'indexes': [models.Index(fields=['channel', 'status', 'scheduled_start_at'], name='channel_liv_channel_af3e41_idx'), models.Index(fields=['provider', 'provider_stream_id'], name='channel_liv_provide_c29ad5_idx'), models.Index(fields=['status', 'created_at'], name='channel_liv_status_0d274b_idx')],
            },
        ),
    ]
