# Generated by Django 4.2.25 on 2026-05-12 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0034_channellivestream'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelEmbedPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_embeds', models.BooleanField(default=True)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('blocked_domains', models.JSONField(blank=True, default=list)),
                ('require_signed_token', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embed_policy', to='broadcasts.broadcastchannel')),
            ],
            options={
                'db_table': 'channel_embed_policy',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentEmbed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='broadcasts.channelcontent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_content_embeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_embed',
                'indexes': [models.Index(fields=['content', 'is_active'], name='channel_con_content_8ac9d6_idx'), models.Index(fields=['domain', 'is_active'], name='channel_con_domain_7d2eb9_idx'), models.Index(fields=['expires_at'], name='channel_con_expires_639605_idx')],
            },
        ),
    ]
