# Generated by Django 4.2.25 on 2026-05-12 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0035_channelembedpolicy_channelcontentembed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelWatchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='broadcasts.channelcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_watch_history',
                'indexes': [models.Index(fields=['content', 'last_viewed_at'], name='channel_wat_content_fb10e5_idx'), models.Index(fields=['user', 'last_viewed_at'], name='channel_wat_user_id_aaeb0e_idx')],
                'unique_together': {('content', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChannelContentSave',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='broadcasts.channelcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_channel_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_save',
                'indexes': [models.Index(fields=['content', 'created_at'], name='channel_con_content_509c28_idx'), models.Index(fields=['user', 'created_at'], name='channel_con_user_id_55e6f1_idx')],
                'unique_together': {('content', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChannelContentReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reaction', models.CharField(default='like', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='broadcasts.channelcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_content_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_reaction',
                'indexes': [models.Index(fields=['content', 'reaction'], name='channel_con_content_e605b9_idx'), models.Index(fields=['user', 'created_at'], name='channel_con_user_id_7ad4de_idx')],
                'unique_together': {('content', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChannelContentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='broadcasts.channelcontent')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='broadcasts.channelcontentcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_content_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_comment',
                'indexes': [models.Index(fields=['content', 'created_at'], name='channel_con_content_701b9e_idx'), models.Index(fields=['user', 'created_at'], name='channel_con_user_id_88d77c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BroadcastPlaylistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='broadcasts.channelcontent')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='broadcasts.broadcastplaylist')),
            ],
            options={
                'db_table': 'broadcast_playlist_item',
                'ordering': ['sort_order', 'added_at'],
                'indexes': [models.Index(fields=['playlist', 'sort_order'], name='broadcast_p_playlis_6bd2a6_idx'), models.Index(fields=['content'], name='broadcast_p_content_771984_idx')],
                'unique_together': {('playlist', 'content')},
            },
        ),
    ]
