# Generated by Django 4.2.25 on 2026-05-12 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0036_channelwatchhistory_channelcontentsave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModerationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('channel', 'Channel'), ('content', 'Content'), ('comment', 'Comment')], db_index=True, max_length=16)),
                ('target_id', models.UUIDField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('action', models.CharField(choices=[('none', 'None'), ('keep', 'Keep'), ('hide', 'Hide'), ('remove', 'Remove'), ('restrict_comments', 'Restrict comments')], default='none', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to='broadcasts.broadcastchannel')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to='broadcasts.channelcontentcomment')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to='broadcasts.channelcontent')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_moderation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_moderation_record',
                'indexes': [models.Index(fields=['channel', 'status', 'created_at'], name='channel_mod_channel_50fb11_idx'), models.Index(fields=['target_type', 'target_id'], name='channel_mod_target__b0f0bb_idx'), models.Index(fields=['reporter', 'created_at'], name='channel_mod_reporte_adf48f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelAnalyticsDailyRollup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('watch_time_seconds', models.PositiveBigIntegerField(default=0)),
                ('average_duration_seconds', models.PositiveIntegerField(default=0)),
                ('subscribers_gained', models.PositiveIntegerField(default=0)),
                ('subscribers_lost', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0)),
                ('embed_impressions', models.PositiveIntegerField(default=0)),
                ('live_peak_viewers', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_rollups', to='broadcasts.broadcastchannel')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_rollups', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_analytics_daily_rollup',
                'indexes': [models.Index(fields=['channel', 'date'], name='channel_ana_channel_4be1fa_idx'), models.Index(fields=['content', 'date'], name='channel_ana_content_e0c9fd_idx')],
                'unique_together': {('channel', 'content', 'date')},
            },
        ),
    ]
