# Generated by Django 4.2.25 on 2026-05-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0037_channelmoderationrecord_channelanalyticsdailyrollup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastitem',
            name='source_type',
            field=models.CharField(choices=[('community_post', 'Community Post'), ('partner_post', 'Partner Post'), ('channel_message', 'Channel Message'), ('broadcast_channel', 'Broadcast Channel'), ('channel_content', 'Channel Content'), ('broadcast_feed_entry', 'Broadcast Feed Entry'), ('market_product', 'Market Product'), ('market_service', 'Market Service'), ('education_course', 'Education Course'), ('education_profile', 'Education Profile'), ('education_broadcast', 'Education Broadcast')], db_index=True, max_length=32),
        ),
    ]
