# Generated by Django 4.2.25 on 2026-05-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0038_alter_broadcastitem_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], db_index=True, default='approved', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='broadcasts.educationinstitutionbroadcast')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='broadcasts.educationinstitutioncourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='broadcasts.educationinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_course_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'status'], name='education_c_institu_8e5fe1_idx'), models.Index(fields=['broadcast', 'status'], name='education_c_broadca_2dc0da_idx'), models.Index(fields=['course', 'status'], name='education_c_course__19aafc_idx'), models.Index(fields=['user', 'created_at'], name='education_c_user_id_c34dc6_idx')],
                'unique_together': {('broadcast', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EducationCourseQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('hidden', 'Hidden'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_education_course_questions', to=settings.AUTH_USER_MODEL)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to='broadcasts.educationinstitutionbroadcast')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='broadcasts.educationinstitutioncourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to='broadcasts.educationinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_course_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_course_question',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'status'], name='education_c_institu_52e5a5_idx'), models.Index(fields=['broadcast', 'status'], name='education_c_broadca_ce2928_idx'), models.Index(fields=['course', 'status'], name='education_c_course__97a563_idx'), models.Index(fields=['user', 'created_at'], name='education_c_user_id_38a3d5_idx')],
            },
        ),
    ]
