# Generated by Django 4.2.25 on 2026-06-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0044_chat_membership_download'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelactivityevent',
            new_name='channel_act_channel_0a5be2_idx',
            old_name='chan_activity_channel_created_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcommentreaction',
            new_name='channel_com_comment_a88f59_idx',
            old_name='chan_comm_react_comment_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcommentreaction',
            new_name='channel_com_user_id_d45f9b_idx',
            old_name='chan_comm_react_user_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcontentchapter',
            new_name='channel_con_content_b90d15_idx',
            old_name='chan_chapter_content_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcontentclip',
            new_name='channel_con_content_d2ad74_idx',
            old_name='chan_clip_content_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcontentclip',
            new_name='channel_con_created_3b5f07_idx',
            old_name='chan_clip_creator_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcontentcomment',
            new_name='channel_con_content_48fda7_idx',
            old_name='chan_comm_content_pinned_idx',
        ),
        migrations.RenameIndex(
            model_name='livestreamcamera',
            new_name='live_stream_stream__c416c2_idx',
            old_name='lsc_stream_active_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontentplaylist',
            new_name='user_conten_user_id_2f7f41_idx',
            old_name='ucp_user_vis_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontentplaylist',
            new_name='user_conten_user_id_3b2387_idx',
            old_name='ucp_user_syskey_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontentplaylist',
            new_name='user_conten_user_id_017a67_idx',
            old_name='ucp_user_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontentplaylistitem',
            new_name='user_conten_playlis_1de74d_idx',
            old_name='ucpi_pl_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='usercontentplaylistitem',
            new_name='user_conten_content_b4615b_idx',
            old_name='ucpi_content_at_idx',
        ),
    ]
