# Generated by Django 4.2.25 on 2026-06-11 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_conversation_direct_key'),
        ('broadcasts', '0045_rename_chan_activity_channel_created_idx_channel_act_channel_0a5be2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAdCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('budget_cents', models.PositiveIntegerField(default=0)),
                ('spent_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_content_types', models.JSONField(blank=True, default=list)),
                ('target_countries', models.JSONField(blank=True, default=list)),
                ('target_age_buckets', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='draft', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='broadcasts.broadcastchannel')),
            ],
            options={
                'db_table': 'channel_ad_campaign',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentCopyrightClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimant_name', models.CharField(blank=True, default='', max_length=220)),
                ('claim_type', models.CharField(choices=[('audio', 'Audio match'), ('video', 'Video match'), ('manual', 'Manual claim')], default='manual', max_length=8)),
                ('asset_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('matched', 'Matched'), ('disputed', 'Under dispute'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=16)),
                ('dispute_reason', models.TextField(blank=True, default='')),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_copyright_claims', to='broadcasts.broadcastchannel')),
            ],
            options={
                'db_table': 'channel_content_copyright_claim',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('sha256', 'SHA-256 (file hash)'), ('perceptual', 'Perceptual (visual)'), ('audio', 'Audio fingerprint')], default='sha256', max_length=16)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'channel_content_fingerprint',
            },
        ),
        migrations.CreateModel(
            name='ChannelHomepageShelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('shelf_type', models.CharField(choices=[('uploads', 'Uploads'), ('playlists', 'Playlists'), ('live', 'Live'), ('shorts', 'Shorts'), ('featured', 'Featured'), ('custom', 'Custom')], default='uploads', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_shelves', to='broadcasts.broadcastchannel')),
            ],
            options={
                'db_table': 'channel_homepage_shelf',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='broadcastplaylist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastplaylist',
            name='is_collaborative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='age_restriction',
            field=models.CharField(choices=[('none', 'None'), ('13+', '13+'), ('18+', '18+')], db_index=True, default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='content_rating',
            field=models.CharField(choices=[('NR', 'Not Rated'), ('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R')], default='NR', max_length=8),
        ),
        migrations.AddField(
            model_name='channellivestream',
            name='dvr_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channellivestream',
            name='dvr_window_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='channellivestream',
            name='latency_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('low', 'Low Latency'), ('ultra_low', 'Ultra Low Latency')], default='normal', max_length=16),
        ),
        migrations.CreateModel(
            name='ChannelMonetizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_enabled', models.BooleanField(default=False)),
                ('membership_enabled', models.BooleanField(default=False)),
                ('ad_revenue_enabled', models.BooleanField(default=False)),
                ('revenue_share_pct', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('payout_threshold_cents', models.PositiveIntegerField(default=10000)),
                ('payout_schedule', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on_request', 'On Request')], default='on_request', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monetization_settings', to='broadcasts.broadcastchannel')),
            ],
            options={
                'db_table': 'channel_monetization_settings',
            },
        ),
        migrations.CreateModel(
            name='ChannelFingerprintMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_matches', to='broadcasts.channelcontentcopyrightclaim')),
                ('matched_fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_match', to='broadcasts.channelcontentfingerprint')),
                ('source_fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_source', to='broadcasts.channelcontentfingerprint')),
            ],
            options={
                'db_table': 'channel_fingerprint_match',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentWatchSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_start_seconds', models.PositiveIntegerField()),
                ('segment_end_seconds', models.PositiveIntegerField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_segments', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_watch_segment',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentWatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('watch_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_watched_seconds', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(db_index=True, default='direct', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='broadcasts.channelcontent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_watch_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_watch_event',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-generated')], default='auto', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('text_plain', models.TextField(blank=True, default='')),
                ('vtt_url', models.URLField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_job_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_transcript',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentTrafficSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('source_type', models.CharField(choices=[('search', 'Search'), ('browse', 'Browse'), ('external', 'External'), ('direct', 'Direct'), ('recommended', 'Recommended'), ('notification', 'Notification'), ('playlist', 'Playlist'), ('channel_page', 'Channel Page'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('watch_time_seconds', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_traffic_source',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('message', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='broadcasts.channelcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_content_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_tip',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_by', to='broadcasts.channelcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_queue',
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelContentProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=128)),
                ('product_url', models.URLField(blank=True, default='')),
                ('product_title', models.CharField(blank=True, default='', max_length=220)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('price_display', models.CharField(blank=True, default='', max_length=32)),
                ('timestamp_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_product',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentPremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_url', models.URLField(blank=True, default='')),
                ('pre_chat_opens_at', models.DateTimeField(blank=True, null=True)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premiere', to='broadcasts.channelcontent')),
                ('lobby_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiere_lobby', to='chat.conversation')),
            ],
            options={
                'db_table': 'channel_content_premiere',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentGeoRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('allow', 'Allow only listed countries'), ('block', 'Block listed countries')], default='block', max_length=8)),
                ('countries', models.JSONField(blank=True, default=list, help_text='List of ISO 3166-1 alpha-2 country codes.')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_restriction', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_geo_restriction',
            },
        ),
        migrations.AddField(
            model_name='channelcontentfingerprint',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='broadcasts.channelcontent'),
        ),
        migrations.CreateModel(
            name='ChannelContentDemographicSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('age_bucket', models.CharField(choices=[('13-17', '13–17'), ('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55+', '55+'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('watch_time_seconds', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographic_snapshots', to='broadcasts.broadcastchannel')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographic_snapshots', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_demographic_snapshot',
            },
        ),
        migrations.AddField(
            model_name='channelcontentcopyrightclaim',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright_claims', to='broadcasts.channelcontent'),
        ),
        migrations.CreateModel(
            name='ChannelContentAutoChapterSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed'), ('applied', 'Applied to chapters')], db_index=True, default='pending', max_length=8)),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='[{"title": str, "start_seconds": int}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_chapter_suggestions', to='broadcasts.channelcontent')),
                ('transcript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_chapter_suggestions', to='broadcasts.channelcontenttranscript')),
            ],
            options={
                'db_table': 'channel_content_auto_chapter_suggestion',
            },
        ),
        migrations.CreateModel(
            name='ChannelContentAudioTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_content_audio_track',
            },
        ),
        migrations.CreateModel(
            name='ChannelCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_name', models.CharField(blank=True, default='', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='broadcasts.channelcategory')),
            ],
            options={
                'db_table': 'channel_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelAdSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement', models.CharField(choices=[('pre_roll', 'Pre-roll'), ('mid_roll', 'Mid-roll'), ('post_roll', 'Post-roll')], default='pre_roll', max_length=12)),
                ('timestamp_seconds', models.PositiveIntegerField(default=0)),
                ('is_skippable', models.BooleanField(default=True)),
                ('skip_after_seconds', models.PositiveIntegerField(default=5)),
                ('ad_media_url', models.URLField(blank=True, default='')),
                ('click_url', models.URLField(blank=True, default='')),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_slots', to='broadcasts.channeladcampaign')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_slots', to='broadcasts.channelcontent')),
            ],
            options={
                'db_table': 'channel_ad_slot',
            },
        ),
        migrations.CreateModel(
            name='ChannelAdImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('skipped', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='broadcasts.channeladslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_ad_impression',
            },
        ),
        migrations.CreateModel(
            name='ChannelPayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('payment_method_ref', models.CharField(blank=True, default='', max_length=256)),
                ('notes', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='broadcasts.broadcastchannel')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_payout_request',
                'indexes': [models.Index(fields=['channel', 'status'], name='channel_pay_channel_773707_idx'), models.Index(fields=['requested_by', 'status'], name='channel_pay_request_c1c574_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembershipGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('redeem_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_membership_gifts', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_membership_gifts', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='broadcasts.channelmembershiptier')),
            ],
            options={
                'db_table': 'channel_membership_gift',
                'indexes': [models.Index(fields=['tier', 'status'], name='channel_mem_tier_id_067602_idx'), models.Index(fields=['gifter', 'status'], name='channel_mem_gifter__a55b98_idx'), models.Index(fields=['recipient', 'status'], name='channel_mem_recipie_3eac13_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelLiveStreamTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('message', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_until', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='broadcasts.channellivestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_stream_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_live_stream_tip',
                'indexes': [models.Index(fields=['live_stream', 'status'], name='channel_liv_live_st_f93165_idx'), models.Index(fields=['live_stream', 'is_pinned'], name='channel_liv_live_st_a1550d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelLiveStreamTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('twitch', 'Twitch'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('rtmp_url', models.CharField(max_length=512)),
                ('stream_key', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('streaming', 'Streaming'), ('error', 'Error'), ('ended', 'Ended')], db_index=True, default='idle', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulcast_targets', to='broadcasts.channellivestream')),
            ],
            options={
                'db_table': 'channel_live_stream_target',
                'indexes': [models.Index(fields=['live_stream', 'status'], name='channel_liv_live_st_aab43e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelLiveStreamGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('invite_token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('cohost', 'Co-host'), ('guest', 'Guest')], default='guest', max_length=16)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('active', 'Active'), ('removed', 'Removed')], db_index=True, default='invited', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_stream_guest_invitations', to=settings.AUTH_USER_MODEL)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='broadcasts.channellivestream')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_stream_guest_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_live_stream_guest',
                'indexes': [models.Index(fields=['live_stream', 'status'], name='channel_liv_live_st_317d12_idx'), models.Index(fields=['user', 'status'], name='channel_liv_user_id_a99ef5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelKeywordFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('block', 'Block (auto-remove)'), ('hold', 'Hold for review'), ('flag', 'Flag only')], default='hold', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_filters', to='broadcasts.broadcastchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keyword_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_keyword_filter',
                'indexes': [models.Index(fields=['channel', 'is_active'], name='channel_key_channel_ec8c35_idx')],
                'unique_together': {('channel', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='ChannelHomepageShelfItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_items', to='broadcasts.channelcontent')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_items', to='broadcasts.broadcastplaylist')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='broadcasts.channelhomepageshelf')),
            ],
            options={
                'db_table': 'channel_homepage_shelf_item',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['shelf', 'sort_order'], name='channel_hom_shelf_i_b13c0f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='channelhomepageshelf',
            index=models.Index(fields=['channel', 'is_active'], name='channel_hom_channel_6d0a07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelfingerprintmatch',
            unique_together={('source_fingerprint', 'matched_fingerprint')},
        ),
        migrations.AddIndex(
            model_name='channelcontentwatchsegment',
            index=models.Index(fields=['content', 'view_count'], name='channel_con_content_70a940_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelcontentwatchsegment',
            unique_together={('content', 'segment_start_seconds')},
        ),
        migrations.AddIndex(
            model_name='channelcontentwatchevent',
            index=models.Index(fields=['content', 'user'], name='channel_con_content_452d30_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentwatchevent',
            index=models.Index(fields=['content', 'created_at'], name='channel_con_content_1f30f1_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentwatchevent',
            index=models.Index(fields=['user', 'source'], name='channel_con_user_id_4ac1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontenttranscript',
            index=models.Index(fields=['content', 'status'], name='channel_con_content_8254a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelcontenttranscript',
            unique_together={('content', 'language_code', 'source')},
        ),
        migrations.AddIndex(
            model_name='channelcontenttrafficsource',
            index=models.Index(fields=['content', 'date'], name='channel_con_content_4dcdef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelcontenttrafficsource',
            unique_together={('content', 'date', 'source_type')},
        ),
        migrations.AddIndex(
            model_name='channelcontenttip',
            index=models.Index(fields=['content', 'status'], name='channel_con_content_36ddd1_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontenttip',
            index=models.Index(fields=['user', 'status'], name='channel_con_user_id_a38cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentqueue',
            index=models.Index(fields=['user', 'position'], name='channel_con_user_id_66a0d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelcontentqueue',
            unique_together={('user', 'content')},
        ),
        migrations.AddIndex(
            model_name='channelcontentproduct',
            index=models.Index(fields=['content', 'timestamp_seconds'], name='channel_con_content_8f7c73_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentproduct',
            index=models.Index(fields=['product_id'], name='channel_con_product_848d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentfingerprint',
            index=models.Index(fields=['fingerprint_hash', 'algorithm'], name='channel_con_fingerp_971edf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelcontentfingerprint',
            unique_together={('content', 'algorithm')},
        ),
        migrations.AddIndex(
            model_name='channelcontentdemographicsnapshot',
            index=models.Index(fields=['channel', 'snapshot_date'], name='channel_con_channel_dd099a_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentdemographicsnapshot',
            index=models.Index(fields=['content', 'snapshot_date'], name='channel_con_content_3e8ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentdemographicsnapshot',
            index=models.Index(fields=['snapshot_date', 'country_code'], name='channel_con_snapsho_870cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentcopyrightclaim',
            index=models.Index(fields=['content', 'status'], name='channel_con_content_39b2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentcopyrightclaim',
            index=models.Index(fields=['claimant_channel', 'status'], name='channel_con_claiman_9ff259_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcontentautochaptersuggestion',
            index=models.Index(fields=['content', 'status'], name='channel_con_content_aaaffa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelcontentaudiotrack',
            unique_together={('content', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='channeladslot',
            index=models.Index(fields=['content', 'placement'], name='channel_ad__content_63280d_idx'),
        ),
        migrations.AddIndex(
            model_name='channeladslot',
            index=models.Index(fields=['campaign', 'placement'], name='channel_ad__campaig_921025_idx'),
        ),
        migrations.AddIndex(
            model_name='channeladimpression',
            index=models.Index(fields=['slot', 'created_at'], name='channel_ad__slot_id_811ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='channeladimpression',
            index=models.Index(fields=['user', 'created_at'], name='channel_ad__user_id_eb20fa_idx'),
        ),
        migrations.AddIndex(
            model_name='channeladcampaign',
            index=models.Index(fields=['advertiser_channel', 'status'], name='channel_ad__adverti_484981_idx'),
        ),
        migrations.AddIndex(
            model_name='channeladcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='channel_ad__status_29473e_idx'),
        ),
    ]
