# Generated by Django 4.2.25 on 2026-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0047_digitalbadge_ebook_kingdommusictrack_liveclassroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='broadcastvideo',
            name='video_url',
            field=models.URLField(max_length=2048),
        ),
    ]
