# Generated by Django 4.2.25 on 2026-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0048_widen_broadcastvideo_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelcontent',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='channelcontentasset',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='channelcontentasset',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
