# Generated by Django 4.2.25 on 2026-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0049_widen_channel_content_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinstitutionassessment',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutionbroadcast',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutionclasssession',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutioncourse',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutionevent',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutionlesson',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutionmaterial',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutionmaterial',
            name='resource_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='educationinstitutionprogram',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
