# Generated by Django 4.2.25 on 2026-08-17 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0050_url_field_length_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitutionCourseAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'education_institution_course_access_request',
            },
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='flutterwave_subaccount_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='payout_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='payout_account_status',
            field=models.CharField(choices=[('not_connected', 'Not connected'), ('pending', 'Pending'), ('active', 'Active')], default='not_connected', max_length=16),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='payout_bank_last4',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourse',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourse',
            name='price_currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourse',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncourse',
            index=models.Index(fields=['institution', 'visibility'], name='education_i_institu_c43f4e_idx'),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourseaccessrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='broadcasts.educationinstitutioncourse'),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourseaccessrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_education_course_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourseaccessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_course_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncourseaccessrequest',
            index=models.Index(fields=['course', 'status'], name='education_i_course__a54308_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncourseaccessrequest',
            index=models.Index(fields=['user', 'status'], name='education_i_user_id_6c6faa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='educationinstitutioncourseaccessrequest',
            unique_together={('course', 'user')},
        ),
    ]
