# Generated by Django 4.2.25 on 2026-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0051_course_pricing_access_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastchannel',
            name='flutterwave_subaccount_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='broadcastchannel',
            name='payout_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='broadcastchannel',
            name='payout_account_status',
            field=models.CharField(choices=[('not_connected', 'Not connected'), ('pending', 'Pending'), ('active', 'Active')], default='not_connected', max_length=16),
        ),
        migrations.AddField(
            model_name='broadcastchannel',
            name='payout_bank_last4',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
