# Generated by Django 4.2.25 on 2026-08-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0052_payout_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classassignment',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='liveclassroom',
            name='host',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='scholarship',
        ),
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='studentbadge',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprogressreport',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='studentprogressreport',
            name='student',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='ClassAssignment',
        ),
        migrations.DeleteModel(
            name='DigitalBadge',
        ),
        migrations.DeleteModel(
            name='LiveClassroom',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
        migrations.DeleteModel(
            name='StudentBadge',
        ),
        migrations.DeleteModel(
            name='StudentProgressReport',
        ),
    ]
