# Generated by Django 4.2.25 on 2026-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0053_remove_classassignment_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastchannel',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='broadcastchannel',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastchannel',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastchannel',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
