# Generated by Django 4.2.25 on 2026-08-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0042_partnerorganizationlink_and_more'),
        ('broadcasts', '0054_broadcastchannel_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitution',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_institutions', to='partners.partner'),
        ),
        migrations.AddIndex(
            model_name='educationinstitution',
            index=models.Index(fields=['partner'], name='education_i_partner_f38e49_idx'),
        ),
    ]
