# Generated by Django 4.2.25 on 2026-09-01 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0055_educationinstitution_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContentPollVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_index', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='broadcasts.channelcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_content_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_content_poll_vote',
                'unique_together': {('content', 'user')},
            },
        ),
    ]
