# Generated by Django 4.2.25 on 2026-09-06 07:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.models import TextField, Value
from django.db.models.functions import Coalesce


def backfill_search_vector(apps, schema_editor):
    # Without this, every piece of content that existed before this
    # migration would have search_vector=NULL and simply never appear in
    # search results until someone happened to re-save it - the new
    # search-vector-based BroadcastSearchView would look like it deleted
    # the entire existing content library.
    ChannelContent = apps.get_model("broadcasts", "ChannelContent")
    empty_text = Value("", output_field=TextField())
    ChannelContent.objects.update(
        search_vector=(
            SearchVector("title", weight="A")
            + SearchVector(Coalesce("description", empty_text), weight="B")
            + SearchVector(Coalesce("text_plain", empty_text), weight="B")
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0057_seed_channel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcontent',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='channelcontent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='channel_content_search_gin'),
        ),
        migrations.RunPython(backfill_search_vector, migrations.RunPython.noop),
    ]
