# Generated by Django 4.2.25 on 2026-09-12 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0058_channelcontent_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastvideo',
            name='moderation_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastvideo',
            name='moderation_passed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastvideo',
            name='moderation_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_broadcast_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastvideo',
            name='moderation_status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('passed', 'Passed'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], db_index=True, default='pending_review', max_length=16),
        ),
    ]
