# Generated by Django 4.2.25 on 2026-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0059_broadcast_video_moderation_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembershipgift',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending', 'Pending'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
    ]
