# Generated by Django 4.2.25 on 2026-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0060_alter_channelmembershipgift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastitem',
            name='save_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
