# Generated by Django 4.2.25 on 2026-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0061_broadcastitem_save_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinstitutionbroadcast',
            name='broadcast_kind',
            field=models.CharField(choices=[('program', 'Program'), ('course', 'Course'), ('lesson', 'Lesson'), ('class_session', 'Class Session'), ('training_session', 'Training Session'), ('event', 'Event'), ('institution_notice', 'Institution Notice'), ('institution', 'Institution Spotlight')], max_length=24),
        ),
    ]
