# Generated by Django 4.2.25 on 2026-09-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_communitymembership_status_and_more'),
        ('channels', '0005_alter_channel_channel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_group_invite_token'),
        ('broadcasts', '0062_alter_educationinstitutionbroadcast_broadcast_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitutionClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'education_institution_class',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='educationinstitutioncourse',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_courses', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_programs', to='communities.community'),
        ),
        # AddIndex operations for the three institution_class indexes below
        # (course/enrollment/staffassignment) are deliberately placed after
        # every AddField in this migration, not in makemigrations' original
        # generated order — it interleaved them between the CreateModel and
        # the institution_class AddField operations on those same models,
        # which fails at apply time (index on a column that doesn't exist
        # yet). Verified via `manage.py sqlmigrate` after reordering.
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_education_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_classes', to='groups.group'),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='broadcasts.educationinstitution'),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='broadcasts.educationinstitutionprogram'),
        ),
        migrations.AddField(
            model_name='educationinstitutioncourse',
            name='institution_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='broadcasts.educationinstitutionclass'),
        ),
        migrations.AddField(
            model_name='educationinstitutionenrollment',
            name='institution_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='broadcasts.educationinstitutionclass'),
        ),
        migrations.AddField(
            model_name='educationinstitutionstaffassignment',
            name='institution_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='broadcasts.educationinstitutionclass'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionclass',
            index=models.Index(fields=['institution', 'status'], name='education_i_institu_b2cd47_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionclass',
            index=models.Index(fields=['program', 'status'], name='education_i_program_e6f730_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutioncourse',
            index=models.Index(fields=['institution_class', 'status'], name='education_i_institu_a080d1_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionenrollment',
            index=models.Index(fields=['institution_class', 'status'], name='education_i_institu_7d7165_idx'),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionstaffassignment',
            index=models.Index(fields=['institution_class', 'status'], name='education_i_institu_df40f0_idx'),
        ),
    ]
