# Generated by Django 4.2.25 on 2026-09-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0063_education_program_class_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitutionbroadcast',
            name='institution_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='broadcasts.educationinstitutionclass'),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='class_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='seat_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='term',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='educationinstitutionclass',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='duration_unit',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='duration_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='entry_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='price_currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='program_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='seat_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='target_audience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationinstitutionprogram',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='educationinstitutionbroadcast',
            name='broadcast_kind',
            field=models.CharField(choices=[('program', 'Program'), ('course', 'Course'), ('lesson', 'Lesson'), ('institution_class', 'Class'), ('class_session', 'Class Session'), ('training_session', 'Training Session'), ('event', 'Event'), ('institution_notice', 'Institution Notice'), ('institution', 'Institution Spotlight')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='educationinstitutionbroadcast',
            index=models.Index(fields=['institution_class', 'status'], name='education_i_institu_757548_idx'),
        ),
    ]
