# Generated by Django 4.2.25 on 2025-10-11 11:17

import apps.notifications.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('notifications', models.JSONField(default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=64, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('priority', models.CharField(blank=True, max_length=16, null=True)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('schedule_json', models.JSONField(blank=True, default=dict)),
                ('channels_json', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('title_template', models.CharField(max_length=400)),
                ('body_template', models.TextField()),
                ('default_channel', models.CharField(default='IN_APP', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=64, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WEBHOOK', 'Webhook')], default='IN_APP', max_length=32)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actions_json', models.JSONField(blank=True, default=list)),
                ('personalization_score', models.FloatField(default=0.0)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], default='NEUTRAL', max_length=16)),
                ('reward_points', models.IntegerField(blank=True, null=True)),
                ('is_snoozed', models.BooleanField(default=False)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('channel', models.CharField(max_length=32)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=32)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'channel'], name='notificatio_status_1f3a81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'),
        ),
    ]
