# Generated by Django 4.2.25 on 2026-04-28 23:34

import apps.notifications.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-App'), ('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WEBHOOK', 'Webhook')], default='IN_APP', max_length=32),
        ),
        migrations.CreateModel(
            name='NotificationDeviceToken',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('push_token', models.TextField()),
                ('token_type', models.CharField(default='fcm', max_length=20)),
                ('apns_token', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'enabled'], name='notificatio_user_id_0e397e_idx'), models.Index(fields=['device_id'], name='notificatio_device__7e2949_idx')],
                'unique_together': {('user_id', 'device_id', 'push_token')},
            },
        ),
    ]
