# Generated by Django 4.2.25 on 2026-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_channel_notificationdevicetoken'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedup_key__isnull', False), ('is_deleted', False)), fields=('user_id', 'dedup_key'), name='uniq_active_notification_user_dedup_key'),
        ),
    ]
