# Generated by Django 4.2.25 on 2026-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_uniq_active_notification_user_dedup_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-App'), ('PUSH', 'Push'), ('EMAIL', 'Email'), ('WEBHOOK', 'Webhook')], default='IN_APP', max_length=32),
        ),
    ]
