# Generated by Django 5.2.8 on 2025-11-16 13:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('direct', 'Direct (1:1)'), ('group', 'Group'), ('channel', 'Channel'), ('thread', 'Thread / Sub-room'), ('system', 'System/Internal')], db_index=True, default='direct', max_length=16)),
                ('title', models.CharField(blank=True, help_text='Display name for group/channel/thread. Optional for direct chats.', max_length=255)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='When locked, only admins/owners may send messages (plus send_policy).')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation',
            },
        ),
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('code', models.CharField(help_text='Machine-readable permission code (e.g. chat.send_message).', max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'rbac_permission_definition',
            },
        ),
        migrations.CreateModel(
            name='ConversationSettings',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='chat.conversation')),
                ('send_policy', models.CharField(choices=[('all_members', 'All members can send'), ('admins_only', 'Only admins/owners can send')], default='all_members', max_length=32)),
                ('join_policy', models.CharField(choices=[('invite_only', 'Invite only'), ('link_join', 'Join via share link'), ('open', 'Anyone within parent scope')], default='invite_only', max_length=32)),
                ('info_edit_policy', models.CharField(choices=[('admins_only', 'Only admins/owners can edit'), ('all_members', 'All members can edit')], default='admins_only', max_length=32)),
                ('subroom_policy', models.CharField(choices=[('admins_only', 'Only admins/owners can create sub-rooms'), ('all_members', 'Any member can create sub-rooms')], default='all_members', max_length=32)),
                ('max_subroom_depth', models.PositiveIntegerField(default=8, help_text='Soft limit for nested sub-rooms depth (0 = top-level).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_conversation_settings',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('readonly', 'Read-only')], default='member', max_length=16)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False, help_text="If true, user shouldn't receive messages from this conversation.")),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation_member',
            },
        ),
        migrations.CreateModel(
            name='MessageThreadLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_message_key', models.CharField(help_text='Message ID/key from the message storage (e.g., Mongo _id).', max_length=255)),
                ('depth', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_message_thread', to='chat.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads_created', to=settings.AUTH_USER_MODEL)),
                ('parent_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_threads', to='chat.conversation')),
                ('parent_thread', models.ForeignKey(blank=True, help_text='If this thread is created from a message inside another thread.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subthreads', to='chat.messagethreadlink')),
            ],
            options={
                'db_table': 'chat_message_thread_link',
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('partner', 'Partner'), ('community', 'Community'), ('channel', 'Channel'), ('group', 'Group'), ('conversation', 'Conversation')], db_index=True, default='conversation', max_length=32)),
                ('scope_id', models.CharField(blank=True, help_text='ID of the scope instance (UUID or int, stored as string).', max_length=64, null=True)),
                ('is_system', models.BooleanField(default=False, help_text='If true, role is system-defined and cannot be deleted by users.')),
                ('is_default_for_scope', models.BooleanField(default=False, help_text='Used as auto-assign default role for new members in that scope.')),
                ('rank', models.IntegerField(default=100, help_text='Lower = more privileged, used for UI sorting & conflict resolution.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_role_definition',
            },
        ),
        migrations.CreateModel(
            name='PrincipalRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('partner', 'Partner'), ('community', 'Community'), ('channel', 'Channel'), ('group', 'Group'), ('conversation', 'Conversation')], db_index=True, max_length=32)),
                ('scope_id', models.CharField(db_index=True, help_text='ID of the scope instance as string; must match role.scope_id (if set).', max_length=64)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_assignments', to='chat.roledefinition')),
            ],
            options={
                'db_table': 'rbac_principal_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to='chat.permissiondefinition')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='chat.roledefinition')),
            ],
            options={
                'db_table': 'rbac_role_permission',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type', 'created_at'], name='chat_conver_type_b8c77c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'user'], name='chat_conver_convers_79dd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'joined_at'], name='chat_conver_user_id_8de2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'base_role'], name='chat_conver_convers_f12abe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagethreadlink',
            index=models.Index(fields=['parent_conversation', 'parent_message_key'], name='chat_messag_parent__001152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagethreadlink',
            unique_together={('parent_conversation', 'parent_message_key')},
        ),
        migrations.AlterUniqueTogether(
            name='roledefinition',
            unique_together={('slug', 'scope_type', 'scope_id')},
        ),
        migrations.AddIndex(
            model_name='principalrole',
            index=models.Index(fields=['user', 'scope_type', 'scope_id'], name='rbac_princi_user_id_5a1c54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
