# Generated by Django 5.2.8 on 2025-11-18 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Optional URL for conversation avatar (group/channel icon).'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description / about text for this conversation.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last message in this conversation (from message service).', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_preview',
            field=models.CharField(blank=True, help_text='Short preview of the last message for UI lists (optional, denormalized).', max_length=255),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='color',
            field=models.CharField(blank=True, help_text='Optional color/tag for UI (e.g. avatar color).', max_length=16),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional per-conversation nickname for this member.', max_length=255),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='notification_level',
            field=models.CharField(choices=[('all', 'All messages'), ('mentions', 'Mentions only'), ('none', 'No notifications')], default='all', help_text='Notification preference for this conversation.', max_length=16),
        ),
        migrations.AddField(
            model_name='conversationsettings',
            name='allow_attachments',
            field=models.BooleanField(default=True, help_text='Whether file/media attachments are allowed in this conversation.'),
        ),
        migrations.AddField(
            model_name='conversationsettings',
            name='allow_reactions',
            field=models.BooleanField(default=True, help_text='Whether message reactions are allowed in this conversation.'),
        ),
        migrations.AddField(
            model_name='conversationsettings',
            name='allow_stickers',
            field=models.BooleanField(default=True, help_text='Whether stickers are allowed in this conversation.'),
        ),
        migrations.AddField(
            model_name='conversationsettings',
            name='message_retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='If set, messages older than this should be auto-deleted by the message service. Null means keep forever.', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct (1:1)'), ('group', 'Group'), ('channel', 'Channel'), ('post', 'Post'), ('thread', 'Thread / Sub-room'), ('system', 'System/Internal')], db_index=True, default='direct', max_length=16),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_archived', 'last_message_at'], name='chat_conver_is_arch_3d132c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'notification_level'], name='chat_conver_user_id_82770a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethreadlink',
            index=models.Index(fields=['child_conversation'], name='chat_messag_child_c_68dffa_idx'),
        ),
    ]
