# Generated by Django 5.2.8 on 2025-11-19 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_avatar_url_conversation_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='request_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the recipient accepted the request (or replied).', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='request_initiator',
            field=models.ForeignKey(blank=True, help_text='User who sent the first message / initiated the direct chat request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_requests_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='request_recipient',
            field=models.ForeignKey(blank=True, help_text='User who receives the direct chat request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='request_rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the recipient rejected/blocked the request.', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='request_state',
            field=models.CharField(choices=[('none', 'Not a request'), ('pending', 'Pending acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected / blocked')], db_index=True, default='none', help_text='Direct chat request workflow state.', max_length=16),
        ),
    ]
