# Generated by Django 5.2.8 on 2025-12-10 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_request_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['request_recipient', 'request_state'], name='chat_conver_request_27e044_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['request_initiator', 'request_state'], name='chat_conver_request_919fd1_idx'),
        ),
    ]
