# Generated by Django 5.2.8 on 2025-12-13 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_chat_conver_request_27e044_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived direct chat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_archived_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked direct chat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_locked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
