# Generated by Django 5.2.8 on 2025-12-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_archived_by_conversation_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_seq',
            field=models.BigIntegerField(default=0, help_text='Monotonic sequence counter for messages in this conversation.'),
        ),
    ]
