# Generated by Django 4.2.25 on 2026-04-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_last_message_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the member last advanced the read watermark.', null=True),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_seq',
            field=models.BigIntegerField(default=0, help_text='Highest authoritative conversation sequence read by this member.'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'last_read_seq'], name='chat_conver_convers_104905_idx'),
        ),
    ]
